// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_Networking_NetworkListManager_2_H
#define WIN32_Windows_Win32_Networking_NetworkListManager_2_H
#include "win32/Windows.Win32.Networking.NetworkListManager.h"
#include "win32/impl/Windows.Win32.Networking.NetworkListManager.1.h"
WIN32_EXPORT namespace win32::Windows::Win32::Networking::NetworkListManager
{
ApiTable g_api_table;

#pragma region abi_methods
extern "C"
{
}

#pragma endregion abi_methods

}
#endif
