// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_System_DeploymentServices_2_H
#define WIN32_Windows_Win32_System_DeploymentServices_2_H
#include "win32/Windows.Win32.System.DeploymentServices.h"
#include "win32/impl/Windows.Win32.System.DeploymentServices.1.h"
WIN32_EXPORT namespace win32::Windows::Win32::System::DeploymentServices
{
ApiTable g_api_table;

#pragma region abi_methods
extern "C"
{
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliClose(win32::Windows::Win32::Foundation::HANDLE Handle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(Handle);

        auto win32_impl_result = g_api_table.WdsCliClose(Handle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliRegisterTrace(win32::Windows::Win32::System::DeploymentServices::PFN_WdsCliTraceFunction* pfn) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pfn);

        auto win32_impl_result = g_api_table.WdsCliRegisterTrace(pfn);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliFreeStringArray(win32::Windows::Win32::Foundation::PWSTR* ppwszArray, uint32_t ulCount) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(ppwszArray);
        ORBIT_TRACK_PARAM(ulCount);

        auto win32_impl_result = g_api_table.WdsCliFreeStringArray(ppwszArray, ulCount);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliFindFirstImage(win32::Windows::Win32::Foundation::HANDLE hSession, win32::Windows::Win32::Foundation::HANDLE* phFindHandle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hSession);
        ORBIT_TRACK_PARAM(phFindHandle);

        auto win32_impl_result = g_api_table.WdsCliFindFirstImage(hSession, phFindHandle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliFindNextImage(win32::Windows::Win32::Foundation::HANDLE Handle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(Handle);

        auto win32_impl_result = g_api_table.WdsCliFindNextImage(Handle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetEnumerationFlags(win32::Windows::Win32::Foundation::HANDLE Handle, uint32_t* pdwFlags) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(Handle);
        ORBIT_TRACK_PARAM(pdwFlags);

        auto win32_impl_result = g_api_table.WdsCliGetEnumerationFlags(Handle, pdwFlags);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetImageHandleFromFindHandle(win32::Windows::Win32::Foundation::HANDLE FindHandle, win32::Windows::Win32::Foundation::HANDLE* phImageHandle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(FindHandle);
        ORBIT_TRACK_PARAM(phImageHandle);

        auto win32_impl_result = g_api_table.WdsCliGetImageHandleFromFindHandle(FindHandle, phImageHandle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetImageHandleFromTransferHandle(win32::Windows::Win32::Foundation::HANDLE hTransfer, win32::Windows::Win32::Foundation::HANDLE* phImageHandle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hTransfer);
        ORBIT_TRACK_PARAM(phImageHandle);

        auto win32_impl_result = g_api_table.WdsCliGetImageHandleFromTransferHandle(hTransfer, phImageHandle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliCreateSession(win32::Windows::Win32::Foundation::PWSTR pwszServer, win32::Windows::Win32::System::DeploymentServices::WDS_CLI_CRED* pCred, win32::Windows::Win32::Foundation::HANDLE* phSession) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pwszServer);
        ORBIT_TRACK_PARAM(pCred);
        ORBIT_TRACK_PARAM(phSession);

        auto win32_impl_result = g_api_table.WdsCliCreateSession(pwszServer, pCred, phSession);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliAuthorizeSession(win32::Windows::Win32::Foundation::HANDLE hSession, win32::Windows::Win32::System::DeploymentServices::WDS_CLI_CRED* pCred) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hSession);
        ORBIT_TRACK_PARAM(pCred);

        auto win32_impl_result = g_api_table.WdsCliAuthorizeSession(hSession, pCred);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliInitializeLog(win32::Windows::Win32::Foundation::HANDLE hSession, win32::Windows::Win32::System::DeploymentServices::CPU_ARCHITECTURE ulClientArchitecture, win32::Windows::Win32::Foundation::PWSTR pwszClientId, win32::Windows::Win32::Foundation::PWSTR pwszClientAddress) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hSession);
        ORBIT_TRACK_PARAM(ulClientArchitecture);
        ORBIT_TRACK_PARAM(pwszClientId);
        ORBIT_TRACK_PARAM(pwszClientAddress);

        auto win32_impl_result = g_api_table.WdsCliInitializeLog(hSession, ulClientArchitecture, pwszClientId, pwszClientAddress);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliLog(win32::Windows::Win32::Foundation::HANDLE hSession, uint32_t ulLogLevel, uint32_t ulMessageCode) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hSession);
        ORBIT_TRACK_PARAM(ulLogLevel);
        ORBIT_TRACK_PARAM(ulMessageCode);

        auto win32_impl_result = g_api_table.WdsCliLog(hSession, ulLogLevel, ulMessageCode);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetImageName(win32::Windows::Win32::Foundation::HANDLE hIfh, win32::Windows::Win32::Foundation::PWSTR* ppwszValue) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hIfh);
        ORBIT_TRACK_PARAM(ppwszValue);

        auto win32_impl_result = g_api_table.WdsCliGetImageName(hIfh, ppwszValue);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetImageDescription(win32::Windows::Win32::Foundation::HANDLE hIfh, win32::Windows::Win32::Foundation::PWSTR* ppwszValue) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hIfh);
        ORBIT_TRACK_PARAM(ppwszValue);

        auto win32_impl_result = g_api_table.WdsCliGetImageDescription(hIfh, ppwszValue);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetImageType(win32::Windows::Win32::Foundation::HANDLE hIfh, win32::Windows::Win32::System::DeploymentServices::WDS_CLI_IMAGE_TYPE* pImageType) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hIfh);
        ORBIT_TRACK_PARAM(pImageType);

        auto win32_impl_result = g_api_table.WdsCliGetImageType(hIfh, pImageType);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetImageFiles(win32::Windows::Win32::Foundation::HANDLE hIfh, win32::Windows::Win32::Foundation::PWSTR** pppwszFiles, uint32_t* pdwCount) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hIfh);
        ORBIT_TRACK_PARAM(pppwszFiles);
        ORBIT_TRACK_PARAM(pdwCount);

        auto win32_impl_result = g_api_table.WdsCliGetImageFiles(hIfh, pppwszFiles, pdwCount);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetImageLanguage(win32::Windows::Win32::Foundation::HANDLE hIfh, win32::Windows::Win32::Foundation::PWSTR* ppwszValue) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hIfh);
        ORBIT_TRACK_PARAM(ppwszValue);

        auto win32_impl_result = g_api_table.WdsCliGetImageLanguage(hIfh, ppwszValue);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetImageLanguages(win32::Windows::Win32::Foundation::HANDLE hIfh, int8_t*** pppszValues, uint32_t* pdwNumValues) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hIfh);
        ORBIT_TRACK_PARAM(pppszValues);
        ORBIT_TRACK_PARAM(pdwNumValues);

        auto win32_impl_result = g_api_table.WdsCliGetImageLanguages(hIfh, pppszValues, pdwNumValues);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetImageVersion(win32::Windows::Win32::Foundation::HANDLE hIfh, win32::Windows::Win32::Foundation::PWSTR* ppwszValue) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hIfh);
        ORBIT_TRACK_PARAM(ppwszValue);

        auto win32_impl_result = g_api_table.WdsCliGetImageVersion(hIfh, ppwszValue);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetImagePath(win32::Windows::Win32::Foundation::HANDLE hIfh, win32::Windows::Win32::Foundation::PWSTR* ppwszValue) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hIfh);
        ORBIT_TRACK_PARAM(ppwszValue);

        auto win32_impl_result = g_api_table.WdsCliGetImagePath(hIfh, ppwszValue);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetImageIndex(win32::Windows::Win32::Foundation::HANDLE hIfh, uint32_t* pdwValue) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hIfh);
        ORBIT_TRACK_PARAM(pdwValue);

        auto win32_impl_result = g_api_table.WdsCliGetImageIndex(hIfh, pdwValue);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetImageArchitecture(win32::Windows::Win32::Foundation::HANDLE hIfh, win32::Windows::Win32::System::DeploymentServices::CPU_ARCHITECTURE* pdwValue) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hIfh);
        ORBIT_TRACK_PARAM(pdwValue);

        auto win32_impl_result = g_api_table.WdsCliGetImageArchitecture(hIfh, pdwValue);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetImageLastModifiedTime(win32::Windows::Win32::Foundation::HANDLE hIfh, win32::Windows::Win32::Foundation::SYSTEMTIME** ppSysTimeValue) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hIfh);
        ORBIT_TRACK_PARAM(ppSysTimeValue);

        auto win32_impl_result = g_api_table.WdsCliGetImageLastModifiedTime(hIfh, ppSysTimeValue);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetImageSize(win32::Windows::Win32::Foundation::HANDLE hIfh, uint64_t* pullValue) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hIfh);
        ORBIT_TRACK_PARAM(pullValue);

        auto win32_impl_result = g_api_table.WdsCliGetImageSize(hIfh, pullValue);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetImageHalName(win32::Windows::Win32::Foundation::HANDLE hIfh, win32::Windows::Win32::Foundation::PWSTR* ppwszValue) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hIfh);
        ORBIT_TRACK_PARAM(ppwszValue);

        auto win32_impl_result = g_api_table.WdsCliGetImageHalName(hIfh, ppwszValue);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetImageGroup(win32::Windows::Win32::Foundation::HANDLE hIfh, win32::Windows::Win32::Foundation::PWSTR* ppwszValue) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hIfh);
        ORBIT_TRACK_PARAM(ppwszValue);

        auto win32_impl_result = g_api_table.WdsCliGetImageGroup(hIfh, ppwszValue);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetImageNamespace(win32::Windows::Win32::Foundation::HANDLE hIfh, win32::Windows::Win32::Foundation::PWSTR* ppwszValue) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hIfh);
        ORBIT_TRACK_PARAM(ppwszValue);

        auto win32_impl_result = g_api_table.WdsCliGetImageNamespace(hIfh, ppwszValue);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetImageParameter(win32::Windows::Win32::Foundation::HANDLE hIfh, win32::Windows::Win32::System::DeploymentServices::WDS_CLI_IMAGE_PARAM_TYPE ParamType, void* pResponse, uint32_t uResponseLen) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hIfh);
        ORBIT_TRACK_PARAM(ParamType);
        ORBIT_TRACK_PARAM(pResponse);
        ORBIT_TRACK_PARAM(uResponseLen);

        auto win32_impl_result = g_api_table.WdsCliGetImageParameter(hIfh, ParamType, pResponse, uResponseLen);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetTransferSize(win32::Windows::Win32::Foundation::HANDLE hIfh, uint64_t* pullValue) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hIfh);
        ORBIT_TRACK_PARAM(pullValue);

        auto win32_impl_result = g_api_table.WdsCliGetTransferSize(hIfh, pullValue);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    void __stdcall ORBIT_IMPL_WdsCliSetTransferBufferSize(uint32_t ulSizeInBytes) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(ulSizeInBytes);

        g_api_table.WdsCliSetTransferBufferSize(ulSizeInBytes);
        
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliTransferImage(win32::Windows::Win32::Foundation::HANDLE hImage, win32::Windows::Win32::Foundation::PWSTR pwszLocalPath, uint32_t dwFlags, uint32_t dwReserved, win32::Windows::Win32::System::DeploymentServices::PFN_WdsCliCallback* pfnWdsCliCallback, void* pvUserData, win32::Windows::Win32::Foundation::HANDLE* phTransfer) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hImage);
        ORBIT_TRACK_PARAM(pwszLocalPath);
        ORBIT_TRACK_PARAM(dwFlags);
        ORBIT_TRACK_PARAM(dwReserved);
        ORBIT_TRACK_PARAM(pfnWdsCliCallback);
        ORBIT_TRACK_PARAM(pvUserData);
        ORBIT_TRACK_PARAM(phTransfer);

        auto win32_impl_result = g_api_table.WdsCliTransferImage(hImage, pwszLocalPath, dwFlags, dwReserved, pfnWdsCliCallback, pvUserData, phTransfer);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliTransferFile(win32::Windows::Win32::Foundation::PWSTR pwszServer, win32::Windows::Win32::Foundation::PWSTR pwszNamespace, win32::Windows::Win32::Foundation::PWSTR pwszRemoteFilePath, win32::Windows::Win32::Foundation::PWSTR pwszLocalFilePath, uint32_t dwFlags, uint32_t dwReserved, win32::Windows::Win32::System::DeploymentServices::PFN_WdsCliCallback* pfnWdsCliCallback, void* pvUserData, win32::Windows::Win32::Foundation::HANDLE* phTransfer) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pwszServer);
        ORBIT_TRACK_PARAM(pwszNamespace);
        ORBIT_TRACK_PARAM(pwszRemoteFilePath);
        ORBIT_TRACK_PARAM(pwszLocalFilePath);
        ORBIT_TRACK_PARAM(dwFlags);
        ORBIT_TRACK_PARAM(dwReserved);
        ORBIT_TRACK_PARAM(pfnWdsCliCallback);
        ORBIT_TRACK_PARAM(pvUserData);
        ORBIT_TRACK_PARAM(phTransfer);

        auto win32_impl_result = g_api_table.WdsCliTransferFile(pwszServer, pwszNamespace, pwszRemoteFilePath, pwszLocalFilePath, dwFlags, dwReserved, pfnWdsCliCallback, pvUserData, phTransfer);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliCancelTransfer(win32::Windows::Win32::Foundation::HANDLE hTransfer) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hTransfer);

        auto win32_impl_result = g_api_table.WdsCliCancelTransfer(hTransfer);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliWaitForTransfer(win32::Windows::Win32::Foundation::HANDLE hTransfer) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hTransfer);

        auto win32_impl_result = g_api_table.WdsCliWaitForTransfer(hTransfer);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliObtainDriverPackages(win32::Windows::Win32::Foundation::HANDLE hImage, win32::Windows::Win32::Foundation::PWSTR* ppwszServerName, win32::Windows::Win32::Foundation::PWSTR** pppwszDriverPackages, uint32_t* pulCount) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hImage);
        ORBIT_TRACK_PARAM(ppwszServerName);
        ORBIT_TRACK_PARAM(pppwszDriverPackages);
        ORBIT_TRACK_PARAM(pulCount);

        auto win32_impl_result = g_api_table.WdsCliObtainDriverPackages(hImage, ppwszServerName, pppwszDriverPackages, pulCount);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliObtainDriverPackagesEx(win32::Windows::Win32::Foundation::HANDLE hSession, win32::Windows::Win32::Foundation::PWSTR pwszMachineInfo, win32::Windows::Win32::Foundation::PWSTR* ppwszServerName, win32::Windows::Win32::Foundation::PWSTR** pppwszDriverPackages, uint32_t* pulCount) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hSession);
        ORBIT_TRACK_PARAM(pwszMachineInfo);
        ORBIT_TRACK_PARAM(ppwszServerName);
        ORBIT_TRACK_PARAM(pppwszDriverPackages);
        ORBIT_TRACK_PARAM(pulCount);

        auto win32_impl_result = g_api_table.WdsCliObtainDriverPackagesEx(hSession, pwszMachineInfo, ppwszServerName, pppwszDriverPackages, pulCount);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsCliGetDriverQueryXml(win32::Windows::Win32::Foundation::PWSTR pwszWinDirPath, win32::Windows::Win32::Foundation::PWSTR* ppwszDriverQuery) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pwszWinDirPath);
        ORBIT_TRACK_PARAM(ppwszDriverQuery);

        auto win32_impl_result = g_api_table.WdsCliGetDriverQueryXml(pwszWinDirPath, ppwszDriverQuery);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeProviderRegister(win32::Windows::Win32::Foundation::PWSTR pszProviderName, win32::Windows::Win32::Foundation::PWSTR pszModulePath, uint32_t Index, win32::Windows::Win32::Foundation::BOOL bIsCritical, win32::Windows::Win32::System::Registry::HKEY* phProviderKey) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pszProviderName);
        ORBIT_TRACK_PARAM(pszModulePath);
        ORBIT_TRACK_PARAM(Index);
        ORBIT_TRACK_PARAM(bIsCritical);
        ORBIT_TRACK_PARAM(phProviderKey);

        auto win32_impl_result = g_api_table.PxeProviderRegister(pszProviderName, pszModulePath, Index, bIsCritical, phProviderKey);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeProviderUnRegister(win32::Windows::Win32::Foundation::PWSTR pszProviderName) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pszProviderName);

        auto win32_impl_result = g_api_table.PxeProviderUnRegister(pszProviderName);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeProviderQueryIndex(win32::Windows::Win32::Foundation::PWSTR pszProviderName, uint32_t* puIndex) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pszProviderName);
        ORBIT_TRACK_PARAM(puIndex);

        auto win32_impl_result = g_api_table.PxeProviderQueryIndex(pszProviderName, puIndex);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeProviderEnumFirst(win32::Windows::Win32::Foundation::HANDLE* phEnum) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(phEnum);

        auto win32_impl_result = g_api_table.PxeProviderEnumFirst(phEnum);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeProviderEnumNext(win32::Windows::Win32::Foundation::HANDLE hEnum, win32::Windows::Win32::System::DeploymentServices::PXE_PROVIDER** ppProvider) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hEnum);
        ORBIT_TRACK_PARAM(ppProvider);

        auto win32_impl_result = g_api_table.PxeProviderEnumNext(hEnum, ppProvider);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeProviderEnumClose(win32::Windows::Win32::Foundation::HANDLE hEnum) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hEnum);

        auto win32_impl_result = g_api_table.PxeProviderEnumClose(hEnum);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeProviderFreeInfo(win32::Windows::Win32::System::DeploymentServices::PXE_PROVIDER* pProvider) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pProvider);

        auto win32_impl_result = g_api_table.PxeProviderFreeInfo(pProvider);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeRegisterCallback(win32::Windows::Win32::Foundation::HANDLE hProvider, uint32_t CallbackType, void* pCallbackFunction, void* pContext) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hProvider);
        ORBIT_TRACK_PARAM(CallbackType);
        ORBIT_TRACK_PARAM(pCallbackFunction);
        ORBIT_TRACK_PARAM(pContext);

        auto win32_impl_result = g_api_table.PxeRegisterCallback(hProvider, CallbackType, pCallbackFunction, pContext);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeSendReply(win32::Windows::Win32::Foundation::HANDLE hClientRequest, void* pPacket, uint32_t uPacketLen, win32::Windows::Win32::System::DeploymentServices::PXE_ADDRESS* pAddress) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hClientRequest);
        ORBIT_TRACK_PARAM(pPacket);
        ORBIT_TRACK_PARAM(uPacketLen);
        ORBIT_TRACK_PARAM(pAddress);

        auto win32_impl_result = g_api_table.PxeSendReply(hClientRequest, pPacket, uPacketLen, pAddress);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeAsyncRecvDone(win32::Windows::Win32::Foundation::HANDLE hClientRequest, uint32_t Action) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hClientRequest);
        ORBIT_TRACK_PARAM(Action);

        auto win32_impl_result = g_api_table.PxeAsyncRecvDone(hClientRequest, Action);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeTrace(win32::Windows::Win32::Foundation::HANDLE hProvider, uint32_t Severity, win32::Windows::Win32::Foundation::PWSTR pszFormat) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hProvider);
        ORBIT_TRACK_PARAM(Severity);
        ORBIT_TRACK_PARAM(pszFormat);

        auto win32_impl_result = g_api_table.PxeTrace(hProvider, Severity, pszFormat);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeTraceV(win32::Windows::Win32::Foundation::HANDLE hProvider, uint32_t Severity, win32::Windows::Win32::Foundation::PWSTR pszFormat, int8_t* Params) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hProvider);
        ORBIT_TRACK_PARAM(Severity);
        ORBIT_TRACK_PARAM(pszFormat);
        ORBIT_TRACK_PARAM(Params);

        auto win32_impl_result = g_api_table.PxeTraceV(hProvider, Severity, pszFormat, Params);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    void* __stdcall ORBIT_IMPL_PxePacketAllocate(win32::Windows::Win32::Foundation::HANDLE hProvider, win32::Windows::Win32::Foundation::HANDLE hClientRequest, uint32_t uSize) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hProvider);
        ORBIT_TRACK_PARAM(hClientRequest);
        ORBIT_TRACK_PARAM(uSize);

        auto win32_impl_result = g_api_table.PxePacketAllocate(hProvider, hClientRequest, uSize);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxePacketFree(win32::Windows::Win32::Foundation::HANDLE hProvider, win32::Windows::Win32::Foundation::HANDLE hClientRequest, void* pPacket) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hProvider);
        ORBIT_TRACK_PARAM(hClientRequest);
        ORBIT_TRACK_PARAM(pPacket);

        auto win32_impl_result = g_api_table.PxePacketFree(hProvider, hClientRequest, pPacket);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeProviderSetAttribute(win32::Windows::Win32::Foundation::HANDLE hProvider, uint32_t Attribute, void* pParameterBuffer, uint32_t uParamLen) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hProvider);
        ORBIT_TRACK_PARAM(Attribute);
        ORBIT_TRACK_PARAM(pParameterBuffer);
        ORBIT_TRACK_PARAM(uParamLen);

        auto win32_impl_result = g_api_table.PxeProviderSetAttribute(hProvider, Attribute, pParameterBuffer, uParamLen);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeDhcpInitialize(void* pRecvPacket, uint32_t uRecvPacketLen, void* pReplyPacket, uint32_t uMaxReplyPacketLen, uint32_t* puReplyPacketLen) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pRecvPacket);
        ORBIT_TRACK_PARAM(uRecvPacketLen);
        ORBIT_TRACK_PARAM(pReplyPacket);
        ORBIT_TRACK_PARAM(uMaxReplyPacketLen);
        ORBIT_TRACK_PARAM(puReplyPacketLen);

        auto win32_impl_result = g_api_table.PxeDhcpInitialize(pRecvPacket, uRecvPacketLen, pReplyPacket, uMaxReplyPacketLen, puReplyPacketLen);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeDhcpv6Initialize(void* pRequest, uint32_t cbRequest, void* pReply, uint32_t cbReply, uint32_t* pcbReplyUsed) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pRequest);
        ORBIT_TRACK_PARAM(cbRequest);
        ORBIT_TRACK_PARAM(pReply);
        ORBIT_TRACK_PARAM(cbReply);
        ORBIT_TRACK_PARAM(pcbReplyUsed);

        auto win32_impl_result = g_api_table.PxeDhcpv6Initialize(pRequest, cbRequest, pReply, cbReply, pcbReplyUsed);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeDhcpAppendOption(void* pReplyPacket, uint32_t uMaxReplyPacketLen, uint32_t* puReplyPacketLen, uint8_t bOption, uint8_t bOptionLen, void* pValue) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pReplyPacket);
        ORBIT_TRACK_PARAM(uMaxReplyPacketLen);
        ORBIT_TRACK_PARAM(puReplyPacketLen);
        ORBIT_TRACK_PARAM(bOption);
        ORBIT_TRACK_PARAM(bOptionLen);
        ORBIT_TRACK_PARAM(pValue);

        auto win32_impl_result = g_api_table.PxeDhcpAppendOption(pReplyPacket, uMaxReplyPacketLen, puReplyPacketLen, bOption, bOptionLen, pValue);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeDhcpv6AppendOption(void* pReply, uint32_t cbReply, uint32_t* pcbReplyUsed, uint16_t wOptionType, uint16_t cbOption, void* pOption) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pReply);
        ORBIT_TRACK_PARAM(cbReply);
        ORBIT_TRACK_PARAM(pcbReplyUsed);
        ORBIT_TRACK_PARAM(wOptionType);
        ORBIT_TRACK_PARAM(cbOption);
        ORBIT_TRACK_PARAM(pOption);

        auto win32_impl_result = g_api_table.PxeDhcpv6AppendOption(pReply, cbReply, pcbReplyUsed, wOptionType, cbOption, pOption);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeDhcpAppendOptionRaw(void* pReplyPacket, uint32_t uMaxReplyPacketLen, uint32_t* puReplyPacketLen, uint16_t uBufferLen, void* pBuffer) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pReplyPacket);
        ORBIT_TRACK_PARAM(uMaxReplyPacketLen);
        ORBIT_TRACK_PARAM(puReplyPacketLen);
        ORBIT_TRACK_PARAM(uBufferLen);
        ORBIT_TRACK_PARAM(pBuffer);

        auto win32_impl_result = g_api_table.PxeDhcpAppendOptionRaw(pReplyPacket, uMaxReplyPacketLen, puReplyPacketLen, uBufferLen, pBuffer);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeDhcpv6AppendOptionRaw(void* pReply, uint32_t cbReply, uint32_t* pcbReplyUsed, uint16_t cbBuffer, void* pBuffer) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pReply);
        ORBIT_TRACK_PARAM(cbReply);
        ORBIT_TRACK_PARAM(pcbReplyUsed);
        ORBIT_TRACK_PARAM(cbBuffer);
        ORBIT_TRACK_PARAM(pBuffer);

        auto win32_impl_result = g_api_table.PxeDhcpv6AppendOptionRaw(pReply, cbReply, pcbReplyUsed, cbBuffer, pBuffer);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeDhcpIsValid(void* pPacket, uint32_t uPacketLen, win32::Windows::Win32::Foundation::BOOL bRequestPacket, win32::Windows::Win32::Foundation::BOOL* pbPxeOptionPresent) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pPacket);
        ORBIT_TRACK_PARAM(uPacketLen);
        ORBIT_TRACK_PARAM(bRequestPacket);
        ORBIT_TRACK_PARAM(pbPxeOptionPresent);

        auto win32_impl_result = g_api_table.PxeDhcpIsValid(pPacket, uPacketLen, bRequestPacket, pbPxeOptionPresent);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeDhcpv6IsValid(void* pPacket, uint32_t uPacketLen, win32::Windows::Win32::Foundation::BOOL bRequestPacket, win32::Windows::Win32::Foundation::BOOL* pbPxeOptionPresent) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pPacket);
        ORBIT_TRACK_PARAM(uPacketLen);
        ORBIT_TRACK_PARAM(bRequestPacket);
        ORBIT_TRACK_PARAM(pbPxeOptionPresent);

        auto win32_impl_result = g_api_table.PxeDhcpv6IsValid(pPacket, uPacketLen, bRequestPacket, pbPxeOptionPresent);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeDhcpGetOptionValue(void* pPacket, uint32_t uPacketLen, uint32_t uInstance, uint8_t bOption, uint8_t* pbOptionLen, void** ppOptionValue) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pPacket);
        ORBIT_TRACK_PARAM(uPacketLen);
        ORBIT_TRACK_PARAM(uInstance);
        ORBIT_TRACK_PARAM(bOption);
        ORBIT_TRACK_PARAM(pbOptionLen);
        ORBIT_TRACK_PARAM(ppOptionValue);

        auto win32_impl_result = g_api_table.PxeDhcpGetOptionValue(pPacket, uPacketLen, uInstance, bOption, pbOptionLen, ppOptionValue);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeDhcpv6GetOptionValue(void* pPacket, uint32_t uPacketLen, uint32_t uInstance, uint16_t wOption, uint16_t* pwOptionLen, void** ppOptionValue) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pPacket);
        ORBIT_TRACK_PARAM(uPacketLen);
        ORBIT_TRACK_PARAM(uInstance);
        ORBIT_TRACK_PARAM(wOption);
        ORBIT_TRACK_PARAM(pwOptionLen);
        ORBIT_TRACK_PARAM(ppOptionValue);

        auto win32_impl_result = g_api_table.PxeDhcpv6GetOptionValue(pPacket, uPacketLen, uInstance, wOption, pwOptionLen, ppOptionValue);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeDhcpGetVendorOptionValue(void* pPacket, uint32_t uPacketLen, uint8_t bOption, uint32_t uInstance, uint8_t* pbOptionLen, void** ppOptionValue) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pPacket);
        ORBIT_TRACK_PARAM(uPacketLen);
        ORBIT_TRACK_PARAM(bOption);
        ORBIT_TRACK_PARAM(uInstance);
        ORBIT_TRACK_PARAM(pbOptionLen);
        ORBIT_TRACK_PARAM(ppOptionValue);

        auto win32_impl_result = g_api_table.PxeDhcpGetVendorOptionValue(pPacket, uPacketLen, bOption, uInstance, pbOptionLen, ppOptionValue);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeDhcpv6GetVendorOptionValue(void* pPacket, uint32_t uPacketLen, uint32_t dwEnterpriseNumber, uint16_t wOption, uint32_t uInstance, uint16_t* pwOptionLen, void** ppOptionValue) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pPacket);
        ORBIT_TRACK_PARAM(uPacketLen);
        ORBIT_TRACK_PARAM(dwEnterpriseNumber);
        ORBIT_TRACK_PARAM(wOption);
        ORBIT_TRACK_PARAM(uInstance);
        ORBIT_TRACK_PARAM(pwOptionLen);
        ORBIT_TRACK_PARAM(ppOptionValue);

        auto win32_impl_result = g_api_table.PxeDhcpv6GetVendorOptionValue(pPacket, uPacketLen, dwEnterpriseNumber, wOption, uInstance, pwOptionLen, ppOptionValue);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeDhcpv6ParseRelayForw(void* pRelayForwPacket, uint32_t uRelayForwPacketLen, win32::Windows::Win32::System::DeploymentServices::PXE_DHCPV6_NESTED_RELAY_MESSAGE* pRelayMessages, uint32_t nRelayMessages, uint32_t* pnRelayMessages, uint8_t** ppInnerPacket, uint32_t* pcbInnerPacket) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pRelayForwPacket);
        ORBIT_TRACK_PARAM(uRelayForwPacketLen);
        ORBIT_TRACK_PARAM(pRelayMessages);
        ORBIT_TRACK_PARAM(nRelayMessages);
        ORBIT_TRACK_PARAM(pnRelayMessages);
        ORBIT_TRACK_PARAM(ppInnerPacket);
        ORBIT_TRACK_PARAM(pcbInnerPacket);

        auto win32_impl_result = g_api_table.PxeDhcpv6ParseRelayForw(pRelayForwPacket, uRelayForwPacketLen, pRelayMessages, nRelayMessages, pnRelayMessages, ppInnerPacket, pcbInnerPacket);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeDhcpv6CreateRelayRepl(win32::Windows::Win32::System::DeploymentServices::PXE_DHCPV6_NESTED_RELAY_MESSAGE* pRelayMessages, uint32_t nRelayMessages, uint8_t* pInnerPacket, uint32_t cbInnerPacket, void* pReplyBuffer, uint32_t cbReplyBuffer, uint32_t* pcbReplyBuffer) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pRelayMessages);
        ORBIT_TRACK_PARAM(nRelayMessages);
        ORBIT_TRACK_PARAM(pInnerPacket);
        ORBIT_TRACK_PARAM(cbInnerPacket);
        ORBIT_TRACK_PARAM(pReplyBuffer);
        ORBIT_TRACK_PARAM(cbReplyBuffer);
        ORBIT_TRACK_PARAM(pcbReplyBuffer);

        auto win32_impl_result = g_api_table.PxeDhcpv6CreateRelayRepl(pRelayMessages, nRelayMessages, pInnerPacket, cbInnerPacket, pReplyBuffer, cbReplyBuffer, pcbReplyBuffer);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeGetServerInfo(uint32_t uInfoType, void* pBuffer, uint32_t uBufferLen) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(uInfoType);
        ORBIT_TRACK_PARAM(pBuffer);
        ORBIT_TRACK_PARAM(uBufferLen);

        auto win32_impl_result = g_api_table.PxeGetServerInfo(uInfoType, pBuffer, uBufferLen);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_PxeGetServerInfoEx(uint32_t uInfoType, void* pBuffer, uint32_t uBufferLen, uint32_t* puBufferUsed) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(uInfoType);
        ORBIT_TRACK_PARAM(pBuffer);
        ORBIT_TRACK_PARAM(uBufferLen);
        ORBIT_TRACK_PARAM(puBufferUsed);

        auto win32_impl_result = g_api_table.PxeGetServerInfoEx(uInfoType, pBuffer, uBufferLen, puBufferUsed);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsTransportServerRegisterCallback(win32::Windows::Win32::Foundation::HANDLE hProvider, win32::Windows::Win32::System::DeploymentServices::TRANSPORTPROVIDER_CALLBACK_ID CallbackId, void* pfnCallback) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hProvider);
        ORBIT_TRACK_PARAM(CallbackId);
        ORBIT_TRACK_PARAM(pfnCallback);

        auto win32_impl_result = g_api_table.WdsTransportServerRegisterCallback(hProvider, CallbackId, pfnCallback);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsTransportServerCompleteRead(win32::Windows::Win32::Foundation::HANDLE hProvider, uint32_t ulBytesRead, void* pvUserData, win32::Windows::Win32::Foundation::HRESULT hReadResult) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hProvider);
        ORBIT_TRACK_PARAM(ulBytesRead);
        ORBIT_TRACK_PARAM(pvUserData);
        ORBIT_TRACK_PARAM(hReadResult);

        auto win32_impl_result = g_api_table.WdsTransportServerCompleteRead(hProvider, ulBytesRead, pvUserData, hReadResult);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsTransportServerTrace(win32::Windows::Win32::Foundation::HANDLE hProvider, uint32_t Severity, win32::Windows::Win32::Foundation::PWSTR pwszFormat) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hProvider);
        ORBIT_TRACK_PARAM(Severity);
        ORBIT_TRACK_PARAM(pwszFormat);

        auto win32_impl_result = g_api_table.WdsTransportServerTrace(hProvider, Severity, pwszFormat);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsTransportServerTraceV(win32::Windows::Win32::Foundation::HANDLE hProvider, uint32_t Severity, win32::Windows::Win32::Foundation::PWSTR pwszFormat, int8_t* Params) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hProvider);
        ORBIT_TRACK_PARAM(Severity);
        ORBIT_TRACK_PARAM(pwszFormat);
        ORBIT_TRACK_PARAM(Params);

        auto win32_impl_result = g_api_table.WdsTransportServerTraceV(hProvider, Severity, pwszFormat, Params);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    void* __stdcall ORBIT_IMPL_WdsTransportServerAllocateBuffer(win32::Windows::Win32::Foundation::HANDLE hProvider, uint32_t ulBufferSize) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hProvider);
        ORBIT_TRACK_PARAM(ulBufferSize);

        auto win32_impl_result = g_api_table.WdsTransportServerAllocateBuffer(hProvider, ulBufferSize);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_WdsTransportServerFreeBuffer(win32::Windows::Win32::Foundation::HANDLE hProvider, void* pvBuffer) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hProvider);
        ORBIT_TRACK_PARAM(pvBuffer);

        auto win32_impl_result = g_api_table.WdsTransportServerFreeBuffer(hProvider, pvBuffer);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_WdsTransportClientInitialize() noexcept
    {
        ORBIT_SCOPE_FUNCTION();

        auto win32_impl_result = g_api_table.WdsTransportClientInitialize();
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_WdsTransportClientInitializeSession(win32::Windows::Win32::System::DeploymentServices::WDS_TRANSPORTCLIENT_REQUEST* pSessionRequest, void* pCallerData, win32::Windows::Win32::Foundation::HANDLE* hSessionKey) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pSessionRequest);
        ORBIT_TRACK_PARAM(pCallerData);
        ORBIT_TRACK_PARAM(hSessionKey);

        auto win32_impl_result = g_api_table.WdsTransportClientInitializeSession(pSessionRequest, pCallerData, hSessionKey);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_WdsTransportClientRegisterCallback(win32::Windows::Win32::Foundation::HANDLE hSessionKey, win32::Windows::Win32::System::DeploymentServices::TRANSPORTCLIENT_CALLBACK_ID CallbackId, void* pfnCallback) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hSessionKey);
        ORBIT_TRACK_PARAM(CallbackId);
        ORBIT_TRACK_PARAM(pfnCallback);

        auto win32_impl_result = g_api_table.WdsTransportClientRegisterCallback(hSessionKey, CallbackId, pfnCallback);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_WdsTransportClientStartSession(win32::Windows::Win32::Foundation::HANDLE hSessionKey) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hSessionKey);

        auto win32_impl_result = g_api_table.WdsTransportClientStartSession(hSessionKey);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_WdsTransportClientCompleteReceive(win32::Windows::Win32::Foundation::HANDLE hSessionKey, uint32_t ulSize, win32::Windows::Win32::Foundation::ULARGE_INTEGER* pullOffset) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hSessionKey);
        ORBIT_TRACK_PARAM(ulSize);
        ORBIT_TRACK_PARAM(pullOffset);

        auto win32_impl_result = g_api_table.WdsTransportClientCompleteReceive(hSessionKey, ulSize, pullOffset);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_WdsTransportClientCancelSession(win32::Windows::Win32::Foundation::HANDLE hSessionKey) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hSessionKey);

        auto win32_impl_result = g_api_table.WdsTransportClientCancelSession(hSessionKey);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_WdsTransportClientCancelSessionEx(win32::Windows::Win32::Foundation::HANDLE hSessionKey, uint32_t dwErrorCode) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hSessionKey);
        ORBIT_TRACK_PARAM(dwErrorCode);

        auto win32_impl_result = g_api_table.WdsTransportClientCancelSessionEx(hSessionKey, dwErrorCode);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_WdsTransportClientWaitForCompletion(win32::Windows::Win32::Foundation::HANDLE hSessionKey, uint32_t uTimeout) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hSessionKey);
        ORBIT_TRACK_PARAM(uTimeout);

        auto win32_impl_result = g_api_table.WdsTransportClientWaitForCompletion(hSessionKey, uTimeout);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_WdsTransportClientQueryStatus(win32::Windows::Win32::Foundation::HANDLE hSessionKey, uint32_t* puStatus, uint32_t* puErrorCode) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hSessionKey);
        ORBIT_TRACK_PARAM(puStatus);
        ORBIT_TRACK_PARAM(puErrorCode);

        auto win32_impl_result = g_api_table.WdsTransportClientQueryStatus(hSessionKey, puStatus, puErrorCode);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_WdsTransportClientCloseSession(win32::Windows::Win32::Foundation::HANDLE hSessionKey) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hSessionKey);

        auto win32_impl_result = g_api_table.WdsTransportClientCloseSession(hSessionKey);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_WdsTransportClientAddRefBuffer(void* pvBuffer) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pvBuffer);

        auto win32_impl_result = g_api_table.WdsTransportClientAddRefBuffer(pvBuffer);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_WdsTransportClientReleaseBuffer(void* pvBuffer) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pvBuffer);

        auto win32_impl_result = g_api_table.WdsTransportClientReleaseBuffer(pvBuffer);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_WdsTransportClientShutdown() noexcept
    {
        ORBIT_SCOPE_FUNCTION();

        auto win32_impl_result = g_api_table.WdsTransportClientShutdown();
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_WdsBpParseInitialize(void* pPacket, uint32_t uPacketLen, uint8_t* pbPacketType, win32::Windows::Win32::Foundation::HANDLE* phHandle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pPacket);
        ORBIT_TRACK_PARAM(uPacketLen);
        ORBIT_TRACK_PARAM(pbPacketType);
        ORBIT_TRACK_PARAM(phHandle);

        auto win32_impl_result = g_api_table.WdsBpParseInitialize(pPacket, uPacketLen, pbPacketType, phHandle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_WdsBpParseInitializev6(void* pPacket, uint32_t uPacketLen, uint8_t* pbPacketType, win32::Windows::Win32::Foundation::HANDLE* phHandle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pPacket);
        ORBIT_TRACK_PARAM(uPacketLen);
        ORBIT_TRACK_PARAM(pbPacketType);
        ORBIT_TRACK_PARAM(phHandle);

        auto win32_impl_result = g_api_table.WdsBpParseInitializev6(pPacket, uPacketLen, pbPacketType, phHandle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_WdsBpInitialize(uint8_t bPacketType, win32::Windows::Win32::Foundation::HANDLE* phHandle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(bPacketType);
        ORBIT_TRACK_PARAM(phHandle);

        auto win32_impl_result = g_api_table.WdsBpInitialize(bPacketType, phHandle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_WdsBpCloseHandle(win32::Windows::Win32::Foundation::HANDLE hHandle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hHandle);

        auto win32_impl_result = g_api_table.WdsBpCloseHandle(hHandle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_WdsBpQueryOption(win32::Windows::Win32::Foundation::HANDLE hHandle, uint32_t uOption, uint32_t uValueLen, void* pValue, uint32_t* puBytes) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hHandle);
        ORBIT_TRACK_PARAM(uOption);
        ORBIT_TRACK_PARAM(uValueLen);
        ORBIT_TRACK_PARAM(pValue);
        ORBIT_TRACK_PARAM(puBytes);

        auto win32_impl_result = g_api_table.WdsBpQueryOption(hHandle, uOption, uValueLen, pValue, puBytes);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_WdsBpAddOption(win32::Windows::Win32::Foundation::HANDLE hHandle, uint32_t uOption, uint32_t uValueLen, void* pValue) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hHandle);
        ORBIT_TRACK_PARAM(uOption);
        ORBIT_TRACK_PARAM(uValueLen);
        ORBIT_TRACK_PARAM(pValue);

        auto win32_impl_result = g_api_table.WdsBpAddOption(hHandle, uOption, uValueLen, pValue);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_WdsBpGetOptionBuffer(win32::Windows::Win32::Foundation::HANDLE hHandle, uint32_t uBufferLen, void* pBuffer, uint32_t* puBytes) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hHandle);
        ORBIT_TRACK_PARAM(uBufferLen);
        ORBIT_TRACK_PARAM(pBuffer);
        ORBIT_TRACK_PARAM(puBytes);

        auto win32_impl_result = g_api_table.WdsBpGetOptionBuffer(hHandle, uBufferLen, pBuffer, puBytes);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

}

#pragma endregion abi_methods

}
#endif
