// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_System_Diagnostics_Etw_2_H
#define WIN32_Windows_Win32_System_Diagnostics_Etw_2_H
#include "win32/Windows.Win32.System.Diagnostics.Etw.h"
#include "win32/impl/Windows.Win32.System.Diagnostics.Etw.1.h"
WIN32_EXPORT namespace win32::Windows::Win32::System::Diagnostics::Etw
{
ApiTable g_api_table;

#pragma region abi_methods
extern "C"
{
    uint32_t __stdcall ORBIT_IMPL_StartTraceW(uint64_t* TraceHandle, win32::Windows::Win32::Foundation::PWSTR InstanceName, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_TRACE_PROPERTIES* Properties) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(TraceHandle);
        ORBIT_TRACK_PARAM(InstanceName);
        ORBIT_TRACK_PARAM(Properties);

        auto win32_impl_result = g_api_table.StartTraceW(TraceHandle, InstanceName, Properties);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_StartTraceA(uint64_t* TraceHandle, win32::Windows::Win32::Foundation::PSTR InstanceName, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_TRACE_PROPERTIES* Properties) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(TraceHandle);
        ORBIT_TRACK_PARAM(InstanceName);
        ORBIT_TRACK_PARAM(Properties);

        auto win32_impl_result = g_api_table.StartTraceA(TraceHandle, InstanceName, Properties);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_StopTraceW(uint64_t TraceHandle, win32::Windows::Win32::Foundation::PWSTR InstanceName, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_TRACE_PROPERTIES* Properties) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(TraceHandle);
        ORBIT_TRACK_PARAM(InstanceName);
        ORBIT_TRACK_PARAM(Properties);

        auto win32_impl_result = g_api_table.StopTraceW(TraceHandle, InstanceName, Properties);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_StopTraceA(uint64_t TraceHandle, win32::Windows::Win32::Foundation::PSTR InstanceName, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_TRACE_PROPERTIES* Properties) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(TraceHandle);
        ORBIT_TRACK_PARAM(InstanceName);
        ORBIT_TRACK_PARAM(Properties);

        auto win32_impl_result = g_api_table.StopTraceA(TraceHandle, InstanceName, Properties);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_QueryTraceW(uint64_t TraceHandle, win32::Windows::Win32::Foundation::PWSTR InstanceName, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_TRACE_PROPERTIES* Properties) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(TraceHandle);
        ORBIT_TRACK_PARAM(InstanceName);
        ORBIT_TRACK_PARAM(Properties);

        auto win32_impl_result = g_api_table.QueryTraceW(TraceHandle, InstanceName, Properties);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_QueryTraceA(uint64_t TraceHandle, win32::Windows::Win32::Foundation::PSTR InstanceName, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_TRACE_PROPERTIES* Properties) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(TraceHandle);
        ORBIT_TRACK_PARAM(InstanceName);
        ORBIT_TRACK_PARAM(Properties);

        auto win32_impl_result = g_api_table.QueryTraceA(TraceHandle, InstanceName, Properties);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_UpdateTraceW(uint64_t TraceHandle, win32::Windows::Win32::Foundation::PWSTR InstanceName, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_TRACE_PROPERTIES* Properties) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(TraceHandle);
        ORBIT_TRACK_PARAM(InstanceName);
        ORBIT_TRACK_PARAM(Properties);

        auto win32_impl_result = g_api_table.UpdateTraceW(TraceHandle, InstanceName, Properties);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_UpdateTraceA(uint64_t TraceHandle, win32::Windows::Win32::Foundation::PSTR InstanceName, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_TRACE_PROPERTIES* Properties) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(TraceHandle);
        ORBIT_TRACK_PARAM(InstanceName);
        ORBIT_TRACK_PARAM(Properties);

        auto win32_impl_result = g_api_table.UpdateTraceA(TraceHandle, InstanceName, Properties);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_FlushTraceW(uint64_t TraceHandle, win32::Windows::Win32::Foundation::PWSTR InstanceName, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_TRACE_PROPERTIES* Properties) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(TraceHandle);
        ORBIT_TRACK_PARAM(InstanceName);
        ORBIT_TRACK_PARAM(Properties);

        auto win32_impl_result = g_api_table.FlushTraceW(TraceHandle, InstanceName, Properties);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_FlushTraceA(uint64_t TraceHandle, win32::Windows::Win32::Foundation::PSTR InstanceName, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_TRACE_PROPERTIES* Properties) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(TraceHandle);
        ORBIT_TRACK_PARAM(InstanceName);
        ORBIT_TRACK_PARAM(Properties);

        auto win32_impl_result = g_api_table.FlushTraceA(TraceHandle, InstanceName, Properties);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_ControlTraceW(uint64_t TraceHandle, win32::Windows::Win32::Foundation::PWSTR InstanceName, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_TRACE_PROPERTIES* Properties, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_TRACE_CONTROL ControlCode) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(TraceHandle);
        ORBIT_TRACK_PARAM(InstanceName);
        ORBIT_TRACK_PARAM(Properties);
        ORBIT_TRACK_PARAM(ControlCode);

        auto win32_impl_result = g_api_table.ControlTraceW(TraceHandle, InstanceName, Properties, ControlCode);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_ControlTraceA(uint64_t TraceHandle, win32::Windows::Win32::Foundation::PSTR InstanceName, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_TRACE_PROPERTIES* Properties, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_TRACE_CONTROL ControlCode) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(TraceHandle);
        ORBIT_TRACK_PARAM(InstanceName);
        ORBIT_TRACK_PARAM(Properties);
        ORBIT_TRACK_PARAM(ControlCode);

        auto win32_impl_result = g_api_table.ControlTraceA(TraceHandle, InstanceName, Properties, ControlCode);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_QueryAllTracesW(win32::Windows::Win32::System::Diagnostics::Etw::EVENT_TRACE_PROPERTIES** PropertyArray, uint32_t PropertyArrayCount, uint32_t* LoggerCount) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(PropertyArray);
        ORBIT_TRACK_PARAM(PropertyArrayCount);
        ORBIT_TRACK_PARAM(LoggerCount);

        auto win32_impl_result = g_api_table.QueryAllTracesW(PropertyArray, PropertyArrayCount, LoggerCount);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_QueryAllTracesA(win32::Windows::Win32::System::Diagnostics::Etw::EVENT_TRACE_PROPERTIES** PropertyArray, uint32_t PropertyArrayCount, uint32_t* LoggerCount) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(PropertyArray);
        ORBIT_TRACK_PARAM(PropertyArrayCount);
        ORBIT_TRACK_PARAM(LoggerCount);

        auto win32_impl_result = g_api_table.QueryAllTracesA(PropertyArray, PropertyArrayCount, LoggerCount);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_EnableTrace(uint32_t Enable, uint32_t EnableFlag, uint32_t EnableLevel, ::win32::guid* ControlGuid, uint64_t TraceHandle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(Enable);
        ORBIT_TRACK_PARAM(EnableFlag);
        ORBIT_TRACK_PARAM(EnableLevel);
        ORBIT_TRACK_PARAM(ControlGuid);
        ORBIT_TRACK_PARAM(TraceHandle);

        auto win32_impl_result = g_api_table.EnableTrace(Enable, EnableFlag, EnableLevel, ControlGuid, TraceHandle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_EnableTraceEx(::win32::guid* ProviderId, ::win32::guid* SourceId, uint64_t TraceHandle, uint32_t IsEnabled, uint8_t Level, uint64_t MatchAnyKeyword, uint64_t MatchAllKeyword, uint32_t EnableProperty, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_FILTER_DESCRIPTOR* EnableFilterDesc) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(ProviderId);
        ORBIT_TRACK_PARAM(SourceId);
        ORBIT_TRACK_PARAM(TraceHandle);
        ORBIT_TRACK_PARAM(IsEnabled);
        ORBIT_TRACK_PARAM(Level);
        ORBIT_TRACK_PARAM(MatchAnyKeyword);
        ORBIT_TRACK_PARAM(MatchAllKeyword);
        ORBIT_TRACK_PARAM(EnableProperty);
        ORBIT_TRACK_PARAM(EnableFilterDesc);

        auto win32_impl_result = g_api_table.EnableTraceEx(ProviderId, SourceId, TraceHandle, IsEnabled, Level, MatchAnyKeyword, MatchAllKeyword, EnableProperty, EnableFilterDesc);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_EnableTraceEx2(uint64_t TraceHandle, ::win32::guid* ProviderId, uint32_t ControlCode, uint8_t Level, uint64_t MatchAnyKeyword, uint64_t MatchAllKeyword, uint32_t Timeout, win32::Windows::Win32::System::Diagnostics::Etw::ENABLE_TRACE_PARAMETERS* EnableParameters) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(TraceHandle);
        ORBIT_TRACK_PARAM(ProviderId);
        ORBIT_TRACK_PARAM(ControlCode);
        ORBIT_TRACK_PARAM(Level);
        ORBIT_TRACK_PARAM(MatchAnyKeyword);
        ORBIT_TRACK_PARAM(MatchAllKeyword);
        ORBIT_TRACK_PARAM(Timeout);
        ORBIT_TRACK_PARAM(EnableParameters);

        auto win32_impl_result = g_api_table.EnableTraceEx2(TraceHandle, ProviderId, ControlCode, Level, MatchAnyKeyword, MatchAllKeyword, Timeout, EnableParameters);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_EnumerateTraceGuidsEx(win32::Windows::Win32::System::Diagnostics::Etw::TRACE_QUERY_INFO_CLASS TraceQueryInfoClass, void* InBuffer, uint32_t InBufferSize, void* OutBuffer, uint32_t OutBufferSize, uint32_t* ReturnLength) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(TraceQueryInfoClass);
        ORBIT_TRACK_PARAM(InBuffer);
        ORBIT_TRACK_PARAM(InBufferSize);
        ORBIT_TRACK_PARAM(OutBuffer);
        ORBIT_TRACK_PARAM(OutBufferSize);
        ORBIT_TRACK_PARAM(ReturnLength);

        auto win32_impl_result = g_api_table.EnumerateTraceGuidsEx(TraceQueryInfoClass, InBuffer, InBufferSize, OutBuffer, OutBufferSize, ReturnLength);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TraceSetInformation(uint64_t SessionHandle, win32::Windows::Win32::System::Diagnostics::Etw::TRACE_QUERY_INFO_CLASS InformationClass, void* TraceInformation, uint32_t InformationLength) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(SessionHandle);
        ORBIT_TRACK_PARAM(InformationClass);
        ORBIT_TRACK_PARAM(TraceInformation);
        ORBIT_TRACK_PARAM(InformationLength);

        auto win32_impl_result = g_api_table.TraceSetInformation(SessionHandle, InformationClass, TraceInformation, InformationLength);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TraceQueryInformation(uint64_t SessionHandle, win32::Windows::Win32::System::Diagnostics::Etw::TRACE_QUERY_INFO_CLASS InformationClass, void* TraceInformation, uint32_t InformationLength, uint32_t* ReturnLength) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(SessionHandle);
        ORBIT_TRACK_PARAM(InformationClass);
        ORBIT_TRACK_PARAM(TraceInformation);
        ORBIT_TRACK_PARAM(InformationLength);
        ORBIT_TRACK_PARAM(ReturnLength);

        auto win32_impl_result = g_api_table.TraceQueryInformation(SessionHandle, InformationClass, TraceInformation, InformationLength, ReturnLength);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_CreateTraceInstanceId(win32::Windows::Win32::Foundation::HANDLE RegHandle, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_INSTANCE_INFO* InstInfo) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(RegHandle);
        ORBIT_TRACK_PARAM(InstInfo);

        auto win32_impl_result = g_api_table.CreateTraceInstanceId(RegHandle, InstInfo);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TraceEvent(uint64_t TraceHandle, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_TRACE_HEADER* EventTrace) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(TraceHandle);
        ORBIT_TRACK_PARAM(EventTrace);

        auto win32_impl_result = g_api_table.TraceEvent(TraceHandle, EventTrace);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TraceEventInstance(uint64_t TraceHandle, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_INSTANCE_HEADER* EventTrace, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_INSTANCE_INFO* InstInfo, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_INSTANCE_INFO* ParentInstInfo) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(TraceHandle);
        ORBIT_TRACK_PARAM(EventTrace);
        ORBIT_TRACK_PARAM(InstInfo);
        ORBIT_TRACK_PARAM(ParentInstInfo);

        auto win32_impl_result = g_api_table.TraceEventInstance(TraceHandle, EventTrace, InstInfo, ParentInstInfo);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_RegisterTraceGuidsW(win32::Windows::Win32::System::Diagnostics::Etw::WMIDPREQUEST* RequestAddress, void* RequestContext, ::win32::guid* ControlGuid, uint32_t GuidCount, win32::Windows::Win32::System::Diagnostics::Etw::TRACE_GUID_REGISTRATION* TraceGuidReg, win32::Windows::Win32::Foundation::PWSTR MofImagePath, win32::Windows::Win32::Foundation::PWSTR MofResourceName, uint64_t* RegistrationHandle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(RequestAddress);
        ORBIT_TRACK_PARAM(RequestContext);
        ORBIT_TRACK_PARAM(ControlGuid);
        ORBIT_TRACK_PARAM(GuidCount);
        ORBIT_TRACK_PARAM(TraceGuidReg);
        ORBIT_TRACK_PARAM(MofImagePath);
        ORBIT_TRACK_PARAM(MofResourceName);
        ORBIT_TRACK_PARAM(RegistrationHandle);

        auto win32_impl_result = g_api_table.RegisterTraceGuidsW(RequestAddress, RequestContext, ControlGuid, GuidCount, TraceGuidReg, MofImagePath, MofResourceName, RegistrationHandle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_RegisterTraceGuidsA(win32::Windows::Win32::System::Diagnostics::Etw::WMIDPREQUEST* RequestAddress, void* RequestContext, ::win32::guid* ControlGuid, uint32_t GuidCount, win32::Windows::Win32::System::Diagnostics::Etw::TRACE_GUID_REGISTRATION* TraceGuidReg, win32::Windows::Win32::Foundation::PSTR MofImagePath, win32::Windows::Win32::Foundation::PSTR MofResourceName, uint64_t* RegistrationHandle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(RequestAddress);
        ORBIT_TRACK_PARAM(RequestContext);
        ORBIT_TRACK_PARAM(ControlGuid);
        ORBIT_TRACK_PARAM(GuidCount);
        ORBIT_TRACK_PARAM(TraceGuidReg);
        ORBIT_TRACK_PARAM(MofImagePath);
        ORBIT_TRACK_PARAM(MofResourceName);
        ORBIT_TRACK_PARAM(RegistrationHandle);

        auto win32_impl_result = g_api_table.RegisterTraceGuidsA(RequestAddress, RequestContext, ControlGuid, GuidCount, TraceGuidReg, MofImagePath, MofResourceName, RegistrationHandle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_EnumerateTraceGuids(win32::Windows::Win32::System::Diagnostics::Etw::TRACE_GUID_PROPERTIES** GuidPropertiesArray, uint32_t PropertyArrayCount, uint32_t* GuidCount) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(GuidPropertiesArray);
        ORBIT_TRACK_PARAM(PropertyArrayCount);
        ORBIT_TRACK_PARAM(GuidCount);

        auto win32_impl_result = g_api_table.EnumerateTraceGuids(GuidPropertiesArray, PropertyArrayCount, GuidCount);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_UnregisterTraceGuids(uint64_t RegistrationHandle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(RegistrationHandle);

        auto win32_impl_result = g_api_table.UnregisterTraceGuids(RegistrationHandle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint64_t __stdcall ORBIT_IMPL_GetTraceLoggerHandle(void* Buffer) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(Buffer);

        auto win32_impl_result = g_api_table.GetTraceLoggerHandle(Buffer);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint8_t __stdcall ORBIT_IMPL_GetTraceEnableLevel(uint64_t TraceHandle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(TraceHandle);

        auto win32_impl_result = g_api_table.GetTraceEnableLevel(TraceHandle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_GetTraceEnableFlags(uint64_t TraceHandle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(TraceHandle);

        auto win32_impl_result = g_api_table.GetTraceEnableFlags(TraceHandle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint64_t __stdcall ORBIT_IMPL_OpenTraceW(win32::Windows::Win32::System::Diagnostics::Etw::EVENT_TRACE_LOGFILEW* Logfile) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(Logfile);

        auto win32_impl_result = g_api_table.OpenTraceW(Logfile);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_ProcessTrace(uint64_t* HandleArray, uint32_t HandleCount, win32::Windows::Win32::Foundation::FILETIME* StartTime, win32::Windows::Win32::Foundation::FILETIME* EndTime) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(HandleArray);
        ORBIT_TRACK_PARAM(HandleCount);
        ORBIT_TRACK_PARAM(StartTime);
        ORBIT_TRACK_PARAM(EndTime);

        auto win32_impl_result = g_api_table.ProcessTrace(HandleArray, HandleCount, StartTime, EndTime);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_CloseTrace(uint64_t TraceHandle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(TraceHandle);

        auto win32_impl_result = g_api_table.CloseTrace(TraceHandle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_QueryTraceProcessingHandle(uint64_t ProcessingHandle, win32::Windows::Win32::System::Diagnostics::Etw::ETW_PROCESS_HANDLE_INFO_TYPE InformationClass, void* InBuffer, uint32_t InBufferSize, void* OutBuffer, uint32_t OutBufferSize, uint32_t* ReturnLength) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(ProcessingHandle);
        ORBIT_TRACK_PARAM(InformationClass);
        ORBIT_TRACK_PARAM(InBuffer);
        ORBIT_TRACK_PARAM(InBufferSize);
        ORBIT_TRACK_PARAM(OutBuffer);
        ORBIT_TRACK_PARAM(OutBufferSize);
        ORBIT_TRACK_PARAM(ReturnLength);

        auto win32_impl_result = g_api_table.QueryTraceProcessingHandle(ProcessingHandle, InformationClass, InBuffer, InBufferSize, OutBuffer, OutBufferSize, ReturnLength);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint64_t __stdcall ORBIT_IMPL_OpenTraceA(win32::Windows::Win32::System::Diagnostics::Etw::EVENT_TRACE_LOGFILEA* Logfile) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(Logfile);

        auto win32_impl_result = g_api_table.OpenTraceA(Logfile);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_SetTraceCallback(::win32::guid* pGuid, win32::Windows::Win32::System::Diagnostics::Etw::PEVENT_CALLBACK* EventCallback) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pGuid);
        ORBIT_TRACK_PARAM(EventCallback);

        auto win32_impl_result = g_api_table.SetTraceCallback(pGuid, EventCallback);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_RemoveTraceCallback(::win32::guid* pGuid) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pGuid);

        auto win32_impl_result = g_api_table.RemoveTraceCallback(pGuid);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TraceMessage(uint64_t LoggerHandle, win32::Windows::Win32::System::Diagnostics::Etw::TRACE_MESSAGE_FLAGS MessageFlags, ::win32::guid* MessageGuid, uint16_t MessageNumber) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(LoggerHandle);
        ORBIT_TRACK_PARAM(MessageFlags);
        ORBIT_TRACK_PARAM(MessageGuid);
        ORBIT_TRACK_PARAM(MessageNumber);

        auto win32_impl_result = g_api_table.TraceMessage(LoggerHandle, MessageFlags, MessageGuid, MessageNumber);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TraceMessageVa(uint64_t LoggerHandle, win32::Windows::Win32::System::Diagnostics::Etw::TRACE_MESSAGE_FLAGS MessageFlags, ::win32::guid* MessageGuid, uint16_t MessageNumber, int8_t* MessageArgList) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(LoggerHandle);
        ORBIT_TRACK_PARAM(MessageFlags);
        ORBIT_TRACK_PARAM(MessageGuid);
        ORBIT_TRACK_PARAM(MessageNumber);
        ORBIT_TRACK_PARAM(MessageArgList);

        auto win32_impl_result = g_api_table.TraceMessageVa(LoggerHandle, MessageFlags, MessageGuid, MessageNumber, MessageArgList);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_EventRegister(::win32::guid* ProviderId, win32::Windows::Win32::System::Diagnostics::Etw::PENABLECALLBACK* EnableCallback, void* CallbackContext, uint64_t* RegHandle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(ProviderId);
        ORBIT_TRACK_PARAM(EnableCallback);
        ORBIT_TRACK_PARAM(CallbackContext);
        ORBIT_TRACK_PARAM(RegHandle);

        auto win32_impl_result = g_api_table.EventRegister(ProviderId, EnableCallback, CallbackContext, RegHandle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_EventUnregister(uint64_t RegHandle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(RegHandle);

        auto win32_impl_result = g_api_table.EventUnregister(RegHandle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_EventSetInformation(uint64_t RegHandle, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_INFO_CLASS InformationClass, void* EventInformation, uint32_t InformationLength) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(RegHandle);
        ORBIT_TRACK_PARAM(InformationClass);
        ORBIT_TRACK_PARAM(EventInformation);
        ORBIT_TRACK_PARAM(InformationLength);

        auto win32_impl_result = g_api_table.EventSetInformation(RegHandle, InformationClass, EventInformation, InformationLength);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOLEAN __stdcall ORBIT_IMPL_EventEnabled(uint64_t RegHandle, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_DESCRIPTOR* EventDescriptor) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(RegHandle);
        ORBIT_TRACK_PARAM(EventDescriptor);

        auto win32_impl_result = g_api_table.EventEnabled(RegHandle, EventDescriptor);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOLEAN __stdcall ORBIT_IMPL_EventProviderEnabled(uint64_t RegHandle, uint8_t Level, uint64_t Keyword) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(RegHandle);
        ORBIT_TRACK_PARAM(Level);
        ORBIT_TRACK_PARAM(Keyword);

        auto win32_impl_result = g_api_table.EventProviderEnabled(RegHandle, Level, Keyword);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_EventWrite(uint64_t RegHandle, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_DESCRIPTOR* EventDescriptor, uint32_t UserDataCount, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_DATA_DESCRIPTOR* UserData) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(RegHandle);
        ORBIT_TRACK_PARAM(EventDescriptor);
        ORBIT_TRACK_PARAM(UserDataCount);
        ORBIT_TRACK_PARAM(UserData);

        auto win32_impl_result = g_api_table.EventWrite(RegHandle, EventDescriptor, UserDataCount, UserData);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_EventWriteTransfer(uint64_t RegHandle, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_DESCRIPTOR* EventDescriptor, ::win32::guid* ActivityId, ::win32::guid* RelatedActivityId, uint32_t UserDataCount, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_DATA_DESCRIPTOR* UserData) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(RegHandle);
        ORBIT_TRACK_PARAM(EventDescriptor);
        ORBIT_TRACK_PARAM(ActivityId);
        ORBIT_TRACK_PARAM(RelatedActivityId);
        ORBIT_TRACK_PARAM(UserDataCount);
        ORBIT_TRACK_PARAM(UserData);

        auto win32_impl_result = g_api_table.EventWriteTransfer(RegHandle, EventDescriptor, ActivityId, RelatedActivityId, UserDataCount, UserData);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_EventWriteEx(uint64_t RegHandle, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_DESCRIPTOR* EventDescriptor, uint64_t Filter, uint32_t Flags, ::win32::guid* ActivityId, ::win32::guid* RelatedActivityId, uint32_t UserDataCount, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_DATA_DESCRIPTOR* UserData) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(RegHandle);
        ORBIT_TRACK_PARAM(EventDescriptor);
        ORBIT_TRACK_PARAM(Filter);
        ORBIT_TRACK_PARAM(Flags);
        ORBIT_TRACK_PARAM(ActivityId);
        ORBIT_TRACK_PARAM(RelatedActivityId);
        ORBIT_TRACK_PARAM(UserDataCount);
        ORBIT_TRACK_PARAM(UserData);

        auto win32_impl_result = g_api_table.EventWriteEx(RegHandle, EventDescriptor, Filter, Flags, ActivityId, RelatedActivityId, UserDataCount, UserData);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_EventWriteString(uint64_t RegHandle, uint8_t Level, uint64_t Keyword, win32::Windows::Win32::Foundation::PWSTR String) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(RegHandle);
        ORBIT_TRACK_PARAM(Level);
        ORBIT_TRACK_PARAM(Keyword);
        ORBIT_TRACK_PARAM(String);

        auto win32_impl_result = g_api_table.EventWriteString(RegHandle, Level, Keyword, String);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_EventActivityIdControl(uint32_t ControlCode, ::win32::guid* ActivityId) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(ControlCode);
        ORBIT_TRACK_PARAM(ActivityId);

        auto win32_impl_result = g_api_table.EventActivityIdControl(ControlCode, ActivityId);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_EventAccessControl(::win32::guid* Guid, uint32_t Operation, win32::Windows::Win32::Foundation::PSID Sid, uint32_t Rights, win32::Windows::Win32::Foundation::BOOLEAN AllowOrDeny) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(Guid);
        ORBIT_TRACK_PARAM(Operation);
        ORBIT_TRACK_PARAM(Sid);
        ORBIT_TRACK_PARAM(Rights);
        ORBIT_TRACK_PARAM(AllowOrDeny);

        auto win32_impl_result = g_api_table.EventAccessControl(Guid, Operation, Sid, Rights, AllowOrDeny);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_EventAccessQuery(::win32::guid* Guid, win32::Windows::Win32::Security::SECURITY_DESCRIPTOR* Buffer, uint32_t* BufferSize) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(Guid);
        ORBIT_TRACK_PARAM(Buffer);
        ORBIT_TRACK_PARAM(BufferSize);

        auto win32_impl_result = g_api_table.EventAccessQuery(Guid, Buffer, BufferSize);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_EventAccessRemove(::win32::guid* Guid) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(Guid);

        auto win32_impl_result = g_api_table.EventAccessRemove(Guid);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhCreatePayloadFilter(::win32::guid* ProviderGuid, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_DESCRIPTOR* EventDescriptor, win32::Windows::Win32::Foundation::BOOLEAN EventMatchANY, uint32_t PayloadPredicateCount, win32::Windows::Win32::System::Diagnostics::Etw::PAYLOAD_FILTER_PREDICATE* PayloadPredicates, void** PayloadFilter) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(ProviderGuid);
        ORBIT_TRACK_PARAM(EventDescriptor);
        ORBIT_TRACK_PARAM(EventMatchANY);
        ORBIT_TRACK_PARAM(PayloadPredicateCount);
        ORBIT_TRACK_PARAM(PayloadPredicates);
        ORBIT_TRACK_PARAM(PayloadFilter);

        auto win32_impl_result = g_api_table.TdhCreatePayloadFilter(ProviderGuid, EventDescriptor, EventMatchANY, PayloadPredicateCount, PayloadPredicates, PayloadFilter);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhDeletePayloadFilter(void** PayloadFilter) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(PayloadFilter);

        auto win32_impl_result = g_api_table.TdhDeletePayloadFilter(PayloadFilter);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhAggregatePayloadFilters(uint32_t PayloadFilterCount, void** PayloadFilterPtrs, win32::Windows::Win32::Foundation::BOOLEAN* EventMatchALLFlags, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_FILTER_DESCRIPTOR* EventFilterDescriptor) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(PayloadFilterCount);
        ORBIT_TRACK_PARAM(PayloadFilterPtrs);
        ORBIT_TRACK_PARAM(EventMatchALLFlags);
        ORBIT_TRACK_PARAM(EventFilterDescriptor);

        auto win32_impl_result = g_api_table.TdhAggregatePayloadFilters(PayloadFilterCount, PayloadFilterPtrs, EventMatchALLFlags, EventFilterDescriptor);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhCleanupPayloadEventFilterDescriptor(win32::Windows::Win32::System::Diagnostics::Etw::EVENT_FILTER_DESCRIPTOR* EventFilterDescriptor) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(EventFilterDescriptor);

        auto win32_impl_result = g_api_table.TdhCleanupPayloadEventFilterDescriptor(EventFilterDescriptor);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhGetEventInformation(win32::Windows::Win32::System::Diagnostics::Etw::EVENT_RECORD* Event, uint32_t TdhContextCount, win32::Windows::Win32::System::Diagnostics::Etw::TDH_CONTEXT* TdhContext, win32::Windows::Win32::System::Diagnostics::Etw::TRACE_EVENT_INFO* Buffer, uint32_t* BufferSize) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(Event);
        ORBIT_TRACK_PARAM(TdhContextCount);
        ORBIT_TRACK_PARAM(TdhContext);
        ORBIT_TRACK_PARAM(Buffer);
        ORBIT_TRACK_PARAM(BufferSize);

        auto win32_impl_result = g_api_table.TdhGetEventInformation(Event, TdhContextCount, TdhContext, Buffer, BufferSize);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhGetEventMapInformation(win32::Windows::Win32::System::Diagnostics::Etw::EVENT_RECORD* pEvent, win32::Windows::Win32::Foundation::PWSTR pMapName, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_MAP_INFO* pBuffer, uint32_t* pBufferSize) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pEvent);
        ORBIT_TRACK_PARAM(pMapName);
        ORBIT_TRACK_PARAM(pBuffer);
        ORBIT_TRACK_PARAM(pBufferSize);

        auto win32_impl_result = g_api_table.TdhGetEventMapInformation(pEvent, pMapName, pBuffer, pBufferSize);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhGetPropertySize(win32::Windows::Win32::System::Diagnostics::Etw::EVENT_RECORD* pEvent, uint32_t TdhContextCount, win32::Windows::Win32::System::Diagnostics::Etw::TDH_CONTEXT* pTdhContext, uint32_t PropertyDataCount, win32::Windows::Win32::System::Diagnostics::Etw::PROPERTY_DATA_DESCRIPTOR* pPropertyData, uint32_t* pPropertySize) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pEvent);
        ORBIT_TRACK_PARAM(TdhContextCount);
        ORBIT_TRACK_PARAM(pTdhContext);
        ORBIT_TRACK_PARAM(PropertyDataCount);
        ORBIT_TRACK_PARAM(pPropertyData);
        ORBIT_TRACK_PARAM(pPropertySize);

        auto win32_impl_result = g_api_table.TdhGetPropertySize(pEvent, TdhContextCount, pTdhContext, PropertyDataCount, pPropertyData, pPropertySize);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhGetProperty(win32::Windows::Win32::System::Diagnostics::Etw::EVENT_RECORD* pEvent, uint32_t TdhContextCount, win32::Windows::Win32::System::Diagnostics::Etw::TDH_CONTEXT* pTdhContext, uint32_t PropertyDataCount, win32::Windows::Win32::System::Diagnostics::Etw::PROPERTY_DATA_DESCRIPTOR* pPropertyData, uint32_t BufferSize, uint8_t* pBuffer) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pEvent);
        ORBIT_TRACK_PARAM(TdhContextCount);
        ORBIT_TRACK_PARAM(pTdhContext);
        ORBIT_TRACK_PARAM(PropertyDataCount);
        ORBIT_TRACK_PARAM(pPropertyData);
        ORBIT_TRACK_PARAM(BufferSize);
        ORBIT_TRACK_PARAM(pBuffer);

        auto win32_impl_result = g_api_table.TdhGetProperty(pEvent, TdhContextCount, pTdhContext, PropertyDataCount, pPropertyData, BufferSize, pBuffer);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhEnumerateProviders(win32::Windows::Win32::System::Diagnostics::Etw::PROVIDER_ENUMERATION_INFO* pBuffer, uint32_t* pBufferSize) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pBuffer);
        ORBIT_TRACK_PARAM(pBufferSize);

        auto win32_impl_result = g_api_table.TdhEnumerateProviders(pBuffer, pBufferSize);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhEnumerateProvidersForDecodingSource(win32::Windows::Win32::System::Diagnostics::Etw::DECODING_SOURCE filter, win32::Windows::Win32::System::Diagnostics::Etw::PROVIDER_ENUMERATION_INFO* buffer, uint32_t bufferSize, uint32_t* bufferRequired) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(filter);
        ORBIT_TRACK_PARAM(buffer);
        ORBIT_TRACK_PARAM(bufferSize);
        ORBIT_TRACK_PARAM(bufferRequired);

        auto win32_impl_result = g_api_table.TdhEnumerateProvidersForDecodingSource(filter, buffer, bufferSize, bufferRequired);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhQueryProviderFieldInformation(::win32::guid* pGuid, uint64_t EventFieldValue, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_FIELD_TYPE EventFieldType, win32::Windows::Win32::System::Diagnostics::Etw::PROVIDER_FIELD_INFOARRAY* pBuffer, uint32_t* pBufferSize) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pGuid);
        ORBIT_TRACK_PARAM(EventFieldValue);
        ORBIT_TRACK_PARAM(EventFieldType);
        ORBIT_TRACK_PARAM(pBuffer);
        ORBIT_TRACK_PARAM(pBufferSize);

        auto win32_impl_result = g_api_table.TdhQueryProviderFieldInformation(pGuid, EventFieldValue, EventFieldType, pBuffer, pBufferSize);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhEnumerateProviderFieldInformation(::win32::guid* pGuid, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_FIELD_TYPE EventFieldType, win32::Windows::Win32::System::Diagnostics::Etw::PROVIDER_FIELD_INFOARRAY* pBuffer, uint32_t* pBufferSize) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pGuid);
        ORBIT_TRACK_PARAM(EventFieldType);
        ORBIT_TRACK_PARAM(pBuffer);
        ORBIT_TRACK_PARAM(pBufferSize);

        auto win32_impl_result = g_api_table.TdhEnumerateProviderFieldInformation(pGuid, EventFieldType, pBuffer, pBufferSize);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhEnumerateProviderFilters(::win32::guid* Guid, uint32_t TdhContextCount, win32::Windows::Win32::System::Diagnostics::Etw::TDH_CONTEXT* TdhContext, uint32_t* FilterCount, win32::Windows::Win32::System::Diagnostics::Etw::PROVIDER_FILTER_INFO** Buffer, uint32_t* BufferSize) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(Guid);
        ORBIT_TRACK_PARAM(TdhContextCount);
        ORBIT_TRACK_PARAM(TdhContext);
        ORBIT_TRACK_PARAM(FilterCount);
        ORBIT_TRACK_PARAM(Buffer);
        ORBIT_TRACK_PARAM(BufferSize);

        auto win32_impl_result = g_api_table.TdhEnumerateProviderFilters(Guid, TdhContextCount, TdhContext, FilterCount, Buffer, BufferSize);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhLoadManifest(win32::Windows::Win32::Foundation::PWSTR Manifest) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(Manifest);

        auto win32_impl_result = g_api_table.TdhLoadManifest(Manifest);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhLoadManifestFromMemory(void* pData, uint32_t cbData) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pData);
        ORBIT_TRACK_PARAM(cbData);

        auto win32_impl_result = g_api_table.TdhLoadManifestFromMemory(pData, cbData);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhUnloadManifest(win32::Windows::Win32::Foundation::PWSTR Manifest) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(Manifest);

        auto win32_impl_result = g_api_table.TdhUnloadManifest(Manifest);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhUnloadManifestFromMemory(void* pData, uint32_t cbData) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pData);
        ORBIT_TRACK_PARAM(cbData);

        auto win32_impl_result = g_api_table.TdhUnloadManifestFromMemory(pData, cbData);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhFormatProperty(win32::Windows::Win32::System::Diagnostics::Etw::TRACE_EVENT_INFO* EventInfo, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_MAP_INFO* MapInfo, uint32_t PointerSize, uint16_t PropertyInType, uint16_t PropertyOutType, uint16_t PropertyLength, uint16_t UserDataLength, uint8_t* UserData, uint32_t* BufferSize, win32::Windows::Win32::Foundation::PWSTR Buffer, uint16_t* UserDataConsumed) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(EventInfo);
        ORBIT_TRACK_PARAM(MapInfo);
        ORBIT_TRACK_PARAM(PointerSize);
        ORBIT_TRACK_PARAM(PropertyInType);
        ORBIT_TRACK_PARAM(PropertyOutType);
        ORBIT_TRACK_PARAM(PropertyLength);
        ORBIT_TRACK_PARAM(UserDataLength);
        ORBIT_TRACK_PARAM(UserData);
        ORBIT_TRACK_PARAM(BufferSize);
        ORBIT_TRACK_PARAM(Buffer);
        ORBIT_TRACK_PARAM(UserDataConsumed);

        auto win32_impl_result = g_api_table.TdhFormatProperty(EventInfo, MapInfo, PointerSize, PropertyInType, PropertyOutType, PropertyLength, UserDataLength, UserData, BufferSize, Buffer, UserDataConsumed);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhOpenDecodingHandle(win32::Windows::Win32::System::Diagnostics::Etw::TDH_HANDLE* Handle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(Handle);

        auto win32_impl_result = g_api_table.TdhOpenDecodingHandle(Handle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhSetDecodingParameter(win32::Windows::Win32::System::Diagnostics::Etw::TDH_HANDLE Handle, win32::Windows::Win32::System::Diagnostics::Etw::TDH_CONTEXT* TdhContext) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(Handle);
        ORBIT_TRACK_PARAM(TdhContext);

        auto win32_impl_result = g_api_table.TdhSetDecodingParameter(Handle, TdhContext);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhGetDecodingParameter(win32::Windows::Win32::System::Diagnostics::Etw::TDH_HANDLE Handle, win32::Windows::Win32::System::Diagnostics::Etw::TDH_CONTEXT* TdhContext) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(Handle);
        ORBIT_TRACK_PARAM(TdhContext);

        auto win32_impl_result = g_api_table.TdhGetDecodingParameter(Handle, TdhContext);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhGetWppProperty(win32::Windows::Win32::System::Diagnostics::Etw::TDH_HANDLE Handle, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_RECORD* EventRecord, win32::Windows::Win32::Foundation::PWSTR PropertyName, uint32_t* BufferSize, uint8_t* Buffer) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(Handle);
        ORBIT_TRACK_PARAM(EventRecord);
        ORBIT_TRACK_PARAM(PropertyName);
        ORBIT_TRACK_PARAM(BufferSize);
        ORBIT_TRACK_PARAM(Buffer);

        auto win32_impl_result = g_api_table.TdhGetWppProperty(Handle, EventRecord, PropertyName, BufferSize, Buffer);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhGetWppMessage(win32::Windows::Win32::System::Diagnostics::Etw::TDH_HANDLE Handle, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_RECORD* EventRecord, uint32_t* BufferSize, uint8_t* Buffer) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(Handle);
        ORBIT_TRACK_PARAM(EventRecord);
        ORBIT_TRACK_PARAM(BufferSize);
        ORBIT_TRACK_PARAM(Buffer);

        auto win32_impl_result = g_api_table.TdhGetWppMessage(Handle, EventRecord, BufferSize, Buffer);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhCloseDecodingHandle(win32::Windows::Win32::System::Diagnostics::Etw::TDH_HANDLE Handle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(Handle);

        auto win32_impl_result = g_api_table.TdhCloseDecodingHandle(Handle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhLoadManifestFromBinary(win32::Windows::Win32::Foundation::PWSTR BinaryPath) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(BinaryPath);

        auto win32_impl_result = g_api_table.TdhLoadManifestFromBinary(BinaryPath);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhEnumerateManifestProviderEvents(::win32::guid* ProviderGuid, win32::Windows::Win32::System::Diagnostics::Etw::PROVIDER_EVENT_INFO* Buffer, uint32_t* BufferSize) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(ProviderGuid);
        ORBIT_TRACK_PARAM(Buffer);
        ORBIT_TRACK_PARAM(BufferSize);

        auto win32_impl_result = g_api_table.TdhEnumerateManifestProviderEvents(ProviderGuid, Buffer, BufferSize);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_TdhGetManifestEventInformation(::win32::guid* ProviderGuid, win32::Windows::Win32::System::Diagnostics::Etw::EVENT_DESCRIPTOR* EventDescriptor, win32::Windows::Win32::System::Diagnostics::Etw::TRACE_EVENT_INFO* Buffer, uint32_t* BufferSize) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(ProviderGuid);
        ORBIT_TRACK_PARAM(EventDescriptor);
        ORBIT_TRACK_PARAM(Buffer);
        ORBIT_TRACK_PARAM(BufferSize);

        auto win32_impl_result = g_api_table.TdhGetManifestEventInformation(ProviderGuid, EventDescriptor, Buffer, BufferSize);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    int32_t __stdcall ORBIT_IMPL_CveEventWrite(win32::Windows::Win32::Foundation::PWSTR CveId, win32::Windows::Win32::Foundation::PWSTR AdditionalDetails) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(CveId);
        ORBIT_TRACK_PARAM(AdditionalDetails);

        auto win32_impl_result = g_api_table.CveEventWrite(CveId, AdditionalDetails);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

}

#pragma endregion abi_methods

}
#endif
