// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_Media_Multimedia_2_H
#define WIN32_Windows_Win32_Media_Multimedia_2_H
#include "win32/Windows.Win32.Media.Multimedia.h"
#include "win32/impl/Windows.Win32.Media.Multimedia.1.h"
WIN32_EXPORT namespace win32::Windows::Win32::Media::Multimedia
{
ApiTable g_api_table;

#pragma region abi_methods
extern "C"
{
    uint32_t __stdcall ORBIT_IMPL_mciSendCommandA(uint32_t mciId, uint32_t uMsg, size_t dwParam1, size_t dwParam2) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(mciId);
        ORBIT_TRACK_PARAM(uMsg);
        ORBIT_TRACK_PARAM(dwParam1);
        ORBIT_TRACK_PARAM(dwParam2);

        auto win32_impl_result = g_api_table.mciSendCommandA(mciId, uMsg, dwParam1, dwParam2);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mciSendCommandW(uint32_t mciId, uint32_t uMsg, size_t dwParam1, size_t dwParam2) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(mciId);
        ORBIT_TRACK_PARAM(uMsg);
        ORBIT_TRACK_PARAM(dwParam1);
        ORBIT_TRACK_PARAM(dwParam2);

        auto win32_impl_result = g_api_table.mciSendCommandW(mciId, uMsg, dwParam1, dwParam2);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mciSendStringA(win32::Windows::Win32::Foundation::PSTR lpstrCommand, win32::Windows::Win32::Foundation::PSTR lpstrReturnString, uint32_t uReturnLength, win32::Windows::Win32::Foundation::HWND hwndCallback) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(lpstrCommand);
        ORBIT_TRACK_PARAM(lpstrReturnString);
        ORBIT_TRACK_PARAM(uReturnLength);
        ORBIT_TRACK_PARAM(hwndCallback);

        auto win32_impl_result = g_api_table.mciSendStringA(lpstrCommand, lpstrReturnString, uReturnLength, hwndCallback);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mciSendStringW(win32::Windows::Win32::Foundation::PWSTR lpstrCommand, win32::Windows::Win32::Foundation::PWSTR lpstrReturnString, uint32_t uReturnLength, win32::Windows::Win32::Foundation::HWND hwndCallback) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(lpstrCommand);
        ORBIT_TRACK_PARAM(lpstrReturnString);
        ORBIT_TRACK_PARAM(uReturnLength);
        ORBIT_TRACK_PARAM(hwndCallback);

        auto win32_impl_result = g_api_table.mciSendStringW(lpstrCommand, lpstrReturnString, uReturnLength, hwndCallback);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mciGetDeviceIDA(win32::Windows::Win32::Foundation::PSTR pszDevice) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pszDevice);

        auto win32_impl_result = g_api_table.mciGetDeviceIDA(pszDevice);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mciGetDeviceIDW(win32::Windows::Win32::Foundation::PWSTR pszDevice) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pszDevice);

        auto win32_impl_result = g_api_table.mciGetDeviceIDW(pszDevice);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mciGetDeviceIDFromElementIDA(uint32_t dwElementID, win32::Windows::Win32::Foundation::PSTR lpstrType) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(dwElementID);
        ORBIT_TRACK_PARAM(lpstrType);

        auto win32_impl_result = g_api_table.mciGetDeviceIDFromElementIDA(dwElementID, lpstrType);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mciGetDeviceIDFromElementIDW(uint32_t dwElementID, win32::Windows::Win32::Foundation::PWSTR lpstrType) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(dwElementID);
        ORBIT_TRACK_PARAM(lpstrType);

        auto win32_impl_result = g_api_table.mciGetDeviceIDFromElementIDW(dwElementID, lpstrType);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_mciGetErrorStringA(uint32_t mcierr, win32::Windows::Win32::Foundation::PSTR pszText, uint32_t cchText) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(mcierr);
        ORBIT_TRACK_PARAM(pszText);
        ORBIT_TRACK_PARAM(cchText);

        auto win32_impl_result = g_api_table.mciGetErrorStringA(mcierr, pszText, cchText);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_mciGetErrorStringW(uint32_t mcierr, win32::Windows::Win32::Foundation::PWSTR pszText, uint32_t cchText) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(mcierr);
        ORBIT_TRACK_PARAM(pszText);
        ORBIT_TRACK_PARAM(cchText);

        auto win32_impl_result = g_api_table.mciGetErrorStringW(mcierr, pszText, cchText);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_mciSetYieldProc(uint32_t mciId, win32::Windows::Win32::Media::Multimedia::YIELDPROC* fpYieldProc, uint32_t dwYieldData) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(mciId);
        ORBIT_TRACK_PARAM(fpYieldProc);
        ORBIT_TRACK_PARAM(dwYieldData);

        auto win32_impl_result = g_api_table.mciSetYieldProc(mciId, fpYieldProc, dwYieldData);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Media::Audio::HTASK __stdcall ORBIT_IMPL_mciGetCreatorTask(uint32_t mciId) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(mciId);

        auto win32_impl_result = g_api_table.mciGetCreatorTask(mciId);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Media::Multimedia::YIELDPROC* __stdcall ORBIT_IMPL_mciGetYieldProc(uint32_t mciId, uint32_t* pdwYieldData) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(mciId);
        ORBIT_TRACK_PARAM(pdwYieldData);

        auto win32_impl_result = g_api_table.mciGetYieldProc(mciId, pdwYieldData);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    size_t __stdcall ORBIT_IMPL_mciGetDriverData(uint32_t wDeviceID) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(wDeviceID);

        auto win32_impl_result = g_api_table.mciGetDriverData(wDeviceID);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mciLoadCommandResource(win32::Windows::Win32::Foundation::HANDLE hInstance, win32::Windows::Win32::Foundation::PWSTR lpResName, uint32_t wType) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hInstance);
        ORBIT_TRACK_PARAM(lpResName);
        ORBIT_TRACK_PARAM(wType);

        auto win32_impl_result = g_api_table.mciLoadCommandResource(hInstance, lpResName, wType);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_mciSetDriverData(uint32_t wDeviceID, size_t dwData) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(wDeviceID);
        ORBIT_TRACK_PARAM(dwData);

        auto win32_impl_result = g_api_table.mciSetDriverData(wDeviceID, dwData);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mciDriverYield(uint32_t wDeviceID) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(wDeviceID);

        auto win32_impl_result = g_api_table.mciDriverYield(wDeviceID);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_mciDriverNotify(win32::Windows::Win32::Foundation::HANDLE hwndCallback, uint32_t wDeviceID, uint32_t uStatus) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hwndCallback);
        ORBIT_TRACK_PARAM(wDeviceID);
        ORBIT_TRACK_PARAM(uStatus);

        auto win32_impl_result = g_api_table.mciDriverNotify(hwndCallback, wDeviceID, uStatus);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_mciFreeCommandResource(uint32_t wTable) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(wTable);

        auto win32_impl_result = g_api_table.mciFreeCommandResource(wTable);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::LRESULT __stdcall ORBIT_IMPL_CloseDriver(win32::Windows::Win32::Media::Multimedia::HDRVR hDriver, win32::Windows::Win32::Foundation::LPARAM lParam1, win32::Windows::Win32::Foundation::LPARAM lParam2) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hDriver);
        ORBIT_TRACK_PARAM(lParam1);
        ORBIT_TRACK_PARAM(lParam2);

        auto win32_impl_result = g_api_table.CloseDriver(hDriver, lParam1, lParam2);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Media::Multimedia::HDRVR __stdcall ORBIT_IMPL_OpenDriver(win32::Windows::Win32::Foundation::PWSTR szDriverName, win32::Windows::Win32::Foundation::PWSTR szSectionName, win32::Windows::Win32::Foundation::LPARAM lParam2) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(szDriverName);
        ORBIT_TRACK_PARAM(szSectionName);
        ORBIT_TRACK_PARAM(lParam2);

        auto win32_impl_result = g_api_table.OpenDriver(szDriverName, szSectionName, lParam2);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::LRESULT __stdcall ORBIT_IMPL_SendDriverMessage(win32::Windows::Win32::Media::Multimedia::HDRVR hDriver, uint32_t message, win32::Windows::Win32::Foundation::LPARAM lParam1, win32::Windows::Win32::Foundation::LPARAM lParam2) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hDriver);
        ORBIT_TRACK_PARAM(message);
        ORBIT_TRACK_PARAM(lParam1);
        ORBIT_TRACK_PARAM(lParam2);

        auto win32_impl_result = g_api_table.SendDriverMessage(hDriver, message, lParam1, lParam2);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HINSTANCE __stdcall ORBIT_IMPL_DrvGetModuleHandle(win32::Windows::Win32::Media::Multimedia::HDRVR hDriver) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hDriver);

        auto win32_impl_result = g_api_table.DrvGetModuleHandle(hDriver);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HINSTANCE __stdcall ORBIT_IMPL_GetDriverModuleHandle(win32::Windows::Win32::Media::Multimedia::HDRVR hDriver) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hDriver);

        auto win32_impl_result = g_api_table.GetDriverModuleHandle(hDriver);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::LRESULT __stdcall ORBIT_IMPL_DefDriverProc(size_t dwDriverIdentifier, win32::Windows::Win32::Media::Multimedia::HDRVR hdrvr, uint32_t uMsg, win32::Windows::Win32::Foundation::LPARAM lParam1, win32::Windows::Win32::Foundation::LPARAM lParam2) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(dwDriverIdentifier);
        ORBIT_TRACK_PARAM(hdrvr);
        ORBIT_TRACK_PARAM(uMsg);
        ORBIT_TRACK_PARAM(lParam1);
        ORBIT_TRACK_PARAM(lParam2);

        auto win32_impl_result = g_api_table.DefDriverProc(dwDriverIdentifier, hdrvr, uMsg, lParam1, lParam2);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_DriverCallback(size_t dwCallback, uint32_t dwFlags, win32::Windows::Win32::Media::Multimedia::HDRVR hDevice, uint32_t dwMsg, size_t dwUser, size_t dwParam1, size_t dwParam2) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(dwCallback);
        ORBIT_TRACK_PARAM(dwFlags);
        ORBIT_TRACK_PARAM(hDevice);
        ORBIT_TRACK_PARAM(dwMsg);
        ORBIT_TRACK_PARAM(dwUser);
        ORBIT_TRACK_PARAM(dwParam1);
        ORBIT_TRACK_PARAM(dwParam2);

        auto win32_impl_result = g_api_table.DriverCallback(dwCallback, dwFlags, hDevice, dwMsg, dwUser, dwParam1, dwParam2);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    int32_t __stdcall ORBIT_IMPL_sndOpenSound(win32::Windows::Win32::Foundation::PWSTR EventName, win32::Windows::Win32::Foundation::PWSTR AppName, int32_t Flags, win32::Windows::Win32::Foundation::HANDLE* FileHandle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(EventName);
        ORBIT_TRACK_PARAM(AppName);
        ORBIT_TRACK_PARAM(Flags);
        ORBIT_TRACK_PARAM(FileHandle);

        auto win32_impl_result = g_api_table.sndOpenSound(EventName, AppName, Flags, FileHandle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mmDrvInstall(win32::Windows::Win32::Media::Multimedia::HDRVR hDriver, win32::Windows::Win32::Foundation::PWSTR wszDrvEntry, win32::Windows::Win32::Media::Multimedia::DRIVERMSGPROC* drvMessage, uint32_t wFlags) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hDriver);
        ORBIT_TRACK_PARAM(wszDrvEntry);
        ORBIT_TRACK_PARAM(drvMessage);
        ORBIT_TRACK_PARAM(wFlags);

        auto win32_impl_result = g_api_table.mmDrvInstall(hDriver, wszDrvEntry, drvMessage, wFlags);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mmioStringToFOURCCA(win32::Windows::Win32::Foundation::PSTR sz, uint32_t uFlags) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(sz);
        ORBIT_TRACK_PARAM(uFlags);

        auto win32_impl_result = g_api_table.mmioStringToFOURCCA(sz, uFlags);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mmioStringToFOURCCW(win32::Windows::Win32::Foundation::PWSTR sz, uint32_t uFlags) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(sz);
        ORBIT_TRACK_PARAM(uFlags);

        auto win32_impl_result = g_api_table.mmioStringToFOURCCW(sz, uFlags);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Media::Multimedia::LPMMIOPROC* __stdcall ORBIT_IMPL_mmioInstallIOProcA(uint32_t fccIOProc, win32::Windows::Win32::Media::Multimedia::LPMMIOPROC* pIOProc, uint32_t dwFlags) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(fccIOProc);
        ORBIT_TRACK_PARAM(pIOProc);
        ORBIT_TRACK_PARAM(dwFlags);

        auto win32_impl_result = g_api_table.mmioInstallIOProcA(fccIOProc, pIOProc, dwFlags);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Media::Multimedia::LPMMIOPROC* __stdcall ORBIT_IMPL_mmioInstallIOProcW(uint32_t fccIOProc, win32::Windows::Win32::Media::Multimedia::LPMMIOPROC* pIOProc, uint32_t dwFlags) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(fccIOProc);
        ORBIT_TRACK_PARAM(pIOProc);
        ORBIT_TRACK_PARAM(dwFlags);

        auto win32_impl_result = g_api_table.mmioInstallIOProcW(fccIOProc, pIOProc, dwFlags);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Media::Multimedia::HMMIO __stdcall ORBIT_IMPL_mmioOpenA(win32::Windows::Win32::Foundation::PSTR pszFileName, win32::Windows::Win32::Media::Multimedia::MMIOINFO* pmmioinfo, uint32_t fdwOpen) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pszFileName);
        ORBIT_TRACK_PARAM(pmmioinfo);
        ORBIT_TRACK_PARAM(fdwOpen);

        auto win32_impl_result = g_api_table.mmioOpenA(pszFileName, pmmioinfo, fdwOpen);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Media::Multimedia::HMMIO __stdcall ORBIT_IMPL_mmioOpenW(win32::Windows::Win32::Foundation::PWSTR pszFileName, win32::Windows::Win32::Media::Multimedia::MMIOINFO* pmmioinfo, uint32_t fdwOpen) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pszFileName);
        ORBIT_TRACK_PARAM(pmmioinfo);
        ORBIT_TRACK_PARAM(fdwOpen);

        auto win32_impl_result = g_api_table.mmioOpenW(pszFileName, pmmioinfo, fdwOpen);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mmioRenameA(win32::Windows::Win32::Foundation::PSTR pszFileName, win32::Windows::Win32::Foundation::PSTR pszNewFileName, win32::Windows::Win32::Media::Multimedia::MMIOINFO* pmmioinfo, uint32_t fdwRename) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pszFileName);
        ORBIT_TRACK_PARAM(pszNewFileName);
        ORBIT_TRACK_PARAM(pmmioinfo);
        ORBIT_TRACK_PARAM(fdwRename);

        auto win32_impl_result = g_api_table.mmioRenameA(pszFileName, pszNewFileName, pmmioinfo, fdwRename);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mmioRenameW(win32::Windows::Win32::Foundation::PWSTR pszFileName, win32::Windows::Win32::Foundation::PWSTR pszNewFileName, win32::Windows::Win32::Media::Multimedia::MMIOINFO* pmmioinfo, uint32_t fdwRename) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pszFileName);
        ORBIT_TRACK_PARAM(pszNewFileName);
        ORBIT_TRACK_PARAM(pmmioinfo);
        ORBIT_TRACK_PARAM(fdwRename);

        auto win32_impl_result = g_api_table.mmioRenameW(pszFileName, pszNewFileName, pmmioinfo, fdwRename);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mmioClose(win32::Windows::Win32::Media::Multimedia::HMMIO hmmio, uint32_t fuClose) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hmmio);
        ORBIT_TRACK_PARAM(fuClose);

        auto win32_impl_result = g_api_table.mmioClose(hmmio, fuClose);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    int32_t __stdcall ORBIT_IMPL_mmioRead(win32::Windows::Win32::Media::Multimedia::HMMIO hmmio, int8_t* pch, int32_t cch) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hmmio);
        ORBIT_TRACK_PARAM(pch);
        ORBIT_TRACK_PARAM(cch);

        auto win32_impl_result = g_api_table.mmioRead(hmmio, pch, cch);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    int32_t __stdcall ORBIT_IMPL_mmioWrite(win32::Windows::Win32::Media::Multimedia::HMMIO hmmio, win32::Windows::Win32::Foundation::PSTR pch, int32_t cch) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hmmio);
        ORBIT_TRACK_PARAM(pch);
        ORBIT_TRACK_PARAM(cch);

        auto win32_impl_result = g_api_table.mmioWrite(hmmio, pch, cch);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    int32_t __stdcall ORBIT_IMPL_mmioSeek(win32::Windows::Win32::Media::Multimedia::HMMIO hmmio, int32_t lOffset, int32_t iOrigin) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hmmio);
        ORBIT_TRACK_PARAM(lOffset);
        ORBIT_TRACK_PARAM(iOrigin);

        auto win32_impl_result = g_api_table.mmioSeek(hmmio, lOffset, iOrigin);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mmioGetInfo(win32::Windows::Win32::Media::Multimedia::HMMIO hmmio, win32::Windows::Win32::Media::Multimedia::MMIOINFO* pmmioinfo, uint32_t fuInfo) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hmmio);
        ORBIT_TRACK_PARAM(pmmioinfo);
        ORBIT_TRACK_PARAM(fuInfo);

        auto win32_impl_result = g_api_table.mmioGetInfo(hmmio, pmmioinfo, fuInfo);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mmioSetInfo(win32::Windows::Win32::Media::Multimedia::HMMIO hmmio, win32::Windows::Win32::Media::Multimedia::MMIOINFO* pmmioinfo, uint32_t fuInfo) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hmmio);
        ORBIT_TRACK_PARAM(pmmioinfo);
        ORBIT_TRACK_PARAM(fuInfo);

        auto win32_impl_result = g_api_table.mmioSetInfo(hmmio, pmmioinfo, fuInfo);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mmioSetBuffer(win32::Windows::Win32::Media::Multimedia::HMMIO hmmio, win32::Windows::Win32::Foundation::PSTR pchBuffer, int32_t cchBuffer, uint32_t fuBuffer) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hmmio);
        ORBIT_TRACK_PARAM(pchBuffer);
        ORBIT_TRACK_PARAM(cchBuffer);
        ORBIT_TRACK_PARAM(fuBuffer);

        auto win32_impl_result = g_api_table.mmioSetBuffer(hmmio, pchBuffer, cchBuffer, fuBuffer);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mmioFlush(win32::Windows::Win32::Media::Multimedia::HMMIO hmmio, uint32_t fuFlush) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hmmio);
        ORBIT_TRACK_PARAM(fuFlush);

        auto win32_impl_result = g_api_table.mmioFlush(hmmio, fuFlush);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mmioAdvance(win32::Windows::Win32::Media::Multimedia::HMMIO hmmio, win32::Windows::Win32::Media::Multimedia::MMIOINFO* pmmioinfo, uint32_t fuAdvance) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hmmio);
        ORBIT_TRACK_PARAM(pmmioinfo);
        ORBIT_TRACK_PARAM(fuAdvance);

        auto win32_impl_result = g_api_table.mmioAdvance(hmmio, pmmioinfo, fuAdvance);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::LRESULT __stdcall ORBIT_IMPL_mmioSendMessage(win32::Windows::Win32::Media::Multimedia::HMMIO hmmio, uint32_t uMsg, win32::Windows::Win32::Foundation::LPARAM lParam1, win32::Windows::Win32::Foundation::LPARAM lParam2) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hmmio);
        ORBIT_TRACK_PARAM(uMsg);
        ORBIT_TRACK_PARAM(lParam1);
        ORBIT_TRACK_PARAM(lParam2);

        auto win32_impl_result = g_api_table.mmioSendMessage(hmmio, uMsg, lParam1, lParam2);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mmioDescend(win32::Windows::Win32::Media::Multimedia::HMMIO hmmio, win32::Windows::Win32::Media::Multimedia::MMCKINFO* pmmcki, win32::Windows::Win32::Media::Multimedia::MMCKINFO* pmmckiParent, uint32_t fuDescend) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hmmio);
        ORBIT_TRACK_PARAM(pmmcki);
        ORBIT_TRACK_PARAM(pmmckiParent);
        ORBIT_TRACK_PARAM(fuDescend);

        auto win32_impl_result = g_api_table.mmioDescend(hmmio, pmmcki, pmmckiParent, fuDescend);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mmioAscend(win32::Windows::Win32::Media::Multimedia::HMMIO hmmio, win32::Windows::Win32::Media::Multimedia::MMCKINFO* pmmcki, uint32_t fuAscend) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hmmio);
        ORBIT_TRACK_PARAM(pmmcki);
        ORBIT_TRACK_PARAM(fuAscend);

        auto win32_impl_result = g_api_table.mmioAscend(hmmio, pmmcki, fuAscend);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mmioCreateChunk(win32::Windows::Win32::Media::Multimedia::HMMIO hmmio, win32::Windows::Win32::Media::Multimedia::MMCKINFO* pmmcki, uint32_t fuCreate) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hmmio);
        ORBIT_TRACK_PARAM(pmmcki);
        ORBIT_TRACK_PARAM(fuCreate);

        auto win32_impl_result = g_api_table.mmioCreateChunk(hmmio, pmmcki, fuCreate);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_joyGetPosEx(uint32_t uJoyID, win32::Windows::Win32::Media::Multimedia::JOYINFOEX* pji) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(uJoyID);
        ORBIT_TRACK_PARAM(pji);

        auto win32_impl_result = g_api_table.joyGetPosEx(uJoyID, pji);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_joyGetNumDevs() noexcept
    {
        ORBIT_SCOPE_FUNCTION();

        auto win32_impl_result = g_api_table.joyGetNumDevs();
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_joyGetDevCapsA(size_t uJoyID, win32::Windows::Win32::Media::Multimedia::JOYCAPSA* pjc, uint32_t cbjc) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(uJoyID);
        ORBIT_TRACK_PARAM(pjc);
        ORBIT_TRACK_PARAM(cbjc);

        auto win32_impl_result = g_api_table.joyGetDevCapsA(uJoyID, pjc, cbjc);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_joyGetDevCapsW(size_t uJoyID, win32::Windows::Win32::Media::Multimedia::JOYCAPSW* pjc, uint32_t cbjc) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(uJoyID);
        ORBIT_TRACK_PARAM(pjc);
        ORBIT_TRACK_PARAM(cbjc);

        auto win32_impl_result = g_api_table.joyGetDevCapsW(uJoyID, pjc, cbjc);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_joyGetPos(uint32_t uJoyID, win32::Windows::Win32::Media::Multimedia::JOYINFO* pji) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(uJoyID);
        ORBIT_TRACK_PARAM(pji);

        auto win32_impl_result = g_api_table.joyGetPos(uJoyID, pji);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_joyGetThreshold(uint32_t uJoyID, uint32_t* puThreshold) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(uJoyID);
        ORBIT_TRACK_PARAM(puThreshold);

        auto win32_impl_result = g_api_table.joyGetThreshold(uJoyID, puThreshold);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_joyReleaseCapture(uint32_t uJoyID) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(uJoyID);

        auto win32_impl_result = g_api_table.joyReleaseCapture(uJoyID);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_joySetCapture(win32::Windows::Win32::Foundation::HWND hwnd, uint32_t uJoyID, uint32_t uPeriod, win32::Windows::Win32::Foundation::BOOL fChanged) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hwnd);
        ORBIT_TRACK_PARAM(uJoyID);
        ORBIT_TRACK_PARAM(uPeriod);
        ORBIT_TRACK_PARAM(fChanged);

        auto win32_impl_result = g_api_table.joySetCapture(hwnd, uJoyID, uPeriod, fChanged);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_joySetThreshold(uint32_t uJoyID, uint32_t uThreshold) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(uJoyID);
        ORBIT_TRACK_PARAM(uThreshold);

        auto win32_impl_result = g_api_table.joySetThreshold(uJoyID, uThreshold);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_VideoForWindowsVersion() noexcept
    {
        ORBIT_SCOPE_FUNCTION();

        auto win32_impl_result = g_api_table.VideoForWindowsVersion();
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_ICInfo(uint32_t fccType, uint32_t fccHandler, win32::Windows::Win32::Media::Multimedia::ICINFO* lpicinfo) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(fccType);
        ORBIT_TRACK_PARAM(fccHandler);
        ORBIT_TRACK_PARAM(lpicinfo);

        auto win32_impl_result = g_api_table.ICInfo(fccType, fccHandler, lpicinfo);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_ICInstall(uint32_t fccType, uint32_t fccHandler, win32::Windows::Win32::Foundation::LPARAM lParam, win32::Windows::Win32::Foundation::PSTR szDesc, uint32_t wFlags) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(fccType);
        ORBIT_TRACK_PARAM(fccHandler);
        ORBIT_TRACK_PARAM(lParam);
        ORBIT_TRACK_PARAM(szDesc);
        ORBIT_TRACK_PARAM(wFlags);

        auto win32_impl_result = g_api_table.ICInstall(fccType, fccHandler, lParam, szDesc, wFlags);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_ICRemove(uint32_t fccType, uint32_t fccHandler, uint32_t wFlags) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(fccType);
        ORBIT_TRACK_PARAM(fccHandler);
        ORBIT_TRACK_PARAM(wFlags);

        auto win32_impl_result = g_api_table.ICRemove(fccType, fccHandler, wFlags);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::LRESULT __stdcall ORBIT_IMPL_ICGetInfo(win32::Windows::Win32::Media::Multimedia::HIC hic, win32::Windows::Win32::Media::Multimedia::ICINFO* picinfo, uint32_t cb) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hic);
        ORBIT_TRACK_PARAM(picinfo);
        ORBIT_TRACK_PARAM(cb);

        auto win32_impl_result = g_api_table.ICGetInfo(hic, picinfo, cb);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Media::Multimedia::HIC __stdcall ORBIT_IMPL_ICOpen(uint32_t fccType, uint32_t fccHandler, uint32_t wMode) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(fccType);
        ORBIT_TRACK_PARAM(fccHandler);
        ORBIT_TRACK_PARAM(wMode);

        auto win32_impl_result = g_api_table.ICOpen(fccType, fccHandler, wMode);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Media::Multimedia::HIC __stdcall ORBIT_IMPL_ICOpenFunction(uint32_t fccType, uint32_t fccHandler, uint32_t wMode, win32::Windows::Win32::Foundation::FARPROC* lpfnHandler) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(fccType);
        ORBIT_TRACK_PARAM(fccHandler);
        ORBIT_TRACK_PARAM(wMode);
        ORBIT_TRACK_PARAM(lpfnHandler);

        auto win32_impl_result = g_api_table.ICOpenFunction(fccType, fccHandler, wMode, lpfnHandler);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::LRESULT __stdcall ORBIT_IMPL_ICClose(win32::Windows::Win32::Media::Multimedia::HIC hic) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hic);

        auto win32_impl_result = g_api_table.ICClose(hic);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::LRESULT __stdcall ORBIT_IMPL_ICSendMessage(win32::Windows::Win32::Media::Multimedia::HIC hic, uint32_t msg, size_t dw1, size_t dw2) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hic);
        ORBIT_TRACK_PARAM(msg);
        ORBIT_TRACK_PARAM(dw1);
        ORBIT_TRACK_PARAM(dw2);

        auto win32_impl_result = g_api_table.ICSendMessage(hic, msg, dw1, dw2);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_ICCompress(win32::Windows::Win32::Media::Multimedia::HIC hic, uint32_t dwFlags, win32::Windows::Win32::Graphics::Gdi::BITMAPINFOHEADER* lpbiOutput, void* lpData, win32::Windows::Win32::Graphics::Gdi::BITMAPINFOHEADER* lpbiInput, void* lpBits, uint32_t* lpckid, uint32_t* lpdwFlags, int32_t lFrameNum, uint32_t dwFrameSize, uint32_t dwQuality, win32::Windows::Win32::Graphics::Gdi::BITMAPINFOHEADER* lpbiPrev, void* lpPrev) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hic);
        ORBIT_TRACK_PARAM(dwFlags);
        ORBIT_TRACK_PARAM(lpbiOutput);
        ORBIT_TRACK_PARAM(lpData);
        ORBIT_TRACK_PARAM(lpbiInput);
        ORBIT_TRACK_PARAM(lpBits);
        ORBIT_TRACK_PARAM(lpckid);
        ORBIT_TRACK_PARAM(lpdwFlags);
        ORBIT_TRACK_PARAM(lFrameNum);
        ORBIT_TRACK_PARAM(dwFrameSize);
        ORBIT_TRACK_PARAM(dwQuality);
        ORBIT_TRACK_PARAM(lpbiPrev);
        ORBIT_TRACK_PARAM(lpPrev);

        auto win32_impl_result = g_api_table.ICCompress(hic, dwFlags, lpbiOutput, lpData, lpbiInput, lpBits, lpckid, lpdwFlags, lFrameNum, dwFrameSize, dwQuality, lpbiPrev, lpPrev);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_ICDecompress(win32::Windows::Win32::Media::Multimedia::HIC hic, uint32_t dwFlags, win32::Windows::Win32::Graphics::Gdi::BITMAPINFOHEADER* lpbiFormat, void* lpData, win32::Windows::Win32::Graphics::Gdi::BITMAPINFOHEADER* lpbi, void* lpBits) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hic);
        ORBIT_TRACK_PARAM(dwFlags);
        ORBIT_TRACK_PARAM(lpbiFormat);
        ORBIT_TRACK_PARAM(lpData);
        ORBIT_TRACK_PARAM(lpbi);
        ORBIT_TRACK_PARAM(lpBits);

        auto win32_impl_result = g_api_table.ICDecompress(hic, dwFlags, lpbiFormat, lpData, lpbi, lpBits);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_ICDrawBegin(win32::Windows::Win32::Media::Multimedia::HIC hic, uint32_t dwFlags, win32::Windows::Win32::Graphics::Gdi::HPALETTE hpal, win32::Windows::Win32::Foundation::HWND hwnd, win32::Windows::Win32::Graphics::Gdi::HDC hdc, int32_t xDst, int32_t yDst, int32_t dxDst, int32_t dyDst, win32::Windows::Win32::Graphics::Gdi::BITMAPINFOHEADER* lpbi, int32_t xSrc, int32_t ySrc, int32_t dxSrc, int32_t dySrc, uint32_t dwRate, uint32_t dwScale) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hic);
        ORBIT_TRACK_PARAM(dwFlags);
        ORBIT_TRACK_PARAM(hpal);
        ORBIT_TRACK_PARAM(hwnd);
        ORBIT_TRACK_PARAM(hdc);
        ORBIT_TRACK_PARAM(xDst);
        ORBIT_TRACK_PARAM(yDst);
        ORBIT_TRACK_PARAM(dxDst);
        ORBIT_TRACK_PARAM(dyDst);
        ORBIT_TRACK_PARAM(lpbi);
        ORBIT_TRACK_PARAM(xSrc);
        ORBIT_TRACK_PARAM(ySrc);
        ORBIT_TRACK_PARAM(dxSrc);
        ORBIT_TRACK_PARAM(dySrc);
        ORBIT_TRACK_PARAM(dwRate);
        ORBIT_TRACK_PARAM(dwScale);

        auto win32_impl_result = g_api_table.ICDrawBegin(hic, dwFlags, hpal, hwnd, hdc, xDst, yDst, dxDst, dyDst, lpbi, xSrc, ySrc, dxSrc, dySrc, dwRate, dwScale);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_ICDraw(win32::Windows::Win32::Media::Multimedia::HIC hic, uint32_t dwFlags, void* lpFormat, void* lpData, uint32_t cbData, int32_t lTime) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hic);
        ORBIT_TRACK_PARAM(dwFlags);
        ORBIT_TRACK_PARAM(lpFormat);
        ORBIT_TRACK_PARAM(lpData);
        ORBIT_TRACK_PARAM(cbData);
        ORBIT_TRACK_PARAM(lTime);

        auto win32_impl_result = g_api_table.ICDraw(hic, dwFlags, lpFormat, lpData, cbData, lTime);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Media::Multimedia::HIC __stdcall ORBIT_IMPL_ICLocate(uint32_t fccType, uint32_t fccHandler, win32::Windows::Win32::Graphics::Gdi::BITMAPINFOHEADER* lpbiIn, win32::Windows::Win32::Graphics::Gdi::BITMAPINFOHEADER* lpbiOut, uint16_t wFlags) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(fccType);
        ORBIT_TRACK_PARAM(fccHandler);
        ORBIT_TRACK_PARAM(lpbiIn);
        ORBIT_TRACK_PARAM(lpbiOut);
        ORBIT_TRACK_PARAM(wFlags);

        auto win32_impl_result = g_api_table.ICLocate(fccType, fccHandler, lpbiIn, lpbiOut, wFlags);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Media::Multimedia::HIC __stdcall ORBIT_IMPL_ICGetDisplayFormat(win32::Windows::Win32::Media::Multimedia::HIC hic, win32::Windows::Win32::Graphics::Gdi::BITMAPINFOHEADER* lpbiIn, win32::Windows::Win32::Graphics::Gdi::BITMAPINFOHEADER* lpbiOut, int32_t BitDepth, int32_t dx, int32_t dy) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hic);
        ORBIT_TRACK_PARAM(lpbiIn);
        ORBIT_TRACK_PARAM(lpbiOut);
        ORBIT_TRACK_PARAM(BitDepth);
        ORBIT_TRACK_PARAM(dx);
        ORBIT_TRACK_PARAM(dy);

        auto win32_impl_result = g_api_table.ICGetDisplayFormat(hic, lpbiIn, lpbiOut, BitDepth, dx, dy);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HANDLE __stdcall ORBIT_IMPL_ICImageCompress(win32::Windows::Win32::Media::Multimedia::HIC hic, uint32_t uiFlags, win32::Windows::Win32::Graphics::Gdi::BITMAPINFO* lpbiIn, void* lpBits, win32::Windows::Win32::Graphics::Gdi::BITMAPINFO* lpbiOut, int32_t lQuality, int32_t* plSize) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hic);
        ORBIT_TRACK_PARAM(uiFlags);
        ORBIT_TRACK_PARAM(lpbiIn);
        ORBIT_TRACK_PARAM(lpBits);
        ORBIT_TRACK_PARAM(lpbiOut);
        ORBIT_TRACK_PARAM(lQuality);
        ORBIT_TRACK_PARAM(plSize);

        auto win32_impl_result = g_api_table.ICImageCompress(hic, uiFlags, lpbiIn, lpBits, lpbiOut, lQuality, plSize);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HANDLE __stdcall ORBIT_IMPL_ICImageDecompress(win32::Windows::Win32::Media::Multimedia::HIC hic, uint32_t uiFlags, win32::Windows::Win32::Graphics::Gdi::BITMAPINFO* lpbiIn, void* lpBits, win32::Windows::Win32::Graphics::Gdi::BITMAPINFO* lpbiOut) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hic);
        ORBIT_TRACK_PARAM(uiFlags);
        ORBIT_TRACK_PARAM(lpbiIn);
        ORBIT_TRACK_PARAM(lpBits);
        ORBIT_TRACK_PARAM(lpbiOut);

        auto win32_impl_result = g_api_table.ICImageDecompress(hic, uiFlags, lpbiIn, lpBits, lpbiOut);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_ICCompressorChoose(win32::Windows::Win32::Foundation::HWND hwnd, uint32_t uiFlags, void* pvIn, void* lpData, win32::Windows::Win32::Media::Multimedia::COMPVARS* pc, win32::Windows::Win32::Foundation::PSTR lpszTitle) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hwnd);
        ORBIT_TRACK_PARAM(uiFlags);
        ORBIT_TRACK_PARAM(pvIn);
        ORBIT_TRACK_PARAM(lpData);
        ORBIT_TRACK_PARAM(pc);
        ORBIT_TRACK_PARAM(lpszTitle);

        auto win32_impl_result = g_api_table.ICCompressorChoose(hwnd, uiFlags, pvIn, lpData, pc, lpszTitle);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_ICSeqCompressFrameStart(win32::Windows::Win32::Media::Multimedia::COMPVARS* pc, win32::Windows::Win32::Graphics::Gdi::BITMAPINFO* lpbiIn) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pc);
        ORBIT_TRACK_PARAM(lpbiIn);

        auto win32_impl_result = g_api_table.ICSeqCompressFrameStart(pc, lpbiIn);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    void __stdcall ORBIT_IMPL_ICSeqCompressFrameEnd(win32::Windows::Win32::Media::Multimedia::COMPVARS* pc) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pc);

        g_api_table.ICSeqCompressFrameEnd(pc);
        
    }

    void* __stdcall ORBIT_IMPL_ICSeqCompressFrame(win32::Windows::Win32::Media::Multimedia::COMPVARS* pc, uint32_t uiFlags, void* lpBits, win32::Windows::Win32::Foundation::BOOL* pfKey, int32_t* plSize) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pc);
        ORBIT_TRACK_PARAM(uiFlags);
        ORBIT_TRACK_PARAM(lpBits);
        ORBIT_TRACK_PARAM(pfKey);
        ORBIT_TRACK_PARAM(plSize);

        auto win32_impl_result = g_api_table.ICSeqCompressFrame(pc, uiFlags, lpBits, pfKey, plSize);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    void __stdcall ORBIT_IMPL_ICCompressorFree(win32::Windows::Win32::Media::Multimedia::COMPVARS* pc) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pc);

        g_api_table.ICCompressorFree(pc);
        
    }

    intptr_t __stdcall ORBIT_IMPL_DrawDibOpen() noexcept
    {
        ORBIT_SCOPE_FUNCTION();

        auto win32_impl_result = g_api_table.DrawDibOpen();
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_DrawDibClose(intptr_t hdd) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hdd);

        auto win32_impl_result = g_api_table.DrawDibClose(hdd);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    void* __stdcall ORBIT_IMPL_DrawDibGetBuffer(intptr_t hdd, win32::Windows::Win32::Graphics::Gdi::BITMAPINFOHEADER* lpbi, uint32_t dwSize, uint32_t dwFlags) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hdd);
        ORBIT_TRACK_PARAM(lpbi);
        ORBIT_TRACK_PARAM(dwSize);
        ORBIT_TRACK_PARAM(dwFlags);

        auto win32_impl_result = g_api_table.DrawDibGetBuffer(hdd, lpbi, dwSize, dwFlags);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Graphics::Gdi::HPALETTE __stdcall ORBIT_IMPL_DrawDibGetPalette(intptr_t hdd) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hdd);

        auto win32_impl_result = g_api_table.DrawDibGetPalette(hdd);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_DrawDibSetPalette(intptr_t hdd, win32::Windows::Win32::Graphics::Gdi::HPALETTE hpal) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hdd);
        ORBIT_TRACK_PARAM(hpal);

        auto win32_impl_result = g_api_table.DrawDibSetPalette(hdd, hpal);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_DrawDibChangePalette(intptr_t hdd, int32_t iStart, int32_t iLen, win32::Windows::Win32::Graphics::Gdi::PALETTEENTRY* lppe) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hdd);
        ORBIT_TRACK_PARAM(iStart);
        ORBIT_TRACK_PARAM(iLen);
        ORBIT_TRACK_PARAM(lppe);

        auto win32_impl_result = g_api_table.DrawDibChangePalette(hdd, iStart, iLen, lppe);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_DrawDibRealize(intptr_t hdd, win32::Windows::Win32::Graphics::Gdi::HDC hdc, win32::Windows::Win32::Foundation::BOOL fBackground) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hdd);
        ORBIT_TRACK_PARAM(hdc);
        ORBIT_TRACK_PARAM(fBackground);

        auto win32_impl_result = g_api_table.DrawDibRealize(hdd, hdc, fBackground);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_DrawDibStart(intptr_t hdd, uint32_t rate) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hdd);
        ORBIT_TRACK_PARAM(rate);

        auto win32_impl_result = g_api_table.DrawDibStart(hdd, rate);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_DrawDibStop(intptr_t hdd) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hdd);

        auto win32_impl_result = g_api_table.DrawDibStop(hdd);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_DrawDibBegin(intptr_t hdd, win32::Windows::Win32::Graphics::Gdi::HDC hdc, int32_t dxDst, int32_t dyDst, win32::Windows::Win32::Graphics::Gdi::BITMAPINFOHEADER* lpbi, int32_t dxSrc, int32_t dySrc, uint32_t wFlags) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hdd);
        ORBIT_TRACK_PARAM(hdc);
        ORBIT_TRACK_PARAM(dxDst);
        ORBIT_TRACK_PARAM(dyDst);
        ORBIT_TRACK_PARAM(lpbi);
        ORBIT_TRACK_PARAM(dxSrc);
        ORBIT_TRACK_PARAM(dySrc);
        ORBIT_TRACK_PARAM(wFlags);

        auto win32_impl_result = g_api_table.DrawDibBegin(hdd, hdc, dxDst, dyDst, lpbi, dxSrc, dySrc, wFlags);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_DrawDibDraw(intptr_t hdd, win32::Windows::Win32::Graphics::Gdi::HDC hdc, int32_t xDst, int32_t yDst, int32_t dxDst, int32_t dyDst, win32::Windows::Win32::Graphics::Gdi::BITMAPINFOHEADER* lpbi, void* lpBits, int32_t xSrc, int32_t ySrc, int32_t dxSrc, int32_t dySrc, uint32_t wFlags) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hdd);
        ORBIT_TRACK_PARAM(hdc);
        ORBIT_TRACK_PARAM(xDst);
        ORBIT_TRACK_PARAM(yDst);
        ORBIT_TRACK_PARAM(dxDst);
        ORBIT_TRACK_PARAM(dyDst);
        ORBIT_TRACK_PARAM(lpbi);
        ORBIT_TRACK_PARAM(lpBits);
        ORBIT_TRACK_PARAM(xSrc);
        ORBIT_TRACK_PARAM(ySrc);
        ORBIT_TRACK_PARAM(dxSrc);
        ORBIT_TRACK_PARAM(dySrc);
        ORBIT_TRACK_PARAM(wFlags);

        auto win32_impl_result = g_api_table.DrawDibDraw(hdd, hdc, xDst, yDst, dxDst, dyDst, lpbi, lpBits, xSrc, ySrc, dxSrc, dySrc, wFlags);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_DrawDibEnd(intptr_t hdd) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hdd);

        auto win32_impl_result = g_api_table.DrawDibEnd(hdd);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_DrawDibTime(intptr_t hdd, win32::Windows::Win32::Media::Multimedia::DRAWDIBTIME* lpddtime) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hdd);
        ORBIT_TRACK_PARAM(lpddtime);

        auto win32_impl_result = g_api_table.DrawDibTime(hdd, lpddtime);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::LRESULT __stdcall ORBIT_IMPL_DrawDibProfileDisplay(win32::Windows::Win32::Graphics::Gdi::BITMAPINFOHEADER* lpbi) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(lpbi);

        auto win32_impl_result = g_api_table.DrawDibProfileDisplay(lpbi);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    void __stdcall ORBIT_IMPL_AVIFileInit() noexcept
    {
        ORBIT_SCOPE_FUNCTION();

        g_api_table.AVIFileInit();
        
    }

    void __stdcall ORBIT_IMPL_AVIFileExit() noexcept
    {
        ORBIT_SCOPE_FUNCTION();

        g_api_table.AVIFileExit();
        
    }

    uint32_t __stdcall ORBIT_IMPL_AVIFileAddRef(win32::Windows::Win32::Media::Multimedia::IAVIFile* pfile) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pfile);

        auto win32_impl_result = g_api_table.AVIFileAddRef(pfile);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_AVIFileRelease(win32::Windows::Win32::Media::Multimedia::IAVIFile* pfile) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pfile);

        auto win32_impl_result = g_api_table.AVIFileRelease(pfile);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIFileOpenA(win32::Windows::Win32::Media::Multimedia::IAVIFile** ppfile, win32::Windows::Win32::Foundation::PSTR szFile, uint32_t uMode, ::win32::guid* lpHandler) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(ppfile);
        ORBIT_TRACK_PARAM(szFile);
        ORBIT_TRACK_PARAM(uMode);
        ORBIT_TRACK_PARAM(lpHandler);

        auto win32_impl_result = g_api_table.AVIFileOpenA(ppfile, szFile, uMode, lpHandler);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIFileOpenW(win32::Windows::Win32::Media::Multimedia::IAVIFile** ppfile, win32::Windows::Win32::Foundation::PWSTR szFile, uint32_t uMode, ::win32::guid* lpHandler) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(ppfile);
        ORBIT_TRACK_PARAM(szFile);
        ORBIT_TRACK_PARAM(uMode);
        ORBIT_TRACK_PARAM(lpHandler);

        auto win32_impl_result = g_api_table.AVIFileOpenW(ppfile, szFile, uMode, lpHandler);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIFileInfoW(win32::Windows::Win32::Media::Multimedia::IAVIFile* pfile, win32::Windows::Win32::Media::Multimedia::AVIFILEINFOW* pfi, int32_t lSize) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pfile);
        ORBIT_TRACK_PARAM(pfi);
        ORBIT_TRACK_PARAM(lSize);

        auto win32_impl_result = g_api_table.AVIFileInfoW(pfile, pfi, lSize);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIFileInfoA(win32::Windows::Win32::Media::Multimedia::IAVIFile* pfile, win32::Windows::Win32::Media::Multimedia::AVIFILEINFOA* pfi, int32_t lSize) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pfile);
        ORBIT_TRACK_PARAM(pfi);
        ORBIT_TRACK_PARAM(lSize);

        auto win32_impl_result = g_api_table.AVIFileInfoA(pfile, pfi, lSize);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIFileGetStream(win32::Windows::Win32::Media::Multimedia::IAVIFile* pfile, win32::Windows::Win32::Media::Multimedia::IAVIStream** ppavi, uint32_t fccType, int32_t lParam) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pfile);
        ORBIT_TRACK_PARAM(ppavi);
        ORBIT_TRACK_PARAM(fccType);
        ORBIT_TRACK_PARAM(lParam);

        auto win32_impl_result = g_api_table.AVIFileGetStream(pfile, ppavi, fccType, lParam);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIFileCreateStreamW(win32::Windows::Win32::Media::Multimedia::IAVIFile* pfile, win32::Windows::Win32::Media::Multimedia::IAVIStream** ppavi, win32::Windows::Win32::Media::Multimedia::AVISTREAMINFOW* psi) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pfile);
        ORBIT_TRACK_PARAM(ppavi);
        ORBIT_TRACK_PARAM(psi);

        auto win32_impl_result = g_api_table.AVIFileCreateStreamW(pfile, ppavi, psi);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIFileCreateStreamA(win32::Windows::Win32::Media::Multimedia::IAVIFile* pfile, win32::Windows::Win32::Media::Multimedia::IAVIStream** ppavi, win32::Windows::Win32::Media::Multimedia::AVISTREAMINFOA* psi) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pfile);
        ORBIT_TRACK_PARAM(ppavi);
        ORBIT_TRACK_PARAM(psi);

        auto win32_impl_result = g_api_table.AVIFileCreateStreamA(pfile, ppavi, psi);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIFileWriteData(win32::Windows::Win32::Media::Multimedia::IAVIFile* pfile, uint32_t ckid, void* lpData, int32_t cbData) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pfile);
        ORBIT_TRACK_PARAM(ckid);
        ORBIT_TRACK_PARAM(lpData);
        ORBIT_TRACK_PARAM(cbData);

        auto win32_impl_result = g_api_table.AVIFileWriteData(pfile, ckid, lpData, cbData);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIFileReadData(win32::Windows::Win32::Media::Multimedia::IAVIFile* pfile, uint32_t ckid, void* lpData, int32_t* lpcbData) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pfile);
        ORBIT_TRACK_PARAM(ckid);
        ORBIT_TRACK_PARAM(lpData);
        ORBIT_TRACK_PARAM(lpcbData);

        auto win32_impl_result = g_api_table.AVIFileReadData(pfile, ckid, lpData, lpcbData);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIFileEndRecord(win32::Windows::Win32::Media::Multimedia::IAVIFile* pfile) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pfile);

        auto win32_impl_result = g_api_table.AVIFileEndRecord(pfile);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_AVIStreamAddRef(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);

        auto win32_impl_result = g_api_table.AVIStreamAddRef(pavi);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_AVIStreamRelease(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);

        auto win32_impl_result = g_api_table.AVIStreamRelease(pavi);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIStreamInfoW(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, win32::Windows::Win32::Media::Multimedia::AVISTREAMINFOW* psi, int32_t lSize) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(psi);
        ORBIT_TRACK_PARAM(lSize);

        auto win32_impl_result = g_api_table.AVIStreamInfoW(pavi, psi, lSize);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIStreamInfoA(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, win32::Windows::Win32::Media::Multimedia::AVISTREAMINFOA* psi, int32_t lSize) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(psi);
        ORBIT_TRACK_PARAM(lSize);

        auto win32_impl_result = g_api_table.AVIStreamInfoA(pavi, psi, lSize);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    int32_t __stdcall ORBIT_IMPL_AVIStreamFindSample(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, int32_t lPos, int32_t lFlags) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(lPos);
        ORBIT_TRACK_PARAM(lFlags);

        auto win32_impl_result = g_api_table.AVIStreamFindSample(pavi, lPos, lFlags);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIStreamReadFormat(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, int32_t lPos, void* lpFormat, int32_t* lpcbFormat) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(lPos);
        ORBIT_TRACK_PARAM(lpFormat);
        ORBIT_TRACK_PARAM(lpcbFormat);

        auto win32_impl_result = g_api_table.AVIStreamReadFormat(pavi, lPos, lpFormat, lpcbFormat);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIStreamSetFormat(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, int32_t lPos, void* lpFormat, int32_t cbFormat) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(lPos);
        ORBIT_TRACK_PARAM(lpFormat);
        ORBIT_TRACK_PARAM(cbFormat);

        auto win32_impl_result = g_api_table.AVIStreamSetFormat(pavi, lPos, lpFormat, cbFormat);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIStreamReadData(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, uint32_t fcc, void* lp, int32_t* lpcb) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(fcc);
        ORBIT_TRACK_PARAM(lp);
        ORBIT_TRACK_PARAM(lpcb);

        auto win32_impl_result = g_api_table.AVIStreamReadData(pavi, fcc, lp, lpcb);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIStreamWriteData(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, uint32_t fcc, void* lp, int32_t cb) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(fcc);
        ORBIT_TRACK_PARAM(lp);
        ORBIT_TRACK_PARAM(cb);

        auto win32_impl_result = g_api_table.AVIStreamWriteData(pavi, fcc, lp, cb);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIStreamRead(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, int32_t lStart, int32_t lSamples, void* lpBuffer, int32_t cbBuffer, int32_t* plBytes, int32_t* plSamples) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(lStart);
        ORBIT_TRACK_PARAM(lSamples);
        ORBIT_TRACK_PARAM(lpBuffer);
        ORBIT_TRACK_PARAM(cbBuffer);
        ORBIT_TRACK_PARAM(plBytes);
        ORBIT_TRACK_PARAM(plSamples);

        auto win32_impl_result = g_api_table.AVIStreamRead(pavi, lStart, lSamples, lpBuffer, cbBuffer, plBytes, plSamples);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIStreamWrite(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, int32_t lStart, int32_t lSamples, void* lpBuffer, int32_t cbBuffer, uint32_t dwFlags, int32_t* plSampWritten, int32_t* plBytesWritten) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(lStart);
        ORBIT_TRACK_PARAM(lSamples);
        ORBIT_TRACK_PARAM(lpBuffer);
        ORBIT_TRACK_PARAM(cbBuffer);
        ORBIT_TRACK_PARAM(dwFlags);
        ORBIT_TRACK_PARAM(plSampWritten);
        ORBIT_TRACK_PARAM(plBytesWritten);

        auto win32_impl_result = g_api_table.AVIStreamWrite(pavi, lStart, lSamples, lpBuffer, cbBuffer, dwFlags, plSampWritten, plBytesWritten);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    int32_t __stdcall ORBIT_IMPL_AVIStreamStart(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);

        auto win32_impl_result = g_api_table.AVIStreamStart(pavi);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    int32_t __stdcall ORBIT_IMPL_AVIStreamLength(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);

        auto win32_impl_result = g_api_table.AVIStreamLength(pavi);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    int32_t __stdcall ORBIT_IMPL_AVIStreamTimeToSample(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, int32_t lTime) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(lTime);

        auto win32_impl_result = g_api_table.AVIStreamTimeToSample(pavi, lTime);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    int32_t __stdcall ORBIT_IMPL_AVIStreamSampleToTime(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, int32_t lSample) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(lSample);

        auto win32_impl_result = g_api_table.AVIStreamSampleToTime(pavi, lSample);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIStreamBeginStreaming(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, int32_t lStart, int32_t lEnd, int32_t lRate) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(lStart);
        ORBIT_TRACK_PARAM(lEnd);
        ORBIT_TRACK_PARAM(lRate);

        auto win32_impl_result = g_api_table.AVIStreamBeginStreaming(pavi, lStart, lEnd, lRate);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIStreamEndStreaming(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);

        auto win32_impl_result = g_api_table.AVIStreamEndStreaming(pavi);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Media::Multimedia::IGetFrame* __stdcall ORBIT_IMPL_AVIStreamGetFrameOpen(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, win32::Windows::Win32::Graphics::Gdi::BITMAPINFOHEADER* lpbiWanted) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(lpbiWanted);

        auto win32_impl_result = g_api_table.AVIStreamGetFrameOpen(pavi, lpbiWanted);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    void* __stdcall ORBIT_IMPL_AVIStreamGetFrame(win32::Windows::Win32::Media::Multimedia::IGetFrame* pg, int32_t lPos) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pg);
        ORBIT_TRACK_PARAM(lPos);

        auto win32_impl_result = g_api_table.AVIStreamGetFrame(pg, lPos);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIStreamGetFrameClose(win32::Windows::Win32::Media::Multimedia::IGetFrame* pg) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pg);

        auto win32_impl_result = g_api_table.AVIStreamGetFrameClose(pg);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIStreamOpenFromFileA(win32::Windows::Win32::Media::Multimedia::IAVIStream** ppavi, win32::Windows::Win32::Foundation::PSTR szFile, uint32_t fccType, int32_t lParam, uint32_t mode, ::win32::guid* pclsidHandler) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(ppavi);
        ORBIT_TRACK_PARAM(szFile);
        ORBIT_TRACK_PARAM(fccType);
        ORBIT_TRACK_PARAM(lParam);
        ORBIT_TRACK_PARAM(mode);
        ORBIT_TRACK_PARAM(pclsidHandler);

        auto win32_impl_result = g_api_table.AVIStreamOpenFromFileA(ppavi, szFile, fccType, lParam, mode, pclsidHandler);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIStreamOpenFromFileW(win32::Windows::Win32::Media::Multimedia::IAVIStream** ppavi, win32::Windows::Win32::Foundation::PWSTR szFile, uint32_t fccType, int32_t lParam, uint32_t mode, ::win32::guid* pclsidHandler) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(ppavi);
        ORBIT_TRACK_PARAM(szFile);
        ORBIT_TRACK_PARAM(fccType);
        ORBIT_TRACK_PARAM(lParam);
        ORBIT_TRACK_PARAM(mode);
        ORBIT_TRACK_PARAM(pclsidHandler);

        auto win32_impl_result = g_api_table.AVIStreamOpenFromFileW(ppavi, szFile, fccType, lParam, mode, pclsidHandler);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIStreamCreate(win32::Windows::Win32::Media::Multimedia::IAVIStream** ppavi, int32_t lParam1, int32_t lParam2, ::win32::guid* pclsidHandler) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(ppavi);
        ORBIT_TRACK_PARAM(lParam1);
        ORBIT_TRACK_PARAM(lParam2);
        ORBIT_TRACK_PARAM(pclsidHandler);

        auto win32_impl_result = g_api_table.AVIStreamCreate(ppavi, lParam1, lParam2, pclsidHandler);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIMakeCompressedStream(win32::Windows::Win32::Media::Multimedia::IAVIStream** ppsCompressed, win32::Windows::Win32::Media::Multimedia::IAVIStream* ppsSource, win32::Windows::Win32::Media::Multimedia::AVICOMPRESSOPTIONS* lpOptions, ::win32::guid* pclsidHandler) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(ppsCompressed);
        ORBIT_TRACK_PARAM(ppsSource);
        ORBIT_TRACK_PARAM(lpOptions);
        ORBIT_TRACK_PARAM(pclsidHandler);

        auto win32_impl_result = g_api_table.AVIMakeCompressedStream(ppsCompressed, ppsSource, lpOptions, pclsidHandler);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVISaveA(win32::Windows::Win32::Foundation::PSTR szFile, ::win32::guid* pclsidHandler, win32::Windows::Win32::Media::Multimedia::AVISAVECALLBACK* lpfnCallback, int32_t nStreams, win32::Windows::Win32::Media::Multimedia::IAVIStream* pfile, win32::Windows::Win32::Media::Multimedia::AVICOMPRESSOPTIONS* lpOptions) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(szFile);
        ORBIT_TRACK_PARAM(pclsidHandler);
        ORBIT_TRACK_PARAM(lpfnCallback);
        ORBIT_TRACK_PARAM(nStreams);
        ORBIT_TRACK_PARAM(pfile);
        ORBIT_TRACK_PARAM(lpOptions);

        auto win32_impl_result = g_api_table.AVISaveA(szFile, pclsidHandler, lpfnCallback, nStreams, pfile, lpOptions);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVISaveVA(win32::Windows::Win32::Foundation::PSTR szFile, ::win32::guid* pclsidHandler, win32::Windows::Win32::Media::Multimedia::AVISAVECALLBACK* lpfnCallback, int32_t nStreams, win32::Windows::Win32::Media::Multimedia::IAVIStream** ppavi, win32::Windows::Win32::Media::Multimedia::AVICOMPRESSOPTIONS** plpOptions) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(szFile);
        ORBIT_TRACK_PARAM(pclsidHandler);
        ORBIT_TRACK_PARAM(lpfnCallback);
        ORBIT_TRACK_PARAM(nStreams);
        ORBIT_TRACK_PARAM(ppavi);
        ORBIT_TRACK_PARAM(plpOptions);

        auto win32_impl_result = g_api_table.AVISaveVA(szFile, pclsidHandler, lpfnCallback, nStreams, ppavi, plpOptions);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVISaveW(win32::Windows::Win32::Foundation::PWSTR szFile, ::win32::guid* pclsidHandler, win32::Windows::Win32::Media::Multimedia::AVISAVECALLBACK* lpfnCallback, int32_t nStreams, win32::Windows::Win32::Media::Multimedia::IAVIStream* pfile, win32::Windows::Win32::Media::Multimedia::AVICOMPRESSOPTIONS* lpOptions) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(szFile);
        ORBIT_TRACK_PARAM(pclsidHandler);
        ORBIT_TRACK_PARAM(lpfnCallback);
        ORBIT_TRACK_PARAM(nStreams);
        ORBIT_TRACK_PARAM(pfile);
        ORBIT_TRACK_PARAM(lpOptions);

        auto win32_impl_result = g_api_table.AVISaveW(szFile, pclsidHandler, lpfnCallback, nStreams, pfile, lpOptions);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVISaveVW(win32::Windows::Win32::Foundation::PWSTR szFile, ::win32::guid* pclsidHandler, win32::Windows::Win32::Media::Multimedia::AVISAVECALLBACK* lpfnCallback, int32_t nStreams, win32::Windows::Win32::Media::Multimedia::IAVIStream** ppavi, win32::Windows::Win32::Media::Multimedia::AVICOMPRESSOPTIONS** plpOptions) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(szFile);
        ORBIT_TRACK_PARAM(pclsidHandler);
        ORBIT_TRACK_PARAM(lpfnCallback);
        ORBIT_TRACK_PARAM(nStreams);
        ORBIT_TRACK_PARAM(ppavi);
        ORBIT_TRACK_PARAM(plpOptions);

        auto win32_impl_result = g_api_table.AVISaveVW(szFile, pclsidHandler, lpfnCallback, nStreams, ppavi, plpOptions);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    intptr_t __stdcall ORBIT_IMPL_AVISaveOptions(win32::Windows::Win32::Foundation::HWND hwnd, uint32_t uiFlags, int32_t nStreams, win32::Windows::Win32::Media::Multimedia::IAVIStream** ppavi, win32::Windows::Win32::Media::Multimedia::AVICOMPRESSOPTIONS** plpOptions) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hwnd);
        ORBIT_TRACK_PARAM(uiFlags);
        ORBIT_TRACK_PARAM(nStreams);
        ORBIT_TRACK_PARAM(ppavi);
        ORBIT_TRACK_PARAM(plpOptions);

        auto win32_impl_result = g_api_table.AVISaveOptions(hwnd, uiFlags, nStreams, ppavi, plpOptions);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVISaveOptionsFree(int32_t nStreams, win32::Windows::Win32::Media::Multimedia::AVICOMPRESSOPTIONS** plpOptions) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(nStreams);
        ORBIT_TRACK_PARAM(plpOptions);

        auto win32_impl_result = g_api_table.AVISaveOptionsFree(nStreams, plpOptions);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIBuildFilterW(win32::Windows::Win32::Foundation::PWSTR lpszFilter, int32_t cbFilter, win32::Windows::Win32::Foundation::BOOL fSaving) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(lpszFilter);
        ORBIT_TRACK_PARAM(cbFilter);
        ORBIT_TRACK_PARAM(fSaving);

        auto win32_impl_result = g_api_table.AVIBuildFilterW(lpszFilter, cbFilter, fSaving);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIBuildFilterA(win32::Windows::Win32::Foundation::PSTR lpszFilter, int32_t cbFilter, win32::Windows::Win32::Foundation::BOOL fSaving) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(lpszFilter);
        ORBIT_TRACK_PARAM(cbFilter);
        ORBIT_TRACK_PARAM(fSaving);

        auto win32_impl_result = g_api_table.AVIBuildFilterA(lpszFilter, cbFilter, fSaving);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIMakeFileFromStreams(win32::Windows::Win32::Media::Multimedia::IAVIFile** ppfile, int32_t nStreams, win32::Windows::Win32::Media::Multimedia::IAVIStream** papStreams) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(ppfile);
        ORBIT_TRACK_PARAM(nStreams);
        ORBIT_TRACK_PARAM(papStreams);

        auto win32_impl_result = g_api_table.AVIMakeFileFromStreams(ppfile, nStreams, papStreams);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIMakeStreamFromClipboard(uint32_t cfFormat, win32::Windows::Win32::Foundation::HANDLE hGlobal, win32::Windows::Win32::Media::Multimedia::IAVIStream** ppstream) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(cfFormat);
        ORBIT_TRACK_PARAM(hGlobal);
        ORBIT_TRACK_PARAM(ppstream);

        auto win32_impl_result = g_api_table.AVIMakeStreamFromClipboard(cfFormat, hGlobal, ppstream);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIPutFileOnClipboard(win32::Windows::Win32::Media::Multimedia::IAVIFile* pf) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pf);

        auto win32_impl_result = g_api_table.AVIPutFileOnClipboard(pf);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIGetFromClipboard(win32::Windows::Win32::Media::Multimedia::IAVIFile** lppf) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(lppf);

        auto win32_impl_result = g_api_table.AVIGetFromClipboard(lppf);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_AVIClearClipboard() noexcept
    {
        ORBIT_SCOPE_FUNCTION();

        auto win32_impl_result = g_api_table.AVIClearClipboard();
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_CreateEditableStream(win32::Windows::Win32::Media::Multimedia::IAVIStream** ppsEditable, win32::Windows::Win32::Media::Multimedia::IAVIStream* psSource) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(ppsEditable);
        ORBIT_TRACK_PARAM(psSource);

        auto win32_impl_result = g_api_table.CreateEditableStream(ppsEditable, psSource);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_EditStreamCut(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, int32_t* plStart, int32_t* plLength, win32::Windows::Win32::Media::Multimedia::IAVIStream** ppResult) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(plStart);
        ORBIT_TRACK_PARAM(plLength);
        ORBIT_TRACK_PARAM(ppResult);

        auto win32_impl_result = g_api_table.EditStreamCut(pavi, plStart, plLength, ppResult);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_EditStreamCopy(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, int32_t* plStart, int32_t* plLength, win32::Windows::Win32::Media::Multimedia::IAVIStream** ppResult) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(plStart);
        ORBIT_TRACK_PARAM(plLength);
        ORBIT_TRACK_PARAM(ppResult);

        auto win32_impl_result = g_api_table.EditStreamCopy(pavi, plStart, plLength, ppResult);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_EditStreamPaste(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, int32_t* plPos, int32_t* plLength, win32::Windows::Win32::Media::Multimedia::IAVIStream* pstream, int32_t lStart, int32_t lEnd) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(plPos);
        ORBIT_TRACK_PARAM(plLength);
        ORBIT_TRACK_PARAM(pstream);
        ORBIT_TRACK_PARAM(lStart);
        ORBIT_TRACK_PARAM(lEnd);

        auto win32_impl_result = g_api_table.EditStreamPaste(pavi, plPos, plLength, pstream, lStart, lEnd);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_EditStreamClone(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, win32::Windows::Win32::Media::Multimedia::IAVIStream** ppResult) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(ppResult);

        auto win32_impl_result = g_api_table.EditStreamClone(pavi, ppResult);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_EditStreamSetNameA(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, win32::Windows::Win32::Foundation::PSTR lpszName) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(lpszName);

        auto win32_impl_result = g_api_table.EditStreamSetNameA(pavi, lpszName);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_EditStreamSetNameW(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, win32::Windows::Win32::Foundation::PWSTR lpszName) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(lpszName);

        auto win32_impl_result = g_api_table.EditStreamSetNameW(pavi, lpszName);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_EditStreamSetInfoW(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, win32::Windows::Win32::Media::Multimedia::AVISTREAMINFOW* lpInfo, int32_t cbInfo) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(lpInfo);
        ORBIT_TRACK_PARAM(cbInfo);

        auto win32_impl_result = g_api_table.EditStreamSetInfoW(pavi, lpInfo, cbInfo);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_EditStreamSetInfoA(win32::Windows::Win32::Media::Multimedia::IAVIStream* pavi, win32::Windows::Win32::Media::Multimedia::AVISTREAMINFOA* lpInfo, int32_t cbInfo) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(pavi);
        ORBIT_TRACK_PARAM(lpInfo);
        ORBIT_TRACK_PARAM(cbInfo);

        auto win32_impl_result = g_api_table.EditStreamSetInfoA(pavi, lpInfo, cbInfo);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HWND __stdcall ORBIT_IMPL_MCIWndCreateA(win32::Windows::Win32::Foundation::HWND hwndParent, win32::Windows::Win32::Foundation::HINSTANCE hInstance, uint32_t dwStyle, win32::Windows::Win32::Foundation::PSTR szFile) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hwndParent);
        ORBIT_TRACK_PARAM(hInstance);
        ORBIT_TRACK_PARAM(dwStyle);
        ORBIT_TRACK_PARAM(szFile);

        auto win32_impl_result = g_api_table.MCIWndCreateA(hwndParent, hInstance, dwStyle, szFile);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HWND __stdcall ORBIT_IMPL_MCIWndCreateW(win32::Windows::Win32::Foundation::HWND hwndParent, win32::Windows::Win32::Foundation::HINSTANCE hInstance, uint32_t dwStyle, win32::Windows::Win32::Foundation::PWSTR szFile) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(hwndParent);
        ORBIT_TRACK_PARAM(hInstance);
        ORBIT_TRACK_PARAM(dwStyle);
        ORBIT_TRACK_PARAM(szFile);

        auto win32_impl_result = g_api_table.MCIWndCreateW(hwndParent, hInstance, dwStyle, szFile);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_MCIWndRegisterClass() noexcept
    {
        ORBIT_SCOPE_FUNCTION();

        auto win32_impl_result = g_api_table.MCIWndRegisterClass();
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HWND __stdcall ORBIT_IMPL_capCreateCaptureWindowA(win32::Windows::Win32::Foundation::PSTR lpszWindowName, uint32_t dwStyle, int32_t x, int32_t y, int32_t nWidth, int32_t nHeight, win32::Windows::Win32::Foundation::HWND hwndParent, int32_t nID) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(lpszWindowName);
        ORBIT_TRACK_PARAM(dwStyle);
        ORBIT_TRACK_PARAM(x);
        ORBIT_TRACK_PARAM(y);
        ORBIT_TRACK_PARAM(nWidth);
        ORBIT_TRACK_PARAM(nHeight);
        ORBIT_TRACK_PARAM(hwndParent);
        ORBIT_TRACK_PARAM(nID);

        auto win32_impl_result = g_api_table.capCreateCaptureWindowA(lpszWindowName, dwStyle, x, y, nWidth, nHeight, hwndParent, nID);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_capGetDriverDescriptionA(uint32_t wDriverIndex, win32::Windows::Win32::Foundation::PSTR lpszName, int32_t cbName, win32::Windows::Win32::Foundation::PSTR lpszVer, int32_t cbVer) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(wDriverIndex);
        ORBIT_TRACK_PARAM(lpszName);
        ORBIT_TRACK_PARAM(cbName);
        ORBIT_TRACK_PARAM(lpszVer);
        ORBIT_TRACK_PARAM(cbVer);

        auto win32_impl_result = g_api_table.capGetDriverDescriptionA(wDriverIndex, lpszName, cbName, lpszVer, cbVer);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::HWND __stdcall ORBIT_IMPL_capCreateCaptureWindowW(win32::Windows::Win32::Foundation::PWSTR lpszWindowName, uint32_t dwStyle, int32_t x, int32_t y, int32_t nWidth, int32_t nHeight, win32::Windows::Win32::Foundation::HWND hwndParent, int32_t nID) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(lpszWindowName);
        ORBIT_TRACK_PARAM(dwStyle);
        ORBIT_TRACK_PARAM(x);
        ORBIT_TRACK_PARAM(y);
        ORBIT_TRACK_PARAM(nWidth);
        ORBIT_TRACK_PARAM(nHeight);
        ORBIT_TRACK_PARAM(hwndParent);
        ORBIT_TRACK_PARAM(nID);

        auto win32_impl_result = g_api_table.capCreateCaptureWindowW(lpszWindowName, dwStyle, x, y, nWidth, nHeight, hwndParent, nID);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_capGetDriverDescriptionW(uint32_t wDriverIndex, win32::Windows::Win32::Foundation::PWSTR lpszName, int32_t cbName, win32::Windows::Win32::Foundation::PWSTR lpszVer, int32_t cbVer) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(wDriverIndex);
        ORBIT_TRACK_PARAM(lpszName);
        ORBIT_TRACK_PARAM(cbName);
        ORBIT_TRACK_PARAM(lpszVer);
        ORBIT_TRACK_PARAM(cbVer);

        auto win32_impl_result = g_api_table.capGetDriverDescriptionW(wDriverIndex, lpszName, cbName, lpszVer, cbVer);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_GetOpenFileNamePreviewA(win32::Windows::Win32::UI::Controls::Dialogs::OPENFILENAMEA* lpofn) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(lpofn);

        auto win32_impl_result = g_api_table.GetOpenFileNamePreviewA(lpofn);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_GetSaveFileNamePreviewA(win32::Windows::Win32::UI::Controls::Dialogs::OPENFILENAMEA* lpofn) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(lpofn);

        auto win32_impl_result = g_api_table.GetSaveFileNamePreviewA(lpofn);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_GetOpenFileNamePreviewW(win32::Windows::Win32::UI::Controls::Dialogs::OPENFILENAMEW* lpofn) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(lpofn);

        auto win32_impl_result = g_api_table.GetOpenFileNamePreviewW(lpofn);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_GetSaveFileNamePreviewW(win32::Windows::Win32::UI::Controls::Dialogs::OPENFILENAMEW* lpofn) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(lpofn);

        auto win32_impl_result = g_api_table.GetSaveFileNamePreviewW(lpofn);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    uint32_t __stdcall ORBIT_IMPL_mmTaskCreate(win32::Windows::Win32::Media::Multimedia::LPTASKCALLBACK* lpfn, win32::Windows::Win32::Foundation::HANDLE* lph, size_t dwInst) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(lpfn);
        ORBIT_TRACK_PARAM(lph);
        ORBIT_TRACK_PARAM(dwInst);

        auto win32_impl_result = g_api_table.mmTaskCreate(lpfn, lph, dwInst);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    void __stdcall ORBIT_IMPL_mmTaskBlock(uint32_t h) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(h);

        g_api_table.mmTaskBlock(h);
        
    }

    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_mmTaskSignal(uint32_t h) noexcept
    {
        ORBIT_SCOPE_FUNCTION();
        ORBIT_TRACK_PARAM(h);

        auto win32_impl_result = g_api_table.mmTaskSignal(h);
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

    void __stdcall ORBIT_IMPL_mmTaskYield() noexcept
    {
        ORBIT_SCOPE_FUNCTION();

        g_api_table.mmTaskYield();
        
    }

    uint32_t __stdcall ORBIT_IMPL_mmGetCurrentTask() noexcept
    {
        ORBIT_SCOPE_FUNCTION();

        auto win32_impl_result = g_api_table.mmGetCurrentTask();
        ORBIT_TRACK_RET(win32_impl_result);
        return win32_impl_result;
    }

}

#pragma endregion abi_methods

}
#endif
