// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_UI_Input_H
#define WIN32_Windows_Win32_UI_Input_H
#include "win32/base.h"
#include "win32/impl/complex_structs.h"
#include "win32/impl/complex_interfaces.h"
static_assert(win32::check_version(CPPWIN32_VERSION, "0.0.0.1"), "Mismatched C++/Win32 headers.");
#define CPPWIN32_VERSION "0.0.0.1"
#include "win32/impl/Windows.Win32.UI.Input.0.h"
WIN32_EXPORT namespace win32::Windows::Win32::UI::Input
{
#pragma region methods
extern "C"
{
    uint32_t __stdcall ORBIT_IMPL_GetRawInputData(win32::Windows::Win32::UI::Input::HRAWINPUT hRawInput, win32::Windows::Win32::UI::Input::RAW_INPUT_DATA_COMMAND_FLAGS uiCommand, void* pData, uint32_t* pcbSize, uint32_t cbSizeHeader) noexcept;
    uint32_t __stdcall ORBIT_IMPL_GetRawInputDeviceInfoA(win32::Windows::Win32::Foundation::HANDLE hDevice, win32::Windows::Win32::UI::Input::RAW_INPUT_DEVICE_INFO_COMMAND uiCommand, void* pData, uint32_t* pcbSize) noexcept;
    uint32_t __stdcall ORBIT_IMPL_GetRawInputDeviceInfoW(win32::Windows::Win32::Foundation::HANDLE hDevice, win32::Windows::Win32::UI::Input::RAW_INPUT_DEVICE_INFO_COMMAND uiCommand, void* pData, uint32_t* pcbSize) noexcept;
    uint32_t __stdcall ORBIT_IMPL_GetRawInputBuffer(win32::Windows::Win32::UI::Input::RAWINPUT* pData, uint32_t* pcbSize, uint32_t cbSizeHeader) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_RegisterRawInputDevices(win32::Windows::Win32::UI::Input::RAWINPUTDEVICE* pRawInputDevices, uint32_t uiNumDevices, uint32_t cbSize) noexcept;
    uint32_t __stdcall ORBIT_IMPL_GetRegisteredRawInputDevices(win32::Windows::Win32::UI::Input::RAWINPUTDEVICE* pRawInputDevices, uint32_t* puiNumDevices, uint32_t cbSize) noexcept;
    uint32_t __stdcall ORBIT_IMPL_GetRawInputDeviceList(win32::Windows::Win32::UI::Input::RAWINPUTDEVICELIST* pRawInputDeviceList, uint32_t* puiNumDevices, uint32_t cbSize) noexcept;
    win32::Windows::Win32::Foundation::LRESULT __stdcall ORBIT_IMPL_DefRawInputProc(win32::Windows::Win32::UI::Input::RAWINPUT** paRawInput, int32_t nInput, uint32_t cbSizeHeader) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_GetCurrentInputMessageSource(win32::Windows::Win32::UI::Input::INPUT_MESSAGE_SOURCE* inputMessageSource) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_GetCIMSSM(win32::Windows::Win32::UI::Input::INPUT_MESSAGE_SOURCE* inputMessageSource) noexcept;
}

struct ApiTable {
    uint32_t (__stdcall *GetRawInputData)(win32::Windows::Win32::UI::Input::HRAWINPUT hRawInput, win32::Windows::Win32::UI::Input::RAW_INPUT_DATA_COMMAND_FLAGS uiCommand, void* pData, uint32_t* pcbSize, uint32_t cbSizeHeader) noexcept;
    uint32_t (__stdcall *GetRawInputDeviceInfoA)(win32::Windows::Win32::Foundation::HANDLE hDevice, win32::Windows::Win32::UI::Input::RAW_INPUT_DEVICE_INFO_COMMAND uiCommand, void* pData, uint32_t* pcbSize) noexcept;
    uint32_t (__stdcall *GetRawInputDeviceInfoW)(win32::Windows::Win32::Foundation::HANDLE hDevice, win32::Windows::Win32::UI::Input::RAW_INPUT_DEVICE_INFO_COMMAND uiCommand, void* pData, uint32_t* pcbSize) noexcept;
    uint32_t (__stdcall *GetRawInputBuffer)(win32::Windows::Win32::UI::Input::RAWINPUT* pData, uint32_t* pcbSize, uint32_t cbSizeHeader) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *RegisterRawInputDevices)(win32::Windows::Win32::UI::Input::RAWINPUTDEVICE* pRawInputDevices, uint32_t uiNumDevices, uint32_t cbSize) noexcept;
    uint32_t (__stdcall *GetRegisteredRawInputDevices)(win32::Windows::Win32::UI::Input::RAWINPUTDEVICE* pRawInputDevices, uint32_t* puiNumDevices, uint32_t cbSize) noexcept;
    uint32_t (__stdcall *GetRawInputDeviceList)(win32::Windows::Win32::UI::Input::RAWINPUTDEVICELIST* pRawInputDeviceList, uint32_t* puiNumDevices, uint32_t cbSize) noexcept;
    win32::Windows::Win32::Foundation::LRESULT (__stdcall *DefRawInputProc)(win32::Windows::Win32::UI::Input::RAWINPUT** paRawInput, int32_t nInput, uint32_t cbSizeHeader) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *GetCurrentInputMessageSource)(win32::Windows::Win32::UI::Input::INPUT_MESSAGE_SOURCE* inputMessageSource) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *GetCIMSSM)(win32::Windows::Win32::UI::Input::INPUT_MESSAGE_SOURCE* inputMessageSource) noexcept;
};
extern ApiTable g_api_table;

#pragma endregion methods

}
#endif
