// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_Web_MsHtml_H
#define WIN32_Windows_Win32_Web_MsHtml_H
#include "win32/base.h"
#include "win32/impl/complex_structs.h"
#include "win32/impl/complex_interfaces.h"
static_assert(win32::check_version(CPPWIN32_VERSION, "0.0.0.1"), "Mismatched C++/Win32 headers.");
#define CPPWIN32_VERSION "0.0.0.1"
#include "win32/impl/Windows.Win32.Web.MsHtml.0.h"
WIN32_EXPORT namespace win32::Windows::Win32::Web::MsHtml
{
#pragma region methods
extern "C"
{
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_RatingEnable(win32::Windows::Win32::Foundation::HWND hwndParent, win32::Windows::Win32::Foundation::PSTR pszUsername, win32::Windows::Win32::Foundation::BOOL fEnable) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_RatingEnableW(win32::Windows::Win32::Foundation::HWND hwndParent, win32::Windows::Win32::Foundation::PWSTR pszUsername, win32::Windows::Win32::Foundation::BOOL fEnable) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_RatingCheckUserAccess(win32::Windows::Win32::Foundation::PSTR pszUsername, win32::Windows::Win32::Foundation::PSTR pszURL, win32::Windows::Win32::Foundation::PSTR pszRatingInfo, uint8_t* pData, uint32_t cbData, void** ppRatingDetails) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_RatingCheckUserAccessW(win32::Windows::Win32::Foundation::PWSTR pszUsername, win32::Windows::Win32::Foundation::PWSTR pszURL, win32::Windows::Win32::Foundation::PWSTR pszRatingInfo, uint8_t* pData, uint32_t cbData, void** ppRatingDetails) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_RatingAccessDeniedDialog(win32::Windows::Win32::Foundation::HWND hDlg, win32::Windows::Win32::Foundation::PSTR pszUsername, win32::Windows::Win32::Foundation::PSTR pszContentDescription, void* pRatingDetails) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_RatingAccessDeniedDialogW(win32::Windows::Win32::Foundation::HWND hDlg, win32::Windows::Win32::Foundation::PWSTR pszUsername, win32::Windows::Win32::Foundation::PWSTR pszContentDescription, void* pRatingDetails) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_RatingAccessDeniedDialog2(win32::Windows::Win32::Foundation::HWND hDlg, win32::Windows::Win32::Foundation::PSTR pszUsername, void* pRatingDetails) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_RatingAccessDeniedDialog2W(win32::Windows::Win32::Foundation::HWND hDlg, win32::Windows::Win32::Foundation::PWSTR pszUsername, void* pRatingDetails) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_RatingFreeDetails(void* pRatingDetails) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_RatingObtainCancel(win32::Windows::Win32::Foundation::HANDLE hRatingObtainQuery) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_RatingObtainQuery(win32::Windows::Win32::Foundation::PSTR pszTargetUrl, uint32_t dwUserData, intptr_t fCallback, win32::Windows::Win32::Foundation::HANDLE* phRatingObtainQuery) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_RatingObtainQueryW(win32::Windows::Win32::Foundation::PWSTR pszTargetUrl, uint32_t dwUserData, intptr_t fCallback, win32::Windows::Win32::Foundation::HANDLE* phRatingObtainQuery) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_RatingSetupUI(win32::Windows::Win32::Foundation::HWND hDlg, win32::Windows::Win32::Foundation::PSTR pszUsername) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_RatingSetupUIW(win32::Windows::Win32::Foundation::HWND hDlg, win32::Windows::Win32::Foundation::PWSTR pszUsername) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_RatingAddToApprovedSites(win32::Windows::Win32::Foundation::HWND hDlg, uint32_t cbPasswordBlob, uint8_t* pbPasswordBlob, win32::Windows::Win32::Foundation::PWSTR lpszUrl, win32::Windows::Win32::Foundation::BOOL fAlwaysNever, win32::Windows::Win32::Foundation::BOOL fSitePage, win32::Windows::Win32::Foundation::BOOL fApprovedSitesEnforced) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_RatingClickedOnPRFInternal(win32::Windows::Win32::Foundation::HWND hWndOwner, win32::Windows::Win32::Foundation::HINSTANCE param1, win32::Windows::Win32::Foundation::PSTR lpszFileName, int32_t nShow) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_RatingClickedOnRATInternal(win32::Windows::Win32::Foundation::HWND hWndOwner, win32::Windows::Win32::Foundation::HINSTANCE param1, win32::Windows::Win32::Foundation::PSTR lpszFileName, int32_t nShow) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_RatingEnabledQuery() noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_RatingInit() noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_CreateMIMEMap(win32::Windows::Win32::Web::MsHtml::IMapMIMEToCLSID** ppMap) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_DecodeImage(win32::Windows::Win32::System::Com::IStream* pStream, win32::Windows::Win32::Web::MsHtml::IMapMIMEToCLSID* pMap, win32::Windows::Win32::System::Com::IUnknown* pEventSink) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_SniffStream(win32::Windows::Win32::System::Com::IStream* pInStream, uint32_t* pnFormat, win32::Windows::Win32::System::Com::IStream** ppOutStream) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_GetMaxMIMEIDBytes(uint32_t* pnMaxBytes) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_IdentifyMIMEType(uint8_t* pbBytes, uint32_t nBytes, uint32_t* pnFormat) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_ComputeInvCMAP(win32::Windows::Win32::Graphics::Gdi::RGBQUAD* pRGBColors, uint32_t nColors, uint8_t* pInvTable, uint32_t cbTable) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_DitherTo8(uint8_t* pDestBits, int32_t nDestPitch, uint8_t* pSrcBits, int32_t nSrcPitch, ::win32::guid* bfidSrc, win32::Windows::Win32::Graphics::Gdi::RGBQUAD* prgbDestColors, win32::Windows::Win32::Graphics::Gdi::RGBQUAD* prgbSrcColors, uint8_t* pbDestInvMap, int32_t x, int32_t y, int32_t cx, int32_t cy, int32_t lDestTrans, int32_t lSrcTrans) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_CreateDDrawSurfaceOnDIB(win32::Windows::Win32::Graphics::Gdi::HBITMAP hbmDib, win32::Windows::Win32::Graphics::DirectDraw::IDirectDrawSurface** ppSurface) noexcept;
    win32::Windows::Win32::Foundation::HRESULT __stdcall ORBIT_IMPL_DecodeImageEx(win32::Windows::Win32::System::Com::IStream* pStream, win32::Windows::Win32::Web::MsHtml::IMapMIMEToCLSID* pMap, win32::Windows::Win32::System::Com::IUnknown* pEventSink, win32::Windows::Win32::Foundation::PWSTR pszMIMETypeParam) noexcept;
}

struct ApiTable {
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *RatingEnable)(win32::Windows::Win32::Foundation::HWND hwndParent, win32::Windows::Win32::Foundation::PSTR pszUsername, win32::Windows::Win32::Foundation::BOOL fEnable) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *RatingEnableW)(win32::Windows::Win32::Foundation::HWND hwndParent, win32::Windows::Win32::Foundation::PWSTR pszUsername, win32::Windows::Win32::Foundation::BOOL fEnable) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *RatingCheckUserAccess)(win32::Windows::Win32::Foundation::PSTR pszUsername, win32::Windows::Win32::Foundation::PSTR pszURL, win32::Windows::Win32::Foundation::PSTR pszRatingInfo, uint8_t* pData, uint32_t cbData, void** ppRatingDetails) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *RatingCheckUserAccessW)(win32::Windows::Win32::Foundation::PWSTR pszUsername, win32::Windows::Win32::Foundation::PWSTR pszURL, win32::Windows::Win32::Foundation::PWSTR pszRatingInfo, uint8_t* pData, uint32_t cbData, void** ppRatingDetails) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *RatingAccessDeniedDialog)(win32::Windows::Win32::Foundation::HWND hDlg, win32::Windows::Win32::Foundation::PSTR pszUsername, win32::Windows::Win32::Foundation::PSTR pszContentDescription, void* pRatingDetails) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *RatingAccessDeniedDialogW)(win32::Windows::Win32::Foundation::HWND hDlg, win32::Windows::Win32::Foundation::PWSTR pszUsername, win32::Windows::Win32::Foundation::PWSTR pszContentDescription, void* pRatingDetails) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *RatingAccessDeniedDialog2)(win32::Windows::Win32::Foundation::HWND hDlg, win32::Windows::Win32::Foundation::PSTR pszUsername, void* pRatingDetails) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *RatingAccessDeniedDialog2W)(win32::Windows::Win32::Foundation::HWND hDlg, win32::Windows::Win32::Foundation::PWSTR pszUsername, void* pRatingDetails) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *RatingFreeDetails)(void* pRatingDetails) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *RatingObtainCancel)(win32::Windows::Win32::Foundation::HANDLE hRatingObtainQuery) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *RatingObtainQuery)(win32::Windows::Win32::Foundation::PSTR pszTargetUrl, uint32_t dwUserData, intptr_t fCallback, win32::Windows::Win32::Foundation::HANDLE* phRatingObtainQuery) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *RatingObtainQueryW)(win32::Windows::Win32::Foundation::PWSTR pszTargetUrl, uint32_t dwUserData, intptr_t fCallback, win32::Windows::Win32::Foundation::HANDLE* phRatingObtainQuery) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *RatingSetupUI)(win32::Windows::Win32::Foundation::HWND hDlg, win32::Windows::Win32::Foundation::PSTR pszUsername) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *RatingSetupUIW)(win32::Windows::Win32::Foundation::HWND hDlg, win32::Windows::Win32::Foundation::PWSTR pszUsername) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *RatingAddToApprovedSites)(win32::Windows::Win32::Foundation::HWND hDlg, uint32_t cbPasswordBlob, uint8_t* pbPasswordBlob, win32::Windows::Win32::Foundation::PWSTR lpszUrl, win32::Windows::Win32::Foundation::BOOL fAlwaysNever, win32::Windows::Win32::Foundation::BOOL fSitePage, win32::Windows::Win32::Foundation::BOOL fApprovedSitesEnforced) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *RatingClickedOnPRFInternal)(win32::Windows::Win32::Foundation::HWND hWndOwner, win32::Windows::Win32::Foundation::HINSTANCE param1, win32::Windows::Win32::Foundation::PSTR lpszFileName, int32_t nShow) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *RatingClickedOnRATInternal)(win32::Windows::Win32::Foundation::HWND hWndOwner, win32::Windows::Win32::Foundation::HINSTANCE param1, win32::Windows::Win32::Foundation::PSTR lpszFileName, int32_t nShow) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *RatingEnabledQuery)() noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *RatingInit)() noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *CreateMIMEMap)(win32::Windows::Win32::Web::MsHtml::IMapMIMEToCLSID** ppMap) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *DecodeImage)(win32::Windows::Win32::System::Com::IStream* pStream, win32::Windows::Win32::Web::MsHtml::IMapMIMEToCLSID* pMap, win32::Windows::Win32::System::Com::IUnknown* pEventSink) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *SniffStream)(win32::Windows::Win32::System::Com::IStream* pInStream, uint32_t* pnFormat, win32::Windows::Win32::System::Com::IStream** ppOutStream) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *GetMaxMIMEIDBytes)(uint32_t* pnMaxBytes) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *IdentifyMIMEType)(uint8_t* pbBytes, uint32_t nBytes, uint32_t* pnFormat) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *ComputeInvCMAP)(win32::Windows::Win32::Graphics::Gdi::RGBQUAD* pRGBColors, uint32_t nColors, uint8_t* pInvTable, uint32_t cbTable) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *DitherTo8)(uint8_t* pDestBits, int32_t nDestPitch, uint8_t* pSrcBits, int32_t nSrcPitch, ::win32::guid* bfidSrc, win32::Windows::Win32::Graphics::Gdi::RGBQUAD* prgbDestColors, win32::Windows::Win32::Graphics::Gdi::RGBQUAD* prgbSrcColors, uint8_t* pbDestInvMap, int32_t x, int32_t y, int32_t cx, int32_t cy, int32_t lDestTrans, int32_t lSrcTrans) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *CreateDDrawSurfaceOnDIB)(win32::Windows::Win32::Graphics::Gdi::HBITMAP hbmDib, win32::Windows::Win32::Graphics::DirectDraw::IDirectDrawSurface** ppSurface) noexcept;
    win32::Windows::Win32::Foundation::HRESULT (__stdcall *DecodeImageEx)(win32::Windows::Win32::System::Com::IStream* pStream, win32::Windows::Win32::Web::MsHtml::IMapMIMEToCLSID* pMap, win32::Windows::Win32::System::Com::IUnknown* pEventSink, win32::Windows::Win32::Foundation::PWSTR pszMIMETypeParam) noexcept;
};
extern ApiTable g_api_table;

#pragma endregion methods

}
#endif
