// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_System_Memory_H
#define WIN32_Windows_Win32_System_Memory_H
#include "win32/base.h"
#include "win32/impl/complex_structs.h"
#include "win32/impl/complex_interfaces.h"
static_assert(win32::check_version(CPPWIN32_VERSION, "0.0.0.1"), "Mismatched C++/Win32 headers.");
#define CPPWIN32_VERSION "0.0.0.1"
#include "win32/impl/Windows.Win32.System.Memory.0.h"
WIN32_EXPORT namespace win32::Windows::Win32::System::Memory
{
#pragma region methods
extern "C"
{
    win32::Windows::Win32::System::Memory::HeapHandle __stdcall ORBIT_IMPL_HeapCreate(win32::Windows::Win32::System::Memory::HEAP_FLAGS flOptions, size_t dwInitialSize, size_t dwMaximumSize) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_HeapDestroy(win32::Windows::Win32::System::Memory::HeapHandle hHeap) noexcept;
    void* __stdcall ORBIT_IMPL_HeapAlloc(win32::Windows::Win32::System::Memory::HeapHandle hHeap, win32::Windows::Win32::System::Memory::HEAP_FLAGS dwFlags, size_t dwBytes) noexcept;
    void* __stdcall ORBIT_IMPL_HeapReAlloc(win32::Windows::Win32::System::Memory::HeapHandle hHeap, win32::Windows::Win32::System::Memory::HEAP_FLAGS dwFlags, void* lpMem, size_t dwBytes) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_HeapFree(win32::Windows::Win32::System::Memory::HeapHandle hHeap, win32::Windows::Win32::System::Memory::HEAP_FLAGS dwFlags, void* lpMem) noexcept;
    size_t __stdcall ORBIT_IMPL_HeapSize(win32::Windows::Win32::System::Memory::HeapHandle hHeap, win32::Windows::Win32::System::Memory::HEAP_FLAGS dwFlags, void* lpMem) noexcept;
    win32::Windows::Win32::System::Memory::HeapHandle __stdcall ORBIT_IMPL_GetProcessHeap() noexcept;
    size_t __stdcall ORBIT_IMPL_HeapCompact(win32::Windows::Win32::System::Memory::HeapHandle hHeap, win32::Windows::Win32::System::Memory::HEAP_FLAGS dwFlags) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_HeapSetInformation(win32::Windows::Win32::System::Memory::HeapHandle HeapHandle, win32::Windows::Win32::System::SystemServices::HEAP_INFORMATION_CLASS HeapInformationClass, void* HeapInformation, size_t HeapInformationLength) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_HeapValidate(win32::Windows::Win32::System::Memory::HeapHandle hHeap, win32::Windows::Win32::System::Memory::HEAP_FLAGS dwFlags, void* lpMem) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_HeapSummary(win32::Windows::Win32::Foundation::HANDLE hHeap, uint32_t dwFlags, win32::Windows::Win32::System::Memory::HEAP_SUMMARY* lpSummary) noexcept;
    uint32_t __stdcall ORBIT_IMPL_GetProcessHeaps(uint32_t NumberOfHeaps, win32::Windows::Win32::System::Memory::HeapHandle* ProcessHeaps) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_HeapLock(win32::Windows::Win32::System::Memory::HeapHandle hHeap) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_HeapUnlock(win32::Windows::Win32::System::Memory::HeapHandle hHeap) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_HeapWalk(win32::Windows::Win32::System::Memory::HeapHandle hHeap, win32::Windows::Win32::System::SystemServices::PROCESS_HEAP_ENTRY* lpEntry) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_HeapQueryInformation(win32::Windows::Win32::System::Memory::HeapHandle HeapHandle, win32::Windows::Win32::System::SystemServices::HEAP_INFORMATION_CLASS HeapInformationClass, void* HeapInformation, size_t HeapInformationLength, size_t* ReturnLength) noexcept;
    void* __stdcall ORBIT_IMPL_VirtualAlloc(void* lpAddress, size_t dwSize, win32::Windows::Win32::System::Memory::VIRTUAL_ALLOCATION_TYPE flAllocationType, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS flProtect) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_VirtualProtect(void* lpAddress, size_t dwSize, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS flNewProtect, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS* lpflOldProtect) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_VirtualFree(void* lpAddress, size_t dwSize, win32::Windows::Win32::System::Memory::VIRTUAL_FREE_TYPE dwFreeType) noexcept;
    size_t __stdcall ORBIT_IMPL_VirtualQuery(void* lpAddress, win32::Windows::Win32::System::Memory::MEMORY_BASIC_INFORMATION* lpBuffer, size_t dwLength) noexcept;
    void* __stdcall ORBIT_IMPL_VirtualAllocEx(win32::Windows::Win32::Foundation::HANDLE hProcess, void* lpAddress, size_t dwSize, win32::Windows::Win32::System::Memory::VIRTUAL_ALLOCATION_TYPE flAllocationType, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS flProtect) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_VirtualProtectEx(win32::Windows::Win32::Foundation::HANDLE hProcess, void* lpAddress, size_t dwSize, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS flNewProtect, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS* lpflOldProtect) noexcept;
    size_t __stdcall ORBIT_IMPL_VirtualQueryEx(win32::Windows::Win32::Foundation::HANDLE hProcess, void* lpAddress, win32::Windows::Win32::System::Memory::MEMORY_BASIC_INFORMATION* lpBuffer, size_t dwLength) noexcept;
    win32::Windows::Win32::Foundation::HANDLE __stdcall ORBIT_IMPL_CreateFileMappingW(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Security::SECURITY_ATTRIBUTES* lpFileMappingAttributes, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS flProtect, uint32_t dwMaximumSizeHigh, uint32_t dwMaximumSizeLow, win32::Windows::Win32::Foundation::PWSTR lpName) noexcept;
    win32::Windows::Win32::Foundation::HANDLE __stdcall ORBIT_IMPL_OpenFileMappingW(uint32_t dwDesiredAccess, win32::Windows::Win32::Foundation::BOOL bInheritHandle, win32::Windows::Win32::Foundation::PWSTR lpName) noexcept;
    void* __stdcall ORBIT_IMPL_MapViewOfFile(win32::Windows::Win32::Foundation::HANDLE hFileMappingObject, win32::Windows::Win32::System::Memory::FILE_MAP dwDesiredAccess, uint32_t dwFileOffsetHigh, uint32_t dwFileOffsetLow, size_t dwNumberOfBytesToMap) noexcept;
    void* __stdcall ORBIT_IMPL_MapViewOfFileEx(win32::Windows::Win32::Foundation::HANDLE hFileMappingObject, win32::Windows::Win32::System::Memory::FILE_MAP dwDesiredAccess, uint32_t dwFileOffsetHigh, uint32_t dwFileOffsetLow, size_t dwNumberOfBytesToMap, void* lpBaseAddress) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_VirtualFreeEx(win32::Windows::Win32::Foundation::HANDLE hProcess, void* lpAddress, size_t dwSize, win32::Windows::Win32::System::Memory::VIRTUAL_FREE_TYPE dwFreeType) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_FlushViewOfFile(void* lpBaseAddress, size_t dwNumberOfBytesToFlush) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_UnmapViewOfFile(void* lpBaseAddress) noexcept;
    size_t __stdcall ORBIT_IMPL_GetLargePageMinimum() noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_GetProcessWorkingSetSizeEx(win32::Windows::Win32::Foundation::HANDLE hProcess, size_t* lpMinimumWorkingSetSize, size_t* lpMaximumWorkingSetSize, uint32_t* Flags) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_SetProcessWorkingSetSizeEx(win32::Windows::Win32::Foundation::HANDLE hProcess, size_t dwMinimumWorkingSetSize, size_t dwMaximumWorkingSetSize, uint32_t Flags) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_VirtualLock(void* lpAddress, size_t dwSize) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_VirtualUnlock(void* lpAddress, size_t dwSize) noexcept;
    uint32_t __stdcall ORBIT_IMPL_GetWriteWatch(uint32_t dwFlags, void* lpBaseAddress, size_t dwRegionSize, void** lpAddresses, size_t* lpdwCount, uint32_t* lpdwGranularity) noexcept;
    uint32_t __stdcall ORBIT_IMPL_ResetWriteWatch(void* lpBaseAddress, size_t dwRegionSize) noexcept;
    win32::Windows::Win32::Foundation::HANDLE __stdcall ORBIT_IMPL_CreateMemoryResourceNotification(win32::Windows::Win32::System::Memory::MEMORY_RESOURCE_NOTIFICATION_TYPE NotificationType) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_QueryMemoryResourceNotification(win32::Windows::Win32::Foundation::HANDLE ResourceNotificationHandle, win32::Windows::Win32::Foundation::BOOL* ResourceState) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_GetSystemFileCacheSize(size_t* lpMinimumFileCacheSize, size_t* lpMaximumFileCacheSize, uint32_t* lpFlags) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_SetSystemFileCacheSize(size_t MinimumFileCacheSize, size_t MaximumFileCacheSize, uint32_t Flags) noexcept;
    win32::Windows::Win32::Foundation::HANDLE __stdcall ORBIT_IMPL_CreateFileMappingNumaW(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Security::SECURITY_ATTRIBUTES* lpFileMappingAttributes, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS flProtect, uint32_t dwMaximumSizeHigh, uint32_t dwMaximumSizeLow, win32::Windows::Win32::Foundation::PWSTR lpName, uint32_t nndPreferred) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_PrefetchVirtualMemory(win32::Windows::Win32::Foundation::HANDLE hProcess, size_t NumberOfEntries, win32::Windows::Win32::System::Memory::WIN32_MEMORY_RANGE_ENTRY* VirtualAddresses, uint32_t Flags) noexcept;
    win32::Windows::Win32::Foundation::HANDLE __stdcall ORBIT_IMPL_CreateFileMappingFromApp(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Security::SECURITY_ATTRIBUTES* SecurityAttributes, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS PageProtection, uint64_t MaximumSize, win32::Windows::Win32::Foundation::PWSTR Name) noexcept;
    void* __stdcall ORBIT_IMPL_MapViewOfFileFromApp(win32::Windows::Win32::Foundation::HANDLE hFileMappingObject, win32::Windows::Win32::System::Memory::FILE_MAP DesiredAccess, uint64_t FileOffset, size_t NumberOfBytesToMap) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_UnmapViewOfFileEx(void* BaseAddress, win32::Windows::Win32::System::Memory::UNMAP_VIEW_OF_FILE_FLAGS UnmapFlags) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_AllocateUserPhysicalPages(win32::Windows::Win32::Foundation::HANDLE hProcess, size_t* NumberOfPages, size_t* PageArray) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_FreeUserPhysicalPages(win32::Windows::Win32::Foundation::HANDLE hProcess, size_t* NumberOfPages, size_t* PageArray) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_MapUserPhysicalPages(void* VirtualAddress, size_t NumberOfPages, size_t* PageArray) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_AllocateUserPhysicalPagesNuma(win32::Windows::Win32::Foundation::HANDLE hProcess, size_t* NumberOfPages, size_t* PageArray, uint32_t nndPreferred) noexcept;
    void* __stdcall ORBIT_IMPL_VirtualAllocExNuma(win32::Windows::Win32::Foundation::HANDLE hProcess, void* lpAddress, size_t dwSize, win32::Windows::Win32::System::Memory::VIRTUAL_ALLOCATION_TYPE flAllocationType, uint32_t flProtect, uint32_t nndPreferred) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_GetMemoryErrorHandlingCapabilities(uint32_t* Capabilities) noexcept;
    void* __stdcall ORBIT_IMPL_RegisterBadMemoryNotification(win32::Windows::Win32::System::Memory::PBAD_MEMORY_CALLBACK_ROUTINE* Callback) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_UnregisterBadMemoryNotification(void* RegistrationHandle) noexcept;
    uint32_t __stdcall ORBIT_IMPL_OfferVirtualMemory(void* VirtualAddress, size_t Size, win32::Windows::Win32::System::Memory::OFFER_PRIORITY Priority) noexcept;
    uint32_t __stdcall ORBIT_IMPL_ReclaimVirtualMemory(void* VirtualAddress, size_t Size) noexcept;
    uint32_t __stdcall ORBIT_IMPL_DiscardVirtualMemory(void* VirtualAddress, size_t Size) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_SetProcessValidCallTargets(win32::Windows::Win32::Foundation::HANDLE hProcess, void* VirtualAddress, size_t RegionSize, uint32_t NumberOfOffsets, win32::Windows::Win32::System::SystemServices::CFG_CALL_TARGET_INFO* OffsetInformation) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_SetProcessValidCallTargetsForMappedView(win32::Windows::Win32::Foundation::HANDLE Process, void* VirtualAddress, size_t RegionSize, uint32_t NumberOfOffsets, win32::Windows::Win32::System::SystemServices::CFG_CALL_TARGET_INFO* OffsetInformation, win32::Windows::Win32::Foundation::HANDLE Section, uint64_t ExpectedFileOffset) noexcept;
    void* __stdcall ORBIT_IMPL_VirtualAllocFromApp(void* BaseAddress, size_t Size, win32::Windows::Win32::System::Memory::VIRTUAL_ALLOCATION_TYPE AllocationType, uint32_t Protection) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_VirtualProtectFromApp(void* Address, size_t Size, uint32_t NewProtection, uint32_t* OldProtection) noexcept;
    win32::Windows::Win32::Foundation::HANDLE __stdcall ORBIT_IMPL_OpenFileMappingFromApp(uint32_t DesiredAccess, win32::Windows::Win32::Foundation::BOOL InheritHandle, win32::Windows::Win32::Foundation::PWSTR Name) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_QueryVirtualMemoryInformation(win32::Windows::Win32::Foundation::HANDLE Process, void* VirtualAddress, win32::Windows::Win32::System::Memory::WIN32_MEMORY_INFORMATION_CLASS MemoryInformationClass, void* MemoryInformation, size_t MemoryInformationSize, size_t* ReturnSize) noexcept;
    void* __stdcall ORBIT_IMPL_MapViewOfFileNuma2(win32::Windows::Win32::Foundation::HANDLE FileMappingHandle, win32::Windows::Win32::Foundation::HANDLE ProcessHandle, uint64_t Offset, void* BaseAddress, size_t ViewSize, uint32_t AllocationType, uint32_t PageProtection, uint32_t PreferredNode) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_UnmapViewOfFile2(win32::Windows::Win32::Foundation::HANDLE Process, void* BaseAddress, win32::Windows::Win32::System::Memory::UNMAP_VIEW_OF_FILE_FLAGS UnmapFlags) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_VirtualUnlockEx(win32::Windows::Win32::Foundation::HANDLE Process, void* Address, size_t Size) noexcept;
    void* __stdcall ORBIT_IMPL_VirtualAlloc2(win32::Windows::Win32::Foundation::HANDLE Process, void* BaseAddress, size_t Size, win32::Windows::Win32::System::Memory::VIRTUAL_ALLOCATION_TYPE AllocationType, uint32_t PageProtection, win32::Windows::Win32::System::SystemServices::MEM_EXTENDED_PARAMETER* ExtendedParameters, uint32_t ParameterCount) noexcept;
    void* __stdcall ORBIT_IMPL_MapViewOfFile3(win32::Windows::Win32::Foundation::HANDLE FileMapping, win32::Windows::Win32::Foundation::HANDLE Process, void* BaseAddress, uint64_t Offset, size_t ViewSize, win32::Windows::Win32::System::Memory::VIRTUAL_ALLOCATION_TYPE AllocationType, uint32_t PageProtection, win32::Windows::Win32::System::SystemServices::MEM_EXTENDED_PARAMETER* ExtendedParameters, uint32_t ParameterCount) noexcept;
    void* __stdcall ORBIT_IMPL_VirtualAlloc2FromApp(win32::Windows::Win32::Foundation::HANDLE Process, void* BaseAddress, size_t Size, win32::Windows::Win32::System::Memory::VIRTUAL_ALLOCATION_TYPE AllocationType, uint32_t PageProtection, win32::Windows::Win32::System::SystemServices::MEM_EXTENDED_PARAMETER* ExtendedParameters, uint32_t ParameterCount) noexcept;
    void* __stdcall ORBIT_IMPL_MapViewOfFile3FromApp(win32::Windows::Win32::Foundation::HANDLE FileMapping, win32::Windows::Win32::Foundation::HANDLE Process, void* BaseAddress, uint64_t Offset, size_t ViewSize, win32::Windows::Win32::System::Memory::VIRTUAL_ALLOCATION_TYPE AllocationType, uint32_t PageProtection, win32::Windows::Win32::System::SystemServices::MEM_EXTENDED_PARAMETER* ExtendedParameters, uint32_t ParameterCount) noexcept;
    win32::Windows::Win32::Foundation::HANDLE __stdcall ORBIT_IMPL_CreateFileMapping2(win32::Windows::Win32::Foundation::HANDLE File, win32::Windows::Win32::Security::SECURITY_ATTRIBUTES* SecurityAttributes, uint32_t DesiredAccess, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS PageProtection, uint32_t AllocationAttributes, uint64_t MaximumSize, win32::Windows::Win32::Foundation::PWSTR Name, win32::Windows::Win32::System::SystemServices::MEM_EXTENDED_PARAMETER* ExtendedParameters, uint32_t ParameterCount) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_AllocateUserPhysicalPages2(win32::Windows::Win32::Foundation::HANDLE ObjectHandle, size_t* NumberOfPages, size_t* PageArray, win32::Windows::Win32::System::SystemServices::MEM_EXTENDED_PARAMETER* ExtendedParameters, uint32_t ExtendedParameterCount) noexcept;
    win32::Windows::Win32::Foundation::HANDLE __stdcall ORBIT_IMPL_OpenDedicatedMemoryPartition(win32::Windows::Win32::Foundation::HANDLE Partition, uint64_t DedicatedMemoryTypeId, uint32_t DesiredAccess, win32::Windows::Win32::Foundation::BOOL InheritHandle) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_QueryPartitionInformation(win32::Windows::Win32::Foundation::HANDLE Partition, win32::Windows::Win32::System::Memory::WIN32_MEMORY_PARTITION_INFORMATION_CLASS PartitionInformationClass, void* PartitionInformation, uint32_t PartitionInformationLength) noexcept;
    intptr_t __stdcall ORBIT_IMPL_GlobalAlloc(win32::Windows::Win32::System::Memory::GLOBAL_ALLOC_FLAGS uFlags, size_t dwBytes) noexcept;
    intptr_t __stdcall ORBIT_IMPL_GlobalReAlloc(intptr_t hMem, size_t dwBytes, uint32_t uFlags) noexcept;
    size_t __stdcall ORBIT_IMPL_GlobalSize(intptr_t hMem) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_GlobalUnlock(intptr_t hMem) noexcept;
    void* __stdcall ORBIT_IMPL_GlobalLock(intptr_t hMem) noexcept;
    uint32_t __stdcall ORBIT_IMPL_GlobalFlags(intptr_t hMem) noexcept;
    intptr_t __stdcall ORBIT_IMPL_GlobalHandle(void* pMem) noexcept;
    intptr_t __stdcall ORBIT_IMPL_GlobalFree(intptr_t hMem) noexcept;
    intptr_t __stdcall ORBIT_IMPL_LocalAlloc(win32::Windows::Win32::System::Memory::LOCAL_ALLOC_FLAGS uFlags, size_t uBytes) noexcept;
    intptr_t __stdcall ORBIT_IMPL_LocalReAlloc(intptr_t hMem, size_t uBytes, uint32_t uFlags) noexcept;
    void* __stdcall ORBIT_IMPL_LocalLock(intptr_t hMem) noexcept;
    intptr_t __stdcall ORBIT_IMPL_LocalHandle(void* pMem) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_LocalUnlock(intptr_t hMem) noexcept;
    size_t __stdcall ORBIT_IMPL_LocalSize(intptr_t hMem) noexcept;
    uint32_t __stdcall ORBIT_IMPL_LocalFlags(intptr_t hMem) noexcept;
    intptr_t __stdcall ORBIT_IMPL_LocalFree(intptr_t hMem) noexcept;
    win32::Windows::Win32::Foundation::HANDLE __stdcall ORBIT_IMPL_CreateFileMappingA(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Security::SECURITY_ATTRIBUTES* lpFileMappingAttributes, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS flProtect, uint32_t dwMaximumSizeHigh, uint32_t dwMaximumSizeLow, win32::Windows::Win32::Foundation::PSTR lpName) noexcept;
    win32::Windows::Win32::Foundation::HANDLE __stdcall ORBIT_IMPL_CreateFileMappingNumaA(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Security::SECURITY_ATTRIBUTES* lpFileMappingAttributes, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS flProtect, uint32_t dwMaximumSizeHigh, uint32_t dwMaximumSizeLow, win32::Windows::Win32::Foundation::PSTR lpName, uint32_t nndPreferred) noexcept;
    win32::Windows::Win32::Foundation::HANDLE __stdcall ORBIT_IMPL_OpenFileMappingA(uint32_t dwDesiredAccess, win32::Windows::Win32::Foundation::BOOL bInheritHandle, win32::Windows::Win32::Foundation::PSTR lpName) noexcept;
    void* __stdcall ORBIT_IMPL_MapViewOfFileExNuma(win32::Windows::Win32::Foundation::HANDLE hFileMappingObject, win32::Windows::Win32::System::Memory::FILE_MAP dwDesiredAccess, uint32_t dwFileOffsetHigh, uint32_t dwFileOffsetLow, size_t dwNumberOfBytesToMap, void* lpBaseAddress, uint32_t nndPreferred) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_IsBadReadPtr(void* lp, size_t ucb) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_IsBadWritePtr(void* lp, size_t ucb) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_IsBadCodePtr(win32::Windows::Win32::Foundation::FARPROC* lpfn) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_IsBadStringPtrA(win32::Windows::Win32::Foundation::PSTR lpsz, size_t ucchMax) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_IsBadStringPtrW(win32::Windows::Win32::Foundation::PWSTR lpsz, size_t ucchMax) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_MapUserPhysicalPagesScatter(void** VirtualAddresses, size_t NumberOfPages, size_t* PageArray) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_AddSecureMemoryCacheCallback(win32::Windows::Win32::System::Memory::PSECURE_MEMORY_CACHE_CALLBACK* pfnCallBack) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_RemoveSecureMemoryCacheCallback(win32::Windows::Win32::System::Memory::PSECURE_MEMORY_CACHE_CALLBACK* pfnCallBack) noexcept;
}

struct ApiTable {
    win32::Windows::Win32::System::Memory::HeapHandle (__stdcall *HeapCreate)(win32::Windows::Win32::System::Memory::HEAP_FLAGS flOptions, size_t dwInitialSize, size_t dwMaximumSize) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *HeapDestroy)(win32::Windows::Win32::System::Memory::HeapHandle hHeap) noexcept;
    void* (__stdcall *HeapAlloc)(win32::Windows::Win32::System::Memory::HeapHandle hHeap, win32::Windows::Win32::System::Memory::HEAP_FLAGS dwFlags, size_t dwBytes) noexcept;
    void* (__stdcall *HeapReAlloc)(win32::Windows::Win32::System::Memory::HeapHandle hHeap, win32::Windows::Win32::System::Memory::HEAP_FLAGS dwFlags, void* lpMem, size_t dwBytes) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *HeapFree)(win32::Windows::Win32::System::Memory::HeapHandle hHeap, win32::Windows::Win32::System::Memory::HEAP_FLAGS dwFlags, void* lpMem) noexcept;
    size_t (__stdcall *HeapSize)(win32::Windows::Win32::System::Memory::HeapHandle hHeap, win32::Windows::Win32::System::Memory::HEAP_FLAGS dwFlags, void* lpMem) noexcept;
    win32::Windows::Win32::System::Memory::HeapHandle (__stdcall *GetProcessHeap)() noexcept;
    size_t (__stdcall *HeapCompact)(win32::Windows::Win32::System::Memory::HeapHandle hHeap, win32::Windows::Win32::System::Memory::HEAP_FLAGS dwFlags) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *HeapSetInformation)(win32::Windows::Win32::System::Memory::HeapHandle HeapHandle, win32::Windows::Win32::System::SystemServices::HEAP_INFORMATION_CLASS HeapInformationClass, void* HeapInformation, size_t HeapInformationLength) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *HeapValidate)(win32::Windows::Win32::System::Memory::HeapHandle hHeap, win32::Windows::Win32::System::Memory::HEAP_FLAGS dwFlags, void* lpMem) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *HeapSummary)(win32::Windows::Win32::Foundation::HANDLE hHeap, uint32_t dwFlags, win32::Windows::Win32::System::Memory::HEAP_SUMMARY* lpSummary) noexcept;
    uint32_t (__stdcall *GetProcessHeaps)(uint32_t NumberOfHeaps, win32::Windows::Win32::System::Memory::HeapHandle* ProcessHeaps) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *HeapLock)(win32::Windows::Win32::System::Memory::HeapHandle hHeap) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *HeapUnlock)(win32::Windows::Win32::System::Memory::HeapHandle hHeap) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *HeapWalk)(win32::Windows::Win32::System::Memory::HeapHandle hHeap, win32::Windows::Win32::System::SystemServices::PROCESS_HEAP_ENTRY* lpEntry) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *HeapQueryInformation)(win32::Windows::Win32::System::Memory::HeapHandle HeapHandle, win32::Windows::Win32::System::SystemServices::HEAP_INFORMATION_CLASS HeapInformationClass, void* HeapInformation, size_t HeapInformationLength, size_t* ReturnLength) noexcept;
    void* (__stdcall *VirtualAlloc)(void* lpAddress, size_t dwSize, win32::Windows::Win32::System::Memory::VIRTUAL_ALLOCATION_TYPE flAllocationType, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS flProtect) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *VirtualProtect)(void* lpAddress, size_t dwSize, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS flNewProtect, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS* lpflOldProtect) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *VirtualFree)(void* lpAddress, size_t dwSize, win32::Windows::Win32::System::Memory::VIRTUAL_FREE_TYPE dwFreeType) noexcept;
    size_t (__stdcall *VirtualQuery)(void* lpAddress, win32::Windows::Win32::System::Memory::MEMORY_BASIC_INFORMATION* lpBuffer, size_t dwLength) noexcept;
    void* (__stdcall *VirtualAllocEx)(win32::Windows::Win32::Foundation::HANDLE hProcess, void* lpAddress, size_t dwSize, win32::Windows::Win32::System::Memory::VIRTUAL_ALLOCATION_TYPE flAllocationType, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS flProtect) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *VirtualProtectEx)(win32::Windows::Win32::Foundation::HANDLE hProcess, void* lpAddress, size_t dwSize, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS flNewProtect, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS* lpflOldProtect) noexcept;
    size_t (__stdcall *VirtualQueryEx)(win32::Windows::Win32::Foundation::HANDLE hProcess, void* lpAddress, win32::Windows::Win32::System::Memory::MEMORY_BASIC_INFORMATION* lpBuffer, size_t dwLength) noexcept;
    win32::Windows::Win32::Foundation::HANDLE (__stdcall *CreateFileMappingW)(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Security::SECURITY_ATTRIBUTES* lpFileMappingAttributes, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS flProtect, uint32_t dwMaximumSizeHigh, uint32_t dwMaximumSizeLow, win32::Windows::Win32::Foundation::PWSTR lpName) noexcept;
    win32::Windows::Win32::Foundation::HANDLE (__stdcall *OpenFileMappingW)(uint32_t dwDesiredAccess, win32::Windows::Win32::Foundation::BOOL bInheritHandle, win32::Windows::Win32::Foundation::PWSTR lpName) noexcept;
    void* (__stdcall *MapViewOfFile)(win32::Windows::Win32::Foundation::HANDLE hFileMappingObject, win32::Windows::Win32::System::Memory::FILE_MAP dwDesiredAccess, uint32_t dwFileOffsetHigh, uint32_t dwFileOffsetLow, size_t dwNumberOfBytesToMap) noexcept;
    void* (__stdcall *MapViewOfFileEx)(win32::Windows::Win32::Foundation::HANDLE hFileMappingObject, win32::Windows::Win32::System::Memory::FILE_MAP dwDesiredAccess, uint32_t dwFileOffsetHigh, uint32_t dwFileOffsetLow, size_t dwNumberOfBytesToMap, void* lpBaseAddress) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *VirtualFreeEx)(win32::Windows::Win32::Foundation::HANDLE hProcess, void* lpAddress, size_t dwSize, win32::Windows::Win32::System::Memory::VIRTUAL_FREE_TYPE dwFreeType) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *FlushViewOfFile)(void* lpBaseAddress, size_t dwNumberOfBytesToFlush) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *UnmapViewOfFile)(void* lpBaseAddress) noexcept;
    size_t (__stdcall *GetLargePageMinimum)() noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *GetProcessWorkingSetSizeEx)(win32::Windows::Win32::Foundation::HANDLE hProcess, size_t* lpMinimumWorkingSetSize, size_t* lpMaximumWorkingSetSize, uint32_t* Flags) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *SetProcessWorkingSetSizeEx)(win32::Windows::Win32::Foundation::HANDLE hProcess, size_t dwMinimumWorkingSetSize, size_t dwMaximumWorkingSetSize, uint32_t Flags) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *VirtualLock)(void* lpAddress, size_t dwSize) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *VirtualUnlock)(void* lpAddress, size_t dwSize) noexcept;
    uint32_t (__stdcall *GetWriteWatch)(uint32_t dwFlags, void* lpBaseAddress, size_t dwRegionSize, void** lpAddresses, size_t* lpdwCount, uint32_t* lpdwGranularity) noexcept;
    uint32_t (__stdcall *ResetWriteWatch)(void* lpBaseAddress, size_t dwRegionSize) noexcept;
    win32::Windows::Win32::Foundation::HANDLE (__stdcall *CreateMemoryResourceNotification)(win32::Windows::Win32::System::Memory::MEMORY_RESOURCE_NOTIFICATION_TYPE NotificationType) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *QueryMemoryResourceNotification)(win32::Windows::Win32::Foundation::HANDLE ResourceNotificationHandle, win32::Windows::Win32::Foundation::BOOL* ResourceState) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *GetSystemFileCacheSize)(size_t* lpMinimumFileCacheSize, size_t* lpMaximumFileCacheSize, uint32_t* lpFlags) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *SetSystemFileCacheSize)(size_t MinimumFileCacheSize, size_t MaximumFileCacheSize, uint32_t Flags) noexcept;
    win32::Windows::Win32::Foundation::HANDLE (__stdcall *CreateFileMappingNumaW)(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Security::SECURITY_ATTRIBUTES* lpFileMappingAttributes, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS flProtect, uint32_t dwMaximumSizeHigh, uint32_t dwMaximumSizeLow, win32::Windows::Win32::Foundation::PWSTR lpName, uint32_t nndPreferred) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *PrefetchVirtualMemory)(win32::Windows::Win32::Foundation::HANDLE hProcess, size_t NumberOfEntries, win32::Windows::Win32::System::Memory::WIN32_MEMORY_RANGE_ENTRY* VirtualAddresses, uint32_t Flags) noexcept;
    win32::Windows::Win32::Foundation::HANDLE (__stdcall *CreateFileMappingFromApp)(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Security::SECURITY_ATTRIBUTES* SecurityAttributes, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS PageProtection, uint64_t MaximumSize, win32::Windows::Win32::Foundation::PWSTR Name) noexcept;
    void* (__stdcall *MapViewOfFileFromApp)(win32::Windows::Win32::Foundation::HANDLE hFileMappingObject, win32::Windows::Win32::System::Memory::FILE_MAP DesiredAccess, uint64_t FileOffset, size_t NumberOfBytesToMap) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *UnmapViewOfFileEx)(void* BaseAddress, win32::Windows::Win32::System::Memory::UNMAP_VIEW_OF_FILE_FLAGS UnmapFlags) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *AllocateUserPhysicalPages)(win32::Windows::Win32::Foundation::HANDLE hProcess, size_t* NumberOfPages, size_t* PageArray) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *FreeUserPhysicalPages)(win32::Windows::Win32::Foundation::HANDLE hProcess, size_t* NumberOfPages, size_t* PageArray) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *MapUserPhysicalPages)(void* VirtualAddress, size_t NumberOfPages, size_t* PageArray) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *AllocateUserPhysicalPagesNuma)(win32::Windows::Win32::Foundation::HANDLE hProcess, size_t* NumberOfPages, size_t* PageArray, uint32_t nndPreferred) noexcept;
    void* (__stdcall *VirtualAllocExNuma)(win32::Windows::Win32::Foundation::HANDLE hProcess, void* lpAddress, size_t dwSize, win32::Windows::Win32::System::Memory::VIRTUAL_ALLOCATION_TYPE flAllocationType, uint32_t flProtect, uint32_t nndPreferred) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *GetMemoryErrorHandlingCapabilities)(uint32_t* Capabilities) noexcept;
    void* (__stdcall *RegisterBadMemoryNotification)(win32::Windows::Win32::System::Memory::PBAD_MEMORY_CALLBACK_ROUTINE* Callback) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *UnregisterBadMemoryNotification)(void* RegistrationHandle) noexcept;
    uint32_t (__stdcall *OfferVirtualMemory)(void* VirtualAddress, size_t Size, win32::Windows::Win32::System::Memory::OFFER_PRIORITY Priority) noexcept;
    uint32_t (__stdcall *ReclaimVirtualMemory)(void* VirtualAddress, size_t Size) noexcept;
    uint32_t (__stdcall *DiscardVirtualMemory)(void* VirtualAddress, size_t Size) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *SetProcessValidCallTargets)(win32::Windows::Win32::Foundation::HANDLE hProcess, void* VirtualAddress, size_t RegionSize, uint32_t NumberOfOffsets, win32::Windows::Win32::System::SystemServices::CFG_CALL_TARGET_INFO* OffsetInformation) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *SetProcessValidCallTargetsForMappedView)(win32::Windows::Win32::Foundation::HANDLE Process, void* VirtualAddress, size_t RegionSize, uint32_t NumberOfOffsets, win32::Windows::Win32::System::SystemServices::CFG_CALL_TARGET_INFO* OffsetInformation, win32::Windows::Win32::Foundation::HANDLE Section, uint64_t ExpectedFileOffset) noexcept;
    void* (__stdcall *VirtualAllocFromApp)(void* BaseAddress, size_t Size, win32::Windows::Win32::System::Memory::VIRTUAL_ALLOCATION_TYPE AllocationType, uint32_t Protection) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *VirtualProtectFromApp)(void* Address, size_t Size, uint32_t NewProtection, uint32_t* OldProtection) noexcept;
    win32::Windows::Win32::Foundation::HANDLE (__stdcall *OpenFileMappingFromApp)(uint32_t DesiredAccess, win32::Windows::Win32::Foundation::BOOL InheritHandle, win32::Windows::Win32::Foundation::PWSTR Name) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *QueryVirtualMemoryInformation)(win32::Windows::Win32::Foundation::HANDLE Process, void* VirtualAddress, win32::Windows::Win32::System::Memory::WIN32_MEMORY_INFORMATION_CLASS MemoryInformationClass, void* MemoryInformation, size_t MemoryInformationSize, size_t* ReturnSize) noexcept;
    void* (__stdcall *MapViewOfFileNuma2)(win32::Windows::Win32::Foundation::HANDLE FileMappingHandle, win32::Windows::Win32::Foundation::HANDLE ProcessHandle, uint64_t Offset, void* BaseAddress, size_t ViewSize, uint32_t AllocationType, uint32_t PageProtection, uint32_t PreferredNode) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *UnmapViewOfFile2)(win32::Windows::Win32::Foundation::HANDLE Process, void* BaseAddress, win32::Windows::Win32::System::Memory::UNMAP_VIEW_OF_FILE_FLAGS UnmapFlags) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *VirtualUnlockEx)(win32::Windows::Win32::Foundation::HANDLE Process, void* Address, size_t Size) noexcept;
    void* (__stdcall *VirtualAlloc2)(win32::Windows::Win32::Foundation::HANDLE Process, void* BaseAddress, size_t Size, win32::Windows::Win32::System::Memory::VIRTUAL_ALLOCATION_TYPE AllocationType, uint32_t PageProtection, win32::Windows::Win32::System::SystemServices::MEM_EXTENDED_PARAMETER* ExtendedParameters, uint32_t ParameterCount) noexcept;
    void* (__stdcall *MapViewOfFile3)(win32::Windows::Win32::Foundation::HANDLE FileMapping, win32::Windows::Win32::Foundation::HANDLE Process, void* BaseAddress, uint64_t Offset, size_t ViewSize, win32::Windows::Win32::System::Memory::VIRTUAL_ALLOCATION_TYPE AllocationType, uint32_t PageProtection, win32::Windows::Win32::System::SystemServices::MEM_EXTENDED_PARAMETER* ExtendedParameters, uint32_t ParameterCount) noexcept;
    void* (__stdcall *VirtualAlloc2FromApp)(win32::Windows::Win32::Foundation::HANDLE Process, void* BaseAddress, size_t Size, win32::Windows::Win32::System::Memory::VIRTUAL_ALLOCATION_TYPE AllocationType, uint32_t PageProtection, win32::Windows::Win32::System::SystemServices::MEM_EXTENDED_PARAMETER* ExtendedParameters, uint32_t ParameterCount) noexcept;
    void* (__stdcall *MapViewOfFile3FromApp)(win32::Windows::Win32::Foundation::HANDLE FileMapping, win32::Windows::Win32::Foundation::HANDLE Process, void* BaseAddress, uint64_t Offset, size_t ViewSize, win32::Windows::Win32::System::Memory::VIRTUAL_ALLOCATION_TYPE AllocationType, uint32_t PageProtection, win32::Windows::Win32::System::SystemServices::MEM_EXTENDED_PARAMETER* ExtendedParameters, uint32_t ParameterCount) noexcept;
    win32::Windows::Win32::Foundation::HANDLE (__stdcall *CreateFileMapping2)(win32::Windows::Win32::Foundation::HANDLE File, win32::Windows::Win32::Security::SECURITY_ATTRIBUTES* SecurityAttributes, uint32_t DesiredAccess, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS PageProtection, uint32_t AllocationAttributes, uint64_t MaximumSize, win32::Windows::Win32::Foundation::PWSTR Name, win32::Windows::Win32::System::SystemServices::MEM_EXTENDED_PARAMETER* ExtendedParameters, uint32_t ParameterCount) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *AllocateUserPhysicalPages2)(win32::Windows::Win32::Foundation::HANDLE ObjectHandle, size_t* NumberOfPages, size_t* PageArray, win32::Windows::Win32::System::SystemServices::MEM_EXTENDED_PARAMETER* ExtendedParameters, uint32_t ExtendedParameterCount) noexcept;
    win32::Windows::Win32::Foundation::HANDLE (__stdcall *OpenDedicatedMemoryPartition)(win32::Windows::Win32::Foundation::HANDLE Partition, uint64_t DedicatedMemoryTypeId, uint32_t DesiredAccess, win32::Windows::Win32::Foundation::BOOL InheritHandle) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *QueryPartitionInformation)(win32::Windows::Win32::Foundation::HANDLE Partition, win32::Windows::Win32::System::Memory::WIN32_MEMORY_PARTITION_INFORMATION_CLASS PartitionInformationClass, void* PartitionInformation, uint32_t PartitionInformationLength) noexcept;
    intptr_t (__stdcall *GlobalAlloc)(win32::Windows::Win32::System::Memory::GLOBAL_ALLOC_FLAGS uFlags, size_t dwBytes) noexcept;
    intptr_t (__stdcall *GlobalReAlloc)(intptr_t hMem, size_t dwBytes, uint32_t uFlags) noexcept;
    size_t (__stdcall *GlobalSize)(intptr_t hMem) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *GlobalUnlock)(intptr_t hMem) noexcept;
    void* (__stdcall *GlobalLock)(intptr_t hMem) noexcept;
    uint32_t (__stdcall *GlobalFlags)(intptr_t hMem) noexcept;
    intptr_t (__stdcall *GlobalHandle)(void* pMem) noexcept;
    intptr_t (__stdcall *GlobalFree)(intptr_t hMem) noexcept;
    intptr_t (__stdcall *LocalAlloc)(win32::Windows::Win32::System::Memory::LOCAL_ALLOC_FLAGS uFlags, size_t uBytes) noexcept;
    intptr_t (__stdcall *LocalReAlloc)(intptr_t hMem, size_t uBytes, uint32_t uFlags) noexcept;
    void* (__stdcall *LocalLock)(intptr_t hMem) noexcept;
    intptr_t (__stdcall *LocalHandle)(void* pMem) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *LocalUnlock)(intptr_t hMem) noexcept;
    size_t (__stdcall *LocalSize)(intptr_t hMem) noexcept;
    uint32_t (__stdcall *LocalFlags)(intptr_t hMem) noexcept;
    intptr_t (__stdcall *LocalFree)(intptr_t hMem) noexcept;
    win32::Windows::Win32::Foundation::HANDLE (__stdcall *CreateFileMappingA)(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Security::SECURITY_ATTRIBUTES* lpFileMappingAttributes, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS flProtect, uint32_t dwMaximumSizeHigh, uint32_t dwMaximumSizeLow, win32::Windows::Win32::Foundation::PSTR lpName) noexcept;
    win32::Windows::Win32::Foundation::HANDLE (__stdcall *CreateFileMappingNumaA)(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Security::SECURITY_ATTRIBUTES* lpFileMappingAttributes, win32::Windows::Win32::System::Memory::PAGE_PROTECTION_FLAGS flProtect, uint32_t dwMaximumSizeHigh, uint32_t dwMaximumSizeLow, win32::Windows::Win32::Foundation::PSTR lpName, uint32_t nndPreferred) noexcept;
    win32::Windows::Win32::Foundation::HANDLE (__stdcall *OpenFileMappingA)(uint32_t dwDesiredAccess, win32::Windows::Win32::Foundation::BOOL bInheritHandle, win32::Windows::Win32::Foundation::PSTR lpName) noexcept;
    void* (__stdcall *MapViewOfFileExNuma)(win32::Windows::Win32::Foundation::HANDLE hFileMappingObject, win32::Windows::Win32::System::Memory::FILE_MAP dwDesiredAccess, uint32_t dwFileOffsetHigh, uint32_t dwFileOffsetLow, size_t dwNumberOfBytesToMap, void* lpBaseAddress, uint32_t nndPreferred) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *IsBadReadPtr)(void* lp, size_t ucb) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *IsBadWritePtr)(void* lp, size_t ucb) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *IsBadCodePtr)(win32::Windows::Win32::Foundation::FARPROC* lpfn) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *IsBadStringPtrA)(win32::Windows::Win32::Foundation::PSTR lpsz, size_t ucchMax) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *IsBadStringPtrW)(win32::Windows::Win32::Foundation::PWSTR lpsz, size_t ucchMax) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *MapUserPhysicalPagesScatter)(void** VirtualAddresses, size_t NumberOfPages, size_t* PageArray) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *AddSecureMemoryCacheCallback)(win32::Windows::Win32::System::Memory::PSECURE_MEMORY_CACHE_CALLBACK* pfnCallBack) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *RemoveSecureMemoryCacheCallback)(win32::Windows::Win32::System::Memory::PSECURE_MEMORY_CACHE_CALLBACK* pfnCallBack) noexcept;
};
extern ApiTable g_api_table;

#pragma endregion methods

}
#endif
