// WARNING: Please don't edit this file. It was generated by C++/Win32 v0.0.0.1

#ifndef WIN32_Windows_Win32_Devices_Communication_H
#define WIN32_Windows_Win32_Devices_Communication_H
#include "win32/base.h"
#include "win32/impl/complex_structs.h"
#include "win32/impl/complex_interfaces.h"
static_assert(win32::check_version(CPPWIN32_VERSION, "0.0.0.1"), "Mismatched C++/Win32 headers.");
#define CPPWIN32_VERSION "0.0.0.1"
#include "win32/impl/Windows.Win32.Devices.Communication.0.h"
WIN32_EXPORT namespace win32::Windows::Win32::Devices::Communication
{
#pragma region methods
extern "C"
{
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_ClearCommBreak(win32::Windows::Win32::Foundation::HANDLE hFile) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_ClearCommError(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::CLEAR_COMM_ERROR_FLAGS* lpErrors, win32::Windows::Win32::Devices::Communication::COMSTAT* lpStat) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_SetupComm(win32::Windows::Win32::Foundation::HANDLE hFile, uint32_t dwInQueue, uint32_t dwOutQueue) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_EscapeCommFunction(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::ESCAPE_COMM_FUNCTION dwFunc) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_GetCommConfig(win32::Windows::Win32::Foundation::HANDLE hCommDev, win32::Windows::Win32::Devices::Communication::COMMCONFIG* lpCC, uint32_t* lpdwSize) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_GetCommMask(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::COMM_EVENT_MASK* lpEvtMask) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_GetCommProperties(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::COMMPROP* lpCommProp) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_GetCommModemStatus(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::MODEM_STATUS_FLAGS* lpModemStat) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_GetCommState(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::DCB* lpDCB) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_GetCommTimeouts(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::COMMTIMEOUTS* lpCommTimeouts) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_PurgeComm(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::PURGE_COMM_FLAGS dwFlags) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_SetCommBreak(win32::Windows::Win32::Foundation::HANDLE hFile) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_SetCommConfig(win32::Windows::Win32::Foundation::HANDLE hCommDev, win32::Windows::Win32::Devices::Communication::COMMCONFIG* lpCC, uint32_t dwSize) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_SetCommMask(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::COMM_EVENT_MASK dwEvtMask) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_SetCommState(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::DCB* lpDCB) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_SetCommTimeouts(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::COMMTIMEOUTS* lpCommTimeouts) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_TransmitCommChar(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Foundation::CHAR cChar) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_WaitCommEvent(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::COMM_EVENT_MASK* lpEvtMask, win32::Windows::Win32::System::IO::OVERLAPPED* lpOverlapped) noexcept;
    win32::Windows::Win32::Foundation::HANDLE __stdcall ORBIT_IMPL_OpenCommPort(uint32_t uPortNumber, uint32_t dwDesiredAccess, uint32_t dwFlagsAndAttributes) noexcept;
    uint32_t __stdcall ORBIT_IMPL_GetCommPorts(uint32_t* lpPortNumbers, uint32_t uPortNumbersCount, uint32_t* puPortNumbersFound) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_BuildCommDCBA(win32::Windows::Win32::Foundation::PSTR lpDef, win32::Windows::Win32::Devices::Communication::DCB* lpDCB) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_BuildCommDCBW(win32::Windows::Win32::Foundation::PWSTR lpDef, win32::Windows::Win32::Devices::Communication::DCB* lpDCB) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_BuildCommDCBAndTimeoutsA(win32::Windows::Win32::Foundation::PSTR lpDef, win32::Windows::Win32::Devices::Communication::DCB* lpDCB, win32::Windows::Win32::Devices::Communication::COMMTIMEOUTS* lpCommTimeouts) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_BuildCommDCBAndTimeoutsW(win32::Windows::Win32::Foundation::PWSTR lpDef, win32::Windows::Win32::Devices::Communication::DCB* lpDCB, win32::Windows::Win32::Devices::Communication::COMMTIMEOUTS* lpCommTimeouts) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_CommConfigDialogA(win32::Windows::Win32::Foundation::PSTR lpszName, win32::Windows::Win32::Foundation::HWND hWnd, win32::Windows::Win32::Devices::Communication::COMMCONFIG* lpCC) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_CommConfigDialogW(win32::Windows::Win32::Foundation::PWSTR lpszName, win32::Windows::Win32::Foundation::HWND hWnd, win32::Windows::Win32::Devices::Communication::COMMCONFIG* lpCC) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_GetDefaultCommConfigA(win32::Windows::Win32::Foundation::PSTR lpszName, win32::Windows::Win32::Devices::Communication::COMMCONFIG* lpCC, uint32_t* lpdwSize) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_GetDefaultCommConfigW(win32::Windows::Win32::Foundation::PWSTR lpszName, win32::Windows::Win32::Devices::Communication::COMMCONFIG* lpCC, uint32_t* lpdwSize) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_SetDefaultCommConfigA(win32::Windows::Win32::Foundation::PSTR lpszName, win32::Windows::Win32::Devices::Communication::COMMCONFIG* lpCC, uint32_t dwSize) noexcept;
    win32::Windows::Win32::Foundation::BOOL __stdcall ORBIT_IMPL_SetDefaultCommConfigW(win32::Windows::Win32::Foundation::PWSTR lpszName, win32::Windows::Win32::Devices::Communication::COMMCONFIG* lpCC, uint32_t dwSize) noexcept;
}

struct ApiTable {
    win32::Windows::Win32::Foundation::BOOL (__stdcall *ClearCommBreak)(win32::Windows::Win32::Foundation::HANDLE hFile) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *ClearCommError)(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::CLEAR_COMM_ERROR_FLAGS* lpErrors, win32::Windows::Win32::Devices::Communication::COMSTAT* lpStat) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *SetupComm)(win32::Windows::Win32::Foundation::HANDLE hFile, uint32_t dwInQueue, uint32_t dwOutQueue) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *EscapeCommFunction)(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::ESCAPE_COMM_FUNCTION dwFunc) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *GetCommConfig)(win32::Windows::Win32::Foundation::HANDLE hCommDev, win32::Windows::Win32::Devices::Communication::COMMCONFIG* lpCC, uint32_t* lpdwSize) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *GetCommMask)(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::COMM_EVENT_MASK* lpEvtMask) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *GetCommProperties)(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::COMMPROP* lpCommProp) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *GetCommModemStatus)(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::MODEM_STATUS_FLAGS* lpModemStat) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *GetCommState)(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::DCB* lpDCB) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *GetCommTimeouts)(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::COMMTIMEOUTS* lpCommTimeouts) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *PurgeComm)(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::PURGE_COMM_FLAGS dwFlags) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *SetCommBreak)(win32::Windows::Win32::Foundation::HANDLE hFile) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *SetCommConfig)(win32::Windows::Win32::Foundation::HANDLE hCommDev, win32::Windows::Win32::Devices::Communication::COMMCONFIG* lpCC, uint32_t dwSize) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *SetCommMask)(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::COMM_EVENT_MASK dwEvtMask) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *SetCommState)(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::DCB* lpDCB) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *SetCommTimeouts)(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::COMMTIMEOUTS* lpCommTimeouts) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *TransmitCommChar)(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Foundation::CHAR cChar) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *WaitCommEvent)(win32::Windows::Win32::Foundation::HANDLE hFile, win32::Windows::Win32::Devices::Communication::COMM_EVENT_MASK* lpEvtMask, win32::Windows::Win32::System::IO::OVERLAPPED* lpOverlapped) noexcept;
    win32::Windows::Win32::Foundation::HANDLE (__stdcall *OpenCommPort)(uint32_t uPortNumber, uint32_t dwDesiredAccess, uint32_t dwFlagsAndAttributes) noexcept;
    uint32_t (__stdcall *GetCommPorts)(uint32_t* lpPortNumbers, uint32_t uPortNumbersCount, uint32_t* puPortNumbersFound) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *BuildCommDCBA)(win32::Windows::Win32::Foundation::PSTR lpDef, win32::Windows::Win32::Devices::Communication::DCB* lpDCB) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *BuildCommDCBW)(win32::Windows::Win32::Foundation::PWSTR lpDef, win32::Windows::Win32::Devices::Communication::DCB* lpDCB) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *BuildCommDCBAndTimeoutsA)(win32::Windows::Win32::Foundation::PSTR lpDef, win32::Windows::Win32::Devices::Communication::DCB* lpDCB, win32::Windows::Win32::Devices::Communication::COMMTIMEOUTS* lpCommTimeouts) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *BuildCommDCBAndTimeoutsW)(win32::Windows::Win32::Foundation::PWSTR lpDef, win32::Windows::Win32::Devices::Communication::DCB* lpDCB, win32::Windows::Win32::Devices::Communication::COMMTIMEOUTS* lpCommTimeouts) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *CommConfigDialogA)(win32::Windows::Win32::Foundation::PSTR lpszName, win32::Windows::Win32::Foundation::HWND hWnd, win32::Windows::Win32::Devices::Communication::COMMCONFIG* lpCC) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *CommConfigDialogW)(win32::Windows::Win32::Foundation::PWSTR lpszName, win32::Windows::Win32::Foundation::HWND hWnd, win32::Windows::Win32::Devices::Communication::COMMCONFIG* lpCC) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *GetDefaultCommConfigA)(win32::Windows::Win32::Foundation::PSTR lpszName, win32::Windows::Win32::Devices::Communication::COMMCONFIG* lpCC, uint32_t* lpdwSize) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *GetDefaultCommConfigW)(win32::Windows::Win32::Foundation::PWSTR lpszName, win32::Windows::Win32::Devices::Communication::COMMCONFIG* lpCC, uint32_t* lpdwSize) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *SetDefaultCommConfigA)(win32::Windows::Win32::Foundation::PSTR lpszName, win32::Windows::Win32::Devices::Communication::COMMCONFIG* lpCC, uint32_t dwSize) noexcept;
    win32::Windows::Win32::Foundation::BOOL (__stdcall *SetDefaultCommConfigW)(win32::Windows::Win32::Foundation::PWSTR lpszName, win32::Windows::Win32::Devices::Communication::COMMCONFIG* lpCC, uint32_t dwSize) noexcept;
};
extern ApiTable g_api_table;

#pragma endregion methods

}
#endif
